/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Moneyly API
 * API para gerenciamento financeiro pessoal
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetUserFinancialPeriods200,
  GetUserFinancialPeriodsPeriodId200,
  GetUserMe200,
  PutUserFinancialPeriod200,
  PutUserFinancialPeriodBody,
  PutUserIncome200,
  PutUserIncomeAndPeriod200,
  PutUserIncomeAndPeriodBody,
  PutUserIncomeBody
} from '../moneylyAPI.schemas';

import { customInstance } from '@/app/(utils)/axios-instance';




/**
 * @summary Perfil do usuário
 */
export const getUserMe = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetUserMe200>(
      {url: `/user/me`, method: 'GET', signal
    },
      );
    }
  



export const getGetUserMeQueryKey = () => {
    return [
    `/user/me`
    ] as const;
    }

    
export const getGetUserMeQueryOptions = <TData = Awaited<ReturnType<typeof getUserMe>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUserMe>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserMe>>> = ({ signal }) => getUserMe(signal);

      

      

   return  { queryKey, queryFn,   staleTime: 10000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserMe>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserMeQueryResult = NonNullable<Awaited<ReturnType<typeof getUserMe>>>
export type GetUserMeQueryError = unknown


/**
 * @summary Perfil do usuário
 */

export function useGetUserMe<TData = Awaited<ReturnType<typeof getUserMe>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUserMe>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUserMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Atualizar rendimento mensal
 */
export const putUserIncome = (
    putUserIncomeBody: PutUserIncomeBody,
 ) => {
      
      
      return customInstance<PutUserIncome200>(
      {url: `/user/income`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putUserIncomeBody
    },
      );
    }
  


export const getPutUserIncomeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUserIncome>>, TError,{data: PutUserIncomeBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putUserIncome>>, TError,{data: PutUserIncomeBody}, TContext> => {

const mutationKey = ['putUserIncome'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putUserIncome>>, {data: PutUserIncomeBody}> = (props) => {
          const {data} = props ?? {};

          return  putUserIncome(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutUserIncomeMutationResult = NonNullable<Awaited<ReturnType<typeof putUserIncome>>>
    export type PutUserIncomeMutationBody = PutUserIncomeBody
    export type PutUserIncomeMutationError = unknown

    /**
 * @summary Atualizar rendimento mensal
 */
export const usePutUserIncome = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUserIncome>>, TError,{data: PutUserIncomeBody}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof putUserIncome>>,
        TError,
        {data: PutUserIncomeBody},
        TContext
      > => {

      const mutationOptions = getPutUserIncomeMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Atualizar período financeiro
 */
export const putUserFinancialPeriod = (
    putUserFinancialPeriodBody: PutUserFinancialPeriodBody,
 ) => {
      
      
      return customInstance<PutUserFinancialPeriod200>(
      {url: `/user/financial-period`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putUserFinancialPeriodBody
    },
      );
    }
  


export const getPutUserFinancialPeriodMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUserFinancialPeriod>>, TError,{data: PutUserFinancialPeriodBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putUserFinancialPeriod>>, TError,{data: PutUserFinancialPeriodBody}, TContext> => {

const mutationKey = ['putUserFinancialPeriod'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putUserFinancialPeriod>>, {data: PutUserFinancialPeriodBody}> = (props) => {
          const {data} = props ?? {};

          return  putUserFinancialPeriod(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutUserFinancialPeriodMutationResult = NonNullable<Awaited<ReturnType<typeof putUserFinancialPeriod>>>
    export type PutUserFinancialPeriodMutationBody = PutUserFinancialPeriodBody
    export type PutUserFinancialPeriodMutationError = unknown

    /**
 * @summary Atualizar período financeiro
 */
export const usePutUserFinancialPeriod = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUserFinancialPeriod>>, TError,{data: PutUserFinancialPeriodBody}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof putUserFinancialPeriod>>,
        TError,
        {data: PutUserFinancialPeriodBody},
        TContext
      > => {

      const mutationOptions = getPutUserFinancialPeriodMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Atualizar rendimento e período financeiro
 */
export const putUserIncomeAndPeriod = (
    putUserIncomeAndPeriodBody: PutUserIncomeAndPeriodBody,
 ) => {
      
      
      return customInstance<PutUserIncomeAndPeriod200>(
      {url: `/user/income-and-period`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putUserIncomeAndPeriodBody
    },
      );
    }
  


export const getPutUserIncomeAndPeriodMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUserIncomeAndPeriod>>, TError,{data: PutUserIncomeAndPeriodBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putUserIncomeAndPeriod>>, TError,{data: PutUserIncomeAndPeriodBody}, TContext> => {

const mutationKey = ['putUserIncomeAndPeriod'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putUserIncomeAndPeriod>>, {data: PutUserIncomeAndPeriodBody}> = (props) => {
          const {data} = props ?? {};

          return  putUserIncomeAndPeriod(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutUserIncomeAndPeriodMutationResult = NonNullable<Awaited<ReturnType<typeof putUserIncomeAndPeriod>>>
    export type PutUserIncomeAndPeriodMutationBody = PutUserIncomeAndPeriodBody
    export type PutUserIncomeAndPeriodMutationError = unknown

    /**
 * @summary Atualizar rendimento e período financeiro
 */
export const usePutUserIncomeAndPeriod = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUserIncomeAndPeriod>>, TError,{data: PutUserIncomeAndPeriodBody}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof putUserIncomeAndPeriod>>,
        TError,
        {data: PutUserIncomeAndPeriodBody},
        TContext
      > => {

      const mutationOptions = getPutUserIncomeAndPeriodMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Listar períodos financeiros
 */
export const getUserFinancialPeriods = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetUserFinancialPeriods200>(
      {url: `/user/financial-periods`, method: 'GET', signal
    },
      );
    }
  



export const getGetUserFinancialPeriodsQueryKey = () => {
    return [
    `/user/financial-periods`
    ] as const;
    }

    
export const getGetUserFinancialPeriodsQueryOptions = <TData = Awaited<ReturnType<typeof getUserFinancialPeriods>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUserFinancialPeriods>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserFinancialPeriodsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserFinancialPeriods>>> = ({ signal }) => getUserFinancialPeriods(signal);

      

      

   return  { queryKey, queryFn,   staleTime: 10000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserFinancialPeriods>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserFinancialPeriodsQueryResult = NonNullable<Awaited<ReturnType<typeof getUserFinancialPeriods>>>
export type GetUserFinancialPeriodsQueryError = unknown


/**
 * @summary Listar períodos financeiros
 */

export function useGetUserFinancialPeriods<TData = Awaited<ReturnType<typeof getUserFinancialPeriods>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUserFinancialPeriods>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUserFinancialPeriodsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Buscar período financeiro por ID
 */
export const getUserFinancialPeriodsPeriodId = (
    periodId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetUserFinancialPeriodsPeriodId200>(
      {url: `/user/financial-periods/${periodId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetUserFinancialPeriodsPeriodIdQueryKey = (periodId?: string,) => {
    return [
    `/user/financial-periods/${periodId}`
    ] as const;
    }

    
export const getGetUserFinancialPeriodsPeriodIdQueryOptions = <TData = Awaited<ReturnType<typeof getUserFinancialPeriodsPeriodId>>, TError = void>(periodId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUserFinancialPeriodsPeriodId>>, TError, TData>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserFinancialPeriodsPeriodIdQueryKey(periodId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserFinancialPeriodsPeriodId>>> = ({ signal }) => getUserFinancialPeriodsPeriodId(periodId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(periodId),  staleTime: 10000,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserFinancialPeriodsPeriodId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserFinancialPeriodsPeriodIdQueryResult = NonNullable<Awaited<ReturnType<typeof getUserFinancialPeriodsPeriodId>>>
export type GetUserFinancialPeriodsPeriodIdQueryError = void


/**
 * @summary Buscar período financeiro por ID
 */

export function useGetUserFinancialPeriodsPeriodId<TData = Awaited<ReturnType<typeof getUserFinancialPeriodsPeriodId>>, TError = void>(
 periodId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getUserFinancialPeriodsPeriodId>>, TError, TData>, }
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUserFinancialPeriodsPeriodIdQueryOptions(periodId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



