/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { userSchema } from "./userSchema.js";

export const authResponseSchema = z.object({
  success: z.optional(z.boolean()),
  data: z.optional(
    z.object({
      user: z.optional(z.lazy(() => userSchema)),
      token: z.optional(z.string()),
    })
  ),
  message: z.optional(z.string()),
});
