/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const budgetSchema = z.object({
  id: z.string().uuid(),
  userId: z.string().uuid(),
  categoryId: z.string().uuid(),
  monthlyLimit: z.string(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  spent: z.optional(z.number()),
  remaining: z.optional(z.number()),
  percentage: z.optional(z.number()),
  status: z.optional(
    z.enum(["safe", "warning", "danger", "exceeded", "attention"]),
  ),
  category: z.optional(
    z.object({
      id: z.string().uuid(),
      name: z.string(),
    }),
  ),
});
