/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const deleteGoalsIdPathParamsSchema = z.object({
    "id": z.string()
    })

/**
 * @description Deletada
 */
export const deleteGoalsId200Schema = z.any()

export const deleteGoalsIdMutationResponseSchema = z.lazy(() => deleteGoalsId200Schema)