/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const deleteGoalsIdPathParamsSchema = z.object({
  id: z.string().uuid(),
});

/**
 * @description Deletada
 */
export const deleteGoalsId200Schema = z.object({
  success: z.boolean(),
  message: z.optional(z.string()),
});

export const deleteGoalsIdMutationResponseSchema = z.lazy(
  () => deleteGoalsId200Schema,
);
