/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const deleteBudgetsIdPathParamsSchema = z.object({
  id: z.string().uuid(),
});

/**
 * @description Deletado
 */
export const deleteBudgetsId200Schema = z.object({
  success: z.boolean(),
  message: z.optional(z.string()),
});

export const deleteBudgetsIdMutationResponseSchema = z.lazy(
  () => deleteBudgetsId200Schema,
);
