/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const deleteTransactionsIdPathParamsSchema = z.object({
  id: z.string().uuid(),
});

/**
 * @description Deletada
 */
export const deleteTransactionsId200Schema = z.object({
  success: z.boolean(),
  message: z.optional(z.string()),
});

export const deleteTransactionsIdMutationResponseSchema = z.lazy(
  () => deleteTransactionsId200Schema,
);
