/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const deleteBudgetsIdPathParamsSchema = z.object({
    "id": z.string()
    })

/**
 * @description Deletado
 */
export const deleteBudgetsId200Schema = z.any()

export const deleteBudgetsIdMutationResponseSchema = z.lazy(() => deleteBudgetsId200Schema)