/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { budgetSchema } from "./budgetSchema.js";

/**
 * @description Lista de orçamentos
 */
export const getBudgets200Schema = z.object({
  success: z.optional(z.boolean()),
  data: z.optional(z.array(z.lazy(() => budgetSchema))),
  message: z.optional(z.string()),
});

export const getBudgetsQueryResponseSchema = z.lazy(() => getBudgets200Schema);
