/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { budgetSchema } from "./budgetSchema.ts";

/**
 * @description Lista de orçamentos
 */
export const getBudgets200Schema = z.object({
  success: z.boolean(),
  data: z.array(z.lazy(() => budgetSchema)),
  message: z.optional(z.string()),
});

export const getBudgetsQueryResponseSchema = z.lazy(() => getBudgets200Schema);
