/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { categorySchema } from "./categorySchema.ts";
import { paginationSchema } from "./paginationSchema.ts";

export const getCategoriesQueryParamsSchema = z
  .object({
    page: z.optional(z.coerce.number()),
    limit: z.optional(z.coerce.number()),
  })
  .optional();

/**
 * @description Lista de categorias
 */
export const getCategories200Schema = z.object({
  success: z.boolean(),
  data: z.array(z.lazy(() => categorySchema)),
  pagination: z.lazy(() => paginationSchema),
  message: z.optional(z.string()),
});

export const getCategoriesQueryResponseSchema = z.lazy(
  () => getCategories200Schema,
);
