/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { goalSchema } from "./goalSchema.ts";

/**
 * @description Lista de metas
 */
export const getGoals200Schema = z.object({
  success: z.boolean(),
  data: z.array(z.lazy(() => goalSchema)),
  message: z.optional(z.string()),
});

export const getGoalsQueryResponseSchema = z.lazy(() => getGoals200Schema);
