/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { goalSchema } from "./goalSchema.ts";

export const getGoalsIdPathParamsSchema = z.object({
  id: z.string().uuid(),
});

/**
 * @description Detalhes da meta
 */
export const getGoalsId200Schema = z.object({
  success: z.boolean(),
  data: z.lazy(() => goalSchema),
  message: z.optional(z.string()),
});

export const getGoalsIdQueryResponseSchema = z.lazy(() => getGoalsId200Schema);
