/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { plannerAlertSchema } from "./plannerAlertSchema.ts";
import { plannerStatsSchema } from "./plannerStatsSchema.ts";

/**
 * @description Planejamento financeiro
 */
export const getOverviewPlanner200Schema = z.object({
  success: z.boolean(),
  data: z.object({
    stats: z.lazy(() => plannerStatsSchema),
    currentPeriod: z.object({
      startDate: z.string().datetime(),
      endDate: z.string().datetime(),
      description: z.string(),
    }),
    alerts: z.array(z.lazy(() => plannerAlertSchema)),
  }),
  message: z.optional(z.string()),
});

export const getOverviewPlannerQueryResponseSchema = z.lazy(
  () => getOverviewPlanner200Schema,
);
