/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

/**
 * @description Planejamento financeiro
 */
export const getOverviewPlanner200Schema = z.object({
    "success": z.optional(z.boolean()),
"data": z.optional(z.object({
    "stats": z.optional(z.object({
    
    })),
"alerts": z.optional(z.array(z.string()))
    })),
"message": z.optional(z.string())
    })

export const getOverviewPlannerQueryResponseSchema = z.lazy(() => getOverviewPlanner200Schema)