/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Resumo financeiro
 */
export const getTransactionsSummary200Schema = z.object({
  success: z.boolean(),
  data: z.object({
    totalIncome: z.number(),
    totalExpenses: z.number(),
    balance: z.number(),
    monthlyIncome: z.number(),
    percentUsed: z.number(),
    alert: z.string().nullish(),
    byCategory: z.optional(z.object({}).catchall(z.number())),
  }),
  message: z.optional(z.string()),
});

export const getTransactionsSummaryQueryResponseSchema = z.lazy(
  () => getTransactionsSummary200Schema,
);
