/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { paginatedResponseSchema } from "./paginatedResponseSchema";

export const getTransactionsQueryParamsSchema = z
  .object({
    page: z.optional(z.coerce.number()),
    limit: z.optional(z.coerce.number()),
  })
  .optional();

/**
 * @description Lista de transações
 */
export const getTransactions200Schema = z.lazy(() => paginatedResponseSchema);

export const getTransactionsQueryResponseSchema = z.lazy(
  () => getTransactions200Schema
);
