/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { financialPeriodSchema } from "./financialPeriodSchema.ts";

/**
 * @description Lista de períodos financeiros
 */
export const getUserFinancialPeriods200Schema = z.object({
  success: z.boolean(),
  data: z.array(z.lazy(() => financialPeriodSchema)),
  message: z.optional(z.string()),
});

export const getUserFinancialPeriodsQueryResponseSchema = z.lazy(
  () => getUserFinancialPeriods200Schema,
);
