/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { userSchema } from "./userSchema.ts";

/**
 * @description Dados do usuário
 */
export const getUserMe200Schema = z.object({
  success: z.boolean(),
  data: z.lazy(() => userSchema),
  message: z.optional(z.string()),
});

export const getUserMeQueryResponseSchema = z.lazy(() => getUserMe200Schema);
