/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { userSchema } from "./userSchema.js";

/**
 * @description Dados do usuário
 */
export const getUserMe200Schema = z.object({
  success: z.optional(z.boolean()),
  data: z.optional(z.lazy(() => userSchema)),
  message: z.optional(z.string()),
});

export const getUserMeQueryResponseSchema = z.lazy(() => getUserMe200Schema);
