/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const goalSchema = z.object({
    "id": z.optional(z.string().uuid()),
"title": z.optional(z.string()),
"description": z.optional(z.string()),
"targetAmount": z.optional(z.string()),
"currentAmount": z.optional(z.string()),
"targetDate": z.optional(z.string().datetime()),
"isActive": z.optional(z.boolean()),
"createdAt": z.optional(z.string().datetime()),
"progress": z.optional(z.object({
    "percentage": z.optional(z.number()),
"daysRemaining": z.optional(z.number())
    })),
"milestones": z.optional(z.array(z.object({
    "id": z.optional(z.string().uuid()),
"percentage": z.optional(z.number()),
"amount": z.optional(z.string()),
"isReached": z.optional(z.boolean())
    })))
    })