/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const monthlyChartItemSchema = z
  .object({
    month: z.string().describe("Formato yyyy-MM"),
    label: z.string().describe("Ex: maio 2026"),
    income: z.number(),
  })
  .catchall(z.number());
