/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { transactionSchema } from "./transactionSchema.js";

export const paginatedTransactionsSchema = z.object({
  data: z.optional(z.array(z.lazy(() => transactionSchema))),
  pagination: z.optional(
    z.object({
      page: z.optional(z.number()),
      limit: z.optional(z.number()),
      total: z.optional(z.number()),
      totalPages: z.optional(z.number()),
    })
  ),
});
