/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { recurringTransactionSchema } from "./recurringTransactionSchema.ts";

export const patchRecurringTransactionsIdReactivatePathParamsSchema = z.object({
  id: z.string().uuid(),
});

/**
 * @description Reativada
 */
export const patchRecurringTransactionsIdReactivate200Schema = z.object({
  success: z.boolean(),
  data: z.lazy(() => recurringTransactionSchema),
  message: z.optional(z.string()),
});

/**
 * @description Não encontrada
 */
export const patchRecurringTransactionsIdReactivate404Schema = z.any();

export const patchRecurringTransactionsIdReactivateMutationResponseSchema =
  z.lazy(() => patchRecurringTransactionsIdReactivate200Schema);
