/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { goalSchema } from "./goalSchema";

/**
 * @description Criada
 */
export const postGoals201Schema = z.object({
  success: z.optional(z.boolean()),
  data: z.optional(z.lazy(() => goalSchema)),
  message: z.optional(z.string()),
});

export const postGoalsMutationRequestSchema = z.object({
  title: z.string(),
  description: z.optional(z.string()),
  targetAmount: z.number(),
  targetDate: z.string().date(),
});

export const postGoalsMutationResponseSchema = z.lazy(() => postGoals201Schema);
