/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { budgetSchema } from "./budgetSchema.ts";

/**
 * @description Criado
 */
export const postBudgets201Schema = z.object({
  success: z.boolean(),
  data: z.lazy(() => budgetSchema),
  message: z.optional(z.string()),
});

export const postBudgetsMutationRequestSchema = z.object({
  categoryId: z.string().uuid(),
  monthlyLimit: z.number(),
});

export const postBudgetsMutationResponseSchema = z.lazy(
  () => postBudgets201Schema,
);
