/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { authResponseSchema } from "./authResponseSchema.js";

/**
 * @description Usuário criado
 */
export const postAuthSignUp201Schema = z.lazy(() => authResponseSchema);

/**
 * @description Email já cadastrado
 */
export const postAuthSignUp409Schema = z.any();

export const postAuthSignUpMutationRequestSchema = z.object({
  name: z.string(),
  email: z.string().email(),
  password: z.string().min(6),
});

export const postAuthSignUpMutationResponseSchema = z.lazy(
  () => postAuthSignUp201Schema
);
