/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { userSchema } from "./userSchema";

/**
 * @description Token renovado
 */
export const postAuthRefresh200Schema = z.object({
  success: z.optional(z.boolean()),
  data: z.optional(
    z.object({
      user: z.optional(z.lazy(() => userSchema)),
      accessToken: z.optional(z.string()),
    })
  ),
  message: z.optional(z.string()),
});

/**
 * @description Refresh token inválido ou expirado
 */
export const postAuthRefresh401Schema = z.any();

export const postAuthRefreshMutationRequestSchema = z.object({
  refreshToken: z.string(),
});

export const postAuthRefreshMutationResponseSchema = z.lazy(
  () => postAuthRefresh200Schema
);
