/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { categorySchema } from "./categorySchema.ts";

/**
 * @description Categoria criada
 */
export const postCategoriesCreate201Schema = z.object({
  success: z.boolean(),
  data: z.lazy(() => categorySchema),
  message: z.optional(z.string()),
});

export const postCategoriesCreateMutationRequestSchema = z.object({
  name: z.string(),
});

export const postCategoriesCreateMutationResponseSchema = z.lazy(
  () => postCategoriesCreate201Schema,
);
