/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { transactionSchema } from "./transactionSchema";

/**
 * @description Transação criada
 */
export const postTransactionsCreate201Schema = z.object({
  success: z.optional(z.boolean()),
  data: z.optional(z.lazy(() => transactionSchema)),
  message: z.optional(z.string()),
});

export const postTransactionsCreateMutationRequestSchema = z.object({
  type: z.enum(["income", "expense"]),
  title: z.string(),
  amount: z.number(),
  category: z.string().uuid(),
  description: z.optional(z.string()),
  date: z.optional(z.string().datetime()),
});

export const postTransactionsCreateMutationResponseSchema = z.lazy(
  () => postTransactionsCreate201Schema
);
