/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { authResponseSchema } from "./authResponseSchema.ts";

/**
 * @description Login com Google realizado
 */
export const postAuthGoogle200Schema = z.lazy(() => authResponseSchema);

/**
 * @description Falha na autenticação com Google
 */
export const postAuthGoogle401Schema = z.any();

export const postAuthGoogleMutationRequestSchema = z.object({
  idToken: z.string(),
});

export const postAuthGoogleMutationResponseSchema = z.lazy(
  () => postAuthGoogle200Schema,
);
