/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { recurringTransactionSchema } from "./recurringTransactionSchema.ts";

/**
 * @description Criada
 */
export const postRecurringTransactions201Schema = z.object({
  success: z.boolean(),
  data: z.lazy(() => recurringTransactionSchema),
  message: z.optional(z.string()),
});

export const postRecurringTransactionsMutationRequestSchema = z.object({
  type: z.enum(["income", "expense"]),
  title: z.string(),
  amount: z.number(),
  categoryId: z.string().uuid(),
  frequency: z.enum(["daily", "weekly", "monthly", "yearly"]),
  dayOfMonth: z.optional(
    z.number().min(1).max(31).describe("Dia do mês (para frequency=monthly)"),
  ),
  dayOfWeek: z.optional(
    z
      .number()
      .min(0)
      .max(6)
      .describe("Dia da semana (0=domingo, 6=sábado, para frequency=weekly)"),
  ),
  description: z.optional(z.string()),
  totalInstallments: z.optional(
    z
      .number()
      .min(1)
      .describe("Quantidade de parcelas. Omitir para recorrência sem fim"),
  ),
  startDate: z.optional(
    z
      .string()
      .datetime()
      .describe(
        "Data de início. Se <= hoje cria imediatamente. Se futura, agenda. Omitir = agora",
      ),
  ),
});

export const postRecurringTransactionsMutationResponseSchema = z.lazy(
  () => postRecurringTransactions201Schema,
);
