/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { categorySchema } from "./categorySchema";

export const putCategoriesUpdateIdPathParamsSchema = z.object({
  id: z.string().uuid(),
});

/**
 * @description Categoria atualizada
 */
export const putCategoriesUpdateId200Schema = z.object({
  success: z.optional(z.boolean()),
  data: z.optional(z.lazy(() => categorySchema)),
  message: z.optional(z.string()),
});

export const putCategoriesUpdateIdMutationRequestSchema = z.object({
  name: z.string(),
});

export const putCategoriesUpdateIdMutationResponseSchema = z.lazy(
  () => putCategoriesUpdateId200Schema
);
