/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const putGoalsIdPathParamsSchema = z.object({
    "id": z.string()
    })

/**
 * @description Atualizada
 */
export const putGoalsId200Schema = z.any()

export const putGoalsIdMutationResponseSchema = z.lazy(() => putGoalsId200Schema)