/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { goalSchema } from "./goalSchema.ts";

export const putGoalsIdPathParamsSchema = z.object({
  id: z.string().uuid(),
});

/**
 * @description Atualizada
 */
export const putGoalsId200Schema = z.object({
  success: z.boolean(),
  data: z.lazy(() => goalSchema),
  message: z.optional(z.string()),
});

export const putGoalsIdMutationRequestSchema = z.object({
  title: z.optional(z.string()),
  description: z.optional(z.string()),
  targetAmount: z.optional(z.number()),
  targetDate: z.optional(z.string().date()),
  currentAmount: z.optional(z.number()),
  isActive: z.optional(z.boolean()),
});

export const putGoalsIdMutationResponseSchema = z.lazy(
  () => putGoalsId200Schema,
);
