/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { recurringTransactionSchema } from "./recurringTransactionSchema.ts";

export const putRecurringTransactionsIdPathParamsSchema = z.object({
  id: z.string().uuid(),
});

/**
 * @description Atualizada
 */
export const putRecurringTransactionsId200Schema = z.object({
  success: z.boolean(),
  data: z.lazy(() => recurringTransactionSchema),
  message: z.optional(z.string()),
});

/**
 * @description Não encontrada
 */
export const putRecurringTransactionsId404Schema = z.any();

export const putRecurringTransactionsIdMutationRequestSchema = z.object({
  title: z.optional(z.string()),
  amount: z.optional(z.number()),
  categoryId: z.optional(z.string().uuid()),
  frequency: z.optional(z.enum(["daily", "weekly", "monthly", "yearly"])),
  dayOfMonth: z.optional(z.number().min(1).max(31)),
  dayOfWeek: z.optional(z.number().min(0).max(6)),
  description: z.optional(z.string()),
  isActive: z.optional(z.boolean()),
  totalInstallments: z.optional(
    z.number().min(1).describe("Quantidade total de parcelas"),
  ),
});

export const putRecurringTransactionsIdMutationResponseSchema = z.lazy(
  () => putRecurringTransactionsId200Schema,
);
