/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { transactionSchema } from "./transactionSchema.ts";

export const putTransactionsIdPathParamsSchema = z.object({
  id: z.string().uuid(),
});

/**
 * @description Atualizada
 */
export const putTransactionsId200Schema = z.object({
  success: z.boolean(),
  data: z.lazy(() => transactionSchema),
  message: z.optional(z.string()),
});

export const putTransactionsIdMutationRequestSchema = z.object({
  type: z.optional(z.enum(["income", "expense"])),
  title: z.optional(z.string()),
  amount: z.optional(z.number()),
  category: z.optional(z.string().uuid()),
  description: z.optional(z.string()),
  date: z.optional(z.string().datetime()),
});

export const putTransactionsIdMutationResponseSchema = z.lazy(
  () => putTransactionsId200Schema,
);
