/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

/**
 * @description Rendimento e período financeiro atualizados
 */
export const putUserIncomeAndPeriod200Schema = z.object({
    "success": z.optional(z.boolean()),
"data": z.optional(z.object({
    "monthlyIncome": z.optional(z.number()),
"financialDayStart": z.optional(z.number()),
"financialDayEnd": z.optional(z.number()),
"firstAccess": z.optional(z.boolean())
    })),
"message": z.optional(z.string())
    })

export const putUserIncomeAndPeriodMutationRequestSchema = z.object({
    "monthlyIncome": z.number().min(0.01).max(999999999.99),
"financialDayStart": z.number().min(1).max(31),
"financialDayEnd": z.number().min(1).max(31)
    })

export const putUserIncomeAndPeriodMutationResponseSchema = z.lazy(() => putUserIncomeAndPeriod200Schema)