/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Rendimento atualizado
 */
export const putUserIncome200Schema = z.object({
  success: z.boolean(),
  data: z.object({
    monthlyIncome: z.number(),
    firstAccess: z.boolean(),
  }),
  message: z.optional(z.string()),
});

export const putUserIncomeMutationRequestSchema = z.object({
  monthlyIncome: z.number().min(0.01).max(999999999.99),
});

export const putUserIncomeMutationResponseSchema = z.lazy(
  () => putUserIncome200Schema,
);
