/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const recurringTransactionSchema = z.object({
  id: z.string().uuid(),
  userId: z.string().uuid(),
  type: z.enum(["income", "expense"]),
  title: z.string(),
  amount: z.string(),
  description: z.string().nullish(),
  categoryId: z.string().uuid(),
  frequency: z.enum(["daily", "weekly", "monthly", "yearly"]),
  dayOfMonth: z.number().min(1).max(31).nullish(),
  dayOfWeek: z.number().min(0).max(6).nullish(),
  startDate: z
    .string()
    .datetime()
    .describe("Data de início. null = criado imediatamente")
    .nullish(),
  totalInstallments: z
    .number()
    .describe("Total de parcelas. null = sem limite")
    .nullish(),
  executedInstallments: z.optional(
    z.number().describe("Quantas parcelas já foram executadas"),
  ),
  isActive: z.boolean(),
  nextExecution: z.string().datetime(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
