/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const successResponseSchema = z.object({
  success: z.boolean(),
  data: z.optional(z.object({})),
  message: z.optional(z.string()),
});
