/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const transactionListSummarySchema = z.object({
  totalExpense: z.number().describe("Total de despesas no período filtrado"),
  totalIncome: z.number().describe("Total de receitas no período filtrado"),
  monthlyIncome: z
    .number()
    .describe("Rendimento mensal cadastrado pelo usuário"),
  percentUsed: z.number().describe("% do rendimento gasto").nullish(),
  alert: z.string().describe("Alerta se percentUsed >= 80%").nullish(),
});
