/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const transactionSchema = z.object({
  id: z.string().uuid(),
  userId: z.string().uuid(),
  type: z.enum(["income", "expense"]),
  title: z.string(),
  amount: z.string(),
  description: z.string().nullish(),
  date: z.string().datetime(),
  categoryId: z.string().uuid(),
  periodId: z.string().uuid().nullish(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  category: z.optional(
    z.object({
      id: z.string().uuid(),
      name: z.string(),
    }),
  ),
});
