/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const userSchema = z.object({
    "id": z.optional(z.string().uuid()),
"name": z.optional(z.string()),
"email": z.optional(z.string().email()),
"monthlyIncome": z.optional(z.number()),
"financialDayStart": z.optional(z.number().min(1).max(31)),
"financialDayEnd": z.optional(z.number().min(1).max(31)),
"firstAccess": z.optional(z.boolean()),
"createdAt": z.optional(z.string().datetime())
    })