/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const userSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  email: z.string().email(),
  googleId: z.string().nullish(),
  avatar: z.string().nullish(),
  monthlyIncome: z.string().nullish(),
  financialDayStart: z.number().min(1).max(31).nullish(),
  financialDayEnd: z.number().min(1).max(31).nullish(),
  firstAccess: z.boolean().nullish(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
