/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const userSchema = z.object({
    "id": z.optional(z.string().uuid()),
"name": z.optional(z.string()),
"email": z.optional(z.string().email()),
"googleId": z.string().nullish(),
"avatar": z.string().nullish(),
"monthlyIncome": z.string().nullish(),
"financialDayStart": z.number().min(1).max(31).nullish(),
"financialDayEnd": z.number().min(1).max(31).nullish(),
"firstAccess": z.boolean().nullish(),
"createdAt": z.optional(z.string().datetime()),
"updatedAt": z.optional(z.string().datetime())
    })