/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Moneyly API
 * API para gerenciamento financeiro pessoal
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  AuthResponse,
  PostAuthGoogleBody,
  PostAuthLogout200,
  PostAuthLogoutBody,
  PostAuthRefresh200,
  PostAuthRefreshBody,
  PostAuthSignInBody,
  PostAuthSignUpBody
} from '../moneylyAPI.schemas';

import { customInstance } from '@/app/(utils)/axios-instance';




/**
 * @summary Cadastrar usuário
 */
export const postAuthSignUp = (
    postAuthSignUpBody: PostAuthSignUpBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AuthResponse>(
      {url: `/auth/sign-up`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAuthSignUpBody, signal
    },
      );
    }
  


export const getPostAuthSignUpMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthSignUp>>, TError,{data: PostAuthSignUpBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthSignUp>>, TError,{data: PostAuthSignUpBody}, TContext> => {

const mutationKey = ['postAuthSignUp'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthSignUp>>, {data: PostAuthSignUpBody}> = (props) => {
          const {data} = props ?? {};

          return  postAuthSignUp(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthSignUpMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthSignUp>>>
    export type PostAuthSignUpMutationBody = PostAuthSignUpBody
    export type PostAuthSignUpMutationError = void

    /**
 * @summary Cadastrar usuário
 */
export const usePostAuthSignUp = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthSignUp>>, TError,{data: PostAuthSignUpBody}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthSignUp>>,
        TError,
        {data: PostAuthSignUpBody},
        TContext
      > => {

      const mutationOptions = getPostAuthSignUpMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Fazer login
 */
export const postAuthSignIn = (
    postAuthSignInBody: PostAuthSignInBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AuthResponse>(
      {url: `/auth/sign-in`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAuthSignInBody, signal
    },
      );
    }
  


export const getPostAuthSignInMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthSignIn>>, TError,{data: PostAuthSignInBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthSignIn>>, TError,{data: PostAuthSignInBody}, TContext> => {

const mutationKey = ['postAuthSignIn'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthSignIn>>, {data: PostAuthSignInBody}> = (props) => {
          const {data} = props ?? {};

          return  postAuthSignIn(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthSignInMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthSignIn>>>
    export type PostAuthSignInMutationBody = PostAuthSignInBody
    export type PostAuthSignInMutationError = void

    /**
 * @summary Fazer login
 */
export const usePostAuthSignIn = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthSignIn>>, TError,{data: PostAuthSignInBody}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthSignIn>>,
        TError,
        {data: PostAuthSignInBody},
        TContext
      > => {

      const mutationOptions = getPostAuthSignInMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Login com Google
 */
export const postAuthGoogle = (
    postAuthGoogleBody: PostAuthGoogleBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<AuthResponse>(
      {url: `/auth/google`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAuthGoogleBody, signal
    },
      );
    }
  


export const getPostAuthGoogleMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthGoogle>>, TError,{data: PostAuthGoogleBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthGoogle>>, TError,{data: PostAuthGoogleBody}, TContext> => {

const mutationKey = ['postAuthGoogle'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthGoogle>>, {data: PostAuthGoogleBody}> = (props) => {
          const {data} = props ?? {};

          return  postAuthGoogle(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthGoogleMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthGoogle>>>
    export type PostAuthGoogleMutationBody = PostAuthGoogleBody
    export type PostAuthGoogleMutationError = void

    /**
 * @summary Login com Google
 */
export const usePostAuthGoogle = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthGoogle>>, TError,{data: PostAuthGoogleBody}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthGoogle>>,
        TError,
        {data: PostAuthGoogleBody},
        TContext
      > => {

      const mutationOptions = getPostAuthGoogleMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Renovar access token
 */
export const postAuthRefresh = (
    postAuthRefreshBody: PostAuthRefreshBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PostAuthRefresh200>(
      {url: `/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAuthRefreshBody, signal
    },
      );
    }
  


export const getPostAuthRefreshMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError,{data: PostAuthRefreshBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError,{data: PostAuthRefreshBody}, TContext> => {

const mutationKey = ['postAuthRefresh'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthRefresh>>, {data: PostAuthRefreshBody}> = (props) => {
          const {data} = props ?? {};

          return  postAuthRefresh(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthRefresh>>>
    export type PostAuthRefreshMutationBody = PostAuthRefreshBody
    export type PostAuthRefreshMutationError = void

    /**
 * @summary Renovar access token
 */
export const usePostAuthRefresh = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError,{data: PostAuthRefreshBody}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthRefresh>>,
        TError,
        {data: PostAuthRefreshBody},
        TContext
      > => {

      const mutationOptions = getPostAuthRefreshMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Fazer logout
 */
export const postAuthLogout = (
    postAuthLogoutBody: PostAuthLogoutBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PostAuthLogout200>(
      {url: `/auth/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAuthLogoutBody, signal
    },
      );
    }
  


export const getPostAuthLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,{data: PostAuthLogoutBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,{data: PostAuthLogoutBody}, TContext> => {

const mutationKey = ['postAuthLogout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogout>>, {data: PostAuthLogoutBody}> = (props) => {
          const {data} = props ?? {};

          return  postAuthLogout(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogout>>>
    export type PostAuthLogoutMutationBody = PostAuthLogoutBody
    export type PostAuthLogoutMutationError = unknown

    /**
 * @summary Fazer logout
 */
export const usePostAuthLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,{data: PostAuthLogoutBody}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogout>>,
        TError,
        {data: PostAuthLogoutBody},
        TContext
      > => {

      const mutationOptions = getPostAuthLogoutMutationOptions(options);

      return useMutation(mutationOptions);
    }
    