/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Moneyly API
 * API para gerenciamento financeiro pessoal
 * OpenAPI spec version: 1.0.0
 */
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";

import type {
  GetOverviewDashboard200,
  GetOverviewDashboardParams,
  GetOverviewPeriods200,
  GetOverviewPlanner200,
} from "../moneylyAPI.schemas";

import { customInstance } from "@/app/(utils)/axios-instance";

/**
 * @summary Listar períodos financeiros disponíveis
 */
export const getOverviewPeriods = (signal?: AbortSignal) => {
  return customInstance<GetOverviewPeriods200>({
    url: `/overview/periods`,
    method: "GET",
    signal,
  });
};

export const getGetOverviewPeriodsQueryKey = () => {
  return [`/overview/periods`] as const;
};

export const getGetOverviewPeriodsQueryOptions = <
  TData = Awaited<ReturnType<typeof getOverviewPeriods>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getOverviewPeriods>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOverviewPeriodsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOverviewPeriods>>
  > = ({ signal }) => getOverviewPeriods(signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOverviewPeriods>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetOverviewPeriodsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOverviewPeriods>>
>;
export type GetOverviewPeriodsQueryError = unknown;

/**
 * @summary Listar períodos financeiros disponíveis
 */

export function useGetOverviewPeriods<
  TData = Awaited<ReturnType<typeof getOverviewPeriods>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getOverviewPeriods>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetOverviewPeriodsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Dados do dashboard
 */
export const getOverviewDashboard = (
  params?: GetOverviewDashboardParams,
  signal?: AbortSignal
) => {
  return customInstance<GetOverviewDashboard200>({
    url: `/overview/dashboard`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetOverviewDashboardQueryKey = (
  params?: GetOverviewDashboardParams
) => {
  return [`/overview/dashboard`, ...(params ? [params] : [])] as const;
};

export const getGetOverviewDashboardQueryOptions = <
  TData = Awaited<ReturnType<typeof getOverviewDashboard>>,
  TError = unknown
>(
  params?: GetOverviewDashboardParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getOverviewDashboard>>,
      TError,
      TData
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetOverviewDashboardQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOverviewDashboard>>
  > = ({ signal }) => getOverviewDashboard(params, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOverviewDashboard>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetOverviewDashboardQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOverviewDashboard>>
>;
export type GetOverviewDashboardQueryError = unknown;

/**
 * @summary Dados do dashboard
 */

export function useGetOverviewDashboard<
  TData = Awaited<ReturnType<typeof getOverviewDashboard>>,
  TError = unknown
>(
  params?: GetOverviewDashboardParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getOverviewDashboard>>,
      TError,
      TData
    >;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetOverviewDashboardQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Planejamento financeiro
 */
export const getOverviewPlanner = (signal?: AbortSignal) => {
  return customInstance<GetOverviewPlanner200>({
    url: `/overview/planner`,
    method: "GET",
    signal,
  });
};

export const getGetOverviewPlannerQueryKey = () => {
  return [`/overview/planner`] as const;
};

export const getGetOverviewPlannerQueryOptions = <
  TData = Awaited<ReturnType<typeof getOverviewPlanner>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getOverviewPlanner>>,
    TError,
    TData
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOverviewPlannerQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOverviewPlanner>>
  > = ({ signal }) => getOverviewPlanner(signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOverviewPlanner>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetOverviewPlannerQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOverviewPlanner>>
>;
export type GetOverviewPlannerQueryError = unknown;

/**
 * @summary Planejamento financeiro
 */

export function useGetOverviewPlanner<
  TData = Awaited<ReturnType<typeof getOverviewPlanner>>,
  TError = unknown
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getOverviewPlanner>>,
    TError,
    TData
  >;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetOverviewPlannerQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
