/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Moneyly API
 * ARQUIVO GERADO por `pnpm openapi:gen` (zod-to-openapi). NÃO editar à mão. Ver moneyly/.specs/01-api-contract.md
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetOverviewDashboard200,
  GetOverviewDashboard400,
  GetOverviewDashboard401,
  GetOverviewDashboardParams,
  GetOverviewForecast200,
  GetOverviewForecast400,
  GetOverviewForecast401,
  GetOverviewForecastParams,
  GetOverviewInsights200,
  GetOverviewInsights400,
  GetOverviewInsights401,
  GetOverviewInsightsComparison200,
  GetOverviewInsightsComparison400,
  GetOverviewInsightsComparison401,
  GetOverviewInsightsComparisonParams,
  GetOverviewPeriods200,
  GetOverviewPeriods400,
  GetOverviewPeriods401,
  GetOverviewPlanner200,
  GetOverviewPlanner400,
  GetOverviewPlanner401,
} from "../moneylyAPI.schemas";

import { customInstance } from "../../../../(utils)/axios-instance";

/**
 * @summary Períodos financeiros disponíveis
 */
export const getOverviewPeriods = (signal?: AbortSignal) => {
  return customInstance<GetOverviewPeriods200>({
    url: `/overview/periods`,
    method: "GET",
    signal,
  });
};

export const getGetOverviewPeriodsQueryKey = () => {
  return [`/overview/periods`] as const;
};

export const getGetOverviewPeriodsQueryOptions = <
  TData = Awaited<ReturnType<typeof getOverviewPeriods>>,
  TError = GetOverviewPeriods400 | GetOverviewPeriods401,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getOverviewPeriods>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOverviewPeriodsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOverviewPeriods>>
  > = ({ signal }) => getOverviewPeriods(signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOverviewPeriods>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOverviewPeriodsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOverviewPeriods>>
>;
export type GetOverviewPeriodsQueryError =
  | GetOverviewPeriods400
  | GetOverviewPeriods401;

export function useGetOverviewPeriods<
  TData = Awaited<ReturnType<typeof getOverviewPeriods>>,
  TError = GetOverviewPeriods400 | GetOverviewPeriods401,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewPeriods>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOverviewPeriods>>,
          TError,
          Awaited<ReturnType<typeof getOverviewPeriods>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOverviewPeriods<
  TData = Awaited<ReturnType<typeof getOverviewPeriods>>,
  TError = GetOverviewPeriods400 | GetOverviewPeriods401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewPeriods>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOverviewPeriods>>,
          TError,
          Awaited<ReturnType<typeof getOverviewPeriods>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOverviewPeriods<
  TData = Awaited<ReturnType<typeof getOverviewPeriods>>,
  TError = GetOverviewPeriods400 | GetOverviewPeriods401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewPeriods>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Períodos financeiros disponíveis
 */

export function useGetOverviewPeriods<
  TData = Awaited<ReturnType<typeof getOverviewPeriods>>,
  TError = GetOverviewPeriods400 | GetOverviewPeriods401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewPeriods>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOverviewPeriodsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Dados do dashboard
 */
export const getOverviewDashboard = (
  params?: GetOverviewDashboardParams,
  signal?: AbortSignal,
) => {
  return customInstance<GetOverviewDashboard200>({
    url: `/overview/dashboard`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetOverviewDashboardQueryKey = (
  params?: GetOverviewDashboardParams,
) => {
  return [`/overview/dashboard`, ...(params ? [params] : [])] as const;
};

export const getGetOverviewDashboardQueryOptions = <
  TData = Awaited<ReturnType<typeof getOverviewDashboard>>,
  TError = GetOverviewDashboard400 | GetOverviewDashboard401,
>(
  params?: GetOverviewDashboardParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewDashboard>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetOverviewDashboardQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOverviewDashboard>>
  > = ({ signal }) => getOverviewDashboard(params, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOverviewDashboard>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOverviewDashboardQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOverviewDashboard>>
>;
export type GetOverviewDashboardQueryError =
  | GetOverviewDashboard400
  | GetOverviewDashboard401;

export function useGetOverviewDashboard<
  TData = Awaited<ReturnType<typeof getOverviewDashboard>>,
  TError = GetOverviewDashboard400 | GetOverviewDashboard401,
>(
  params: undefined | GetOverviewDashboardParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewDashboard>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOverviewDashboard>>,
          TError,
          Awaited<ReturnType<typeof getOverviewDashboard>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOverviewDashboard<
  TData = Awaited<ReturnType<typeof getOverviewDashboard>>,
  TError = GetOverviewDashboard400 | GetOverviewDashboard401,
>(
  params?: GetOverviewDashboardParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewDashboard>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOverviewDashboard>>,
          TError,
          Awaited<ReturnType<typeof getOverviewDashboard>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOverviewDashboard<
  TData = Awaited<ReturnType<typeof getOverviewDashboard>>,
  TError = GetOverviewDashboard400 | GetOverviewDashboard401,
>(
  params?: GetOverviewDashboardParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewDashboard>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Dados do dashboard
 */

export function useGetOverviewDashboard<
  TData = Awaited<ReturnType<typeof getOverviewDashboard>>,
  TError = GetOverviewDashboard400 | GetOverviewDashboard401,
>(
  params?: GetOverviewDashboardParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewDashboard>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOverviewDashboardQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Planejamento financeiro
 */
export const getOverviewPlanner = (signal?: AbortSignal) => {
  return customInstance<GetOverviewPlanner200>({
    url: `/overview/planner`,
    method: "GET",
    signal,
  });
};

export const getGetOverviewPlannerQueryKey = () => {
  return [`/overview/planner`] as const;
};

export const getGetOverviewPlannerQueryOptions = <
  TData = Awaited<ReturnType<typeof getOverviewPlanner>>,
  TError = GetOverviewPlanner400 | GetOverviewPlanner401,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getOverviewPlanner>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOverviewPlannerQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOverviewPlanner>>
  > = ({ signal }) => getOverviewPlanner(signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOverviewPlanner>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOverviewPlannerQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOverviewPlanner>>
>;
export type GetOverviewPlannerQueryError =
  | GetOverviewPlanner400
  | GetOverviewPlanner401;

export function useGetOverviewPlanner<
  TData = Awaited<ReturnType<typeof getOverviewPlanner>>,
  TError = GetOverviewPlanner400 | GetOverviewPlanner401,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewPlanner>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOverviewPlanner>>,
          TError,
          Awaited<ReturnType<typeof getOverviewPlanner>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOverviewPlanner<
  TData = Awaited<ReturnType<typeof getOverviewPlanner>>,
  TError = GetOverviewPlanner400 | GetOverviewPlanner401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewPlanner>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOverviewPlanner>>,
          TError,
          Awaited<ReturnType<typeof getOverviewPlanner>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOverviewPlanner<
  TData = Awaited<ReturnType<typeof getOverviewPlanner>>,
  TError = GetOverviewPlanner400 | GetOverviewPlanner401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewPlanner>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Planejamento financeiro
 */

export function useGetOverviewPlanner<
  TData = Awaited<ReturnType<typeof getOverviewPlanner>>,
  TError = GetOverviewPlanner400 | GetOverviewPlanner401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewPlanner>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOverviewPlannerQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Insights financeiros
 */
export const getOverviewInsights = (signal?: AbortSignal) => {
  return customInstance<GetOverviewInsights200>({
    url: `/overview/insights`,
    method: "GET",
    signal,
  });
};

export const getGetOverviewInsightsQueryKey = () => {
  return [`/overview/insights`] as const;
};

export const getGetOverviewInsightsQueryOptions = <
  TData = Awaited<ReturnType<typeof getOverviewInsights>>,
  TError = GetOverviewInsights400 | GetOverviewInsights401,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getOverviewInsights>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOverviewInsightsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOverviewInsights>>
  > = ({ signal }) => getOverviewInsights(signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOverviewInsights>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOverviewInsightsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOverviewInsights>>
>;
export type GetOverviewInsightsQueryError =
  | GetOverviewInsights400
  | GetOverviewInsights401;

export function useGetOverviewInsights<
  TData = Awaited<ReturnType<typeof getOverviewInsights>>,
  TError = GetOverviewInsights400 | GetOverviewInsights401,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewInsights>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOverviewInsights>>,
          TError,
          Awaited<ReturnType<typeof getOverviewInsights>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOverviewInsights<
  TData = Awaited<ReturnType<typeof getOverviewInsights>>,
  TError = GetOverviewInsights400 | GetOverviewInsights401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewInsights>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOverviewInsights>>,
          TError,
          Awaited<ReturnType<typeof getOverviewInsights>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOverviewInsights<
  TData = Awaited<ReturnType<typeof getOverviewInsights>>,
  TError = GetOverviewInsights400 | GetOverviewInsights401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewInsights>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Insights financeiros
 */

export function useGetOverviewInsights<
  TData = Awaited<ReturnType<typeof getOverviewInsights>>,
  TError = GetOverviewInsights400 | GetOverviewInsights401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewInsights>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOverviewInsightsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Saldo projetado (cash-flow forecast)
 */
export const getOverviewForecast = (
  params?: GetOverviewForecastParams,
  signal?: AbortSignal,
) => {
  return customInstance<GetOverviewForecast200>({
    url: `/overview/forecast`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetOverviewForecastQueryKey = (
  params?: GetOverviewForecastParams,
) => {
  return [`/overview/forecast`, ...(params ? [params] : [])] as const;
};

export const getGetOverviewForecastQueryOptions = <
  TData = Awaited<ReturnType<typeof getOverviewForecast>>,
  TError = GetOverviewForecast400 | GetOverviewForecast401,
>(
  params?: GetOverviewForecastParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewForecast>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetOverviewForecastQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOverviewForecast>>
  > = ({ signal }) => getOverviewForecast(params, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOverviewForecast>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOverviewForecastQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOverviewForecast>>
>;
export type GetOverviewForecastQueryError =
  | GetOverviewForecast400
  | GetOverviewForecast401;

export function useGetOverviewForecast<
  TData = Awaited<ReturnType<typeof getOverviewForecast>>,
  TError = GetOverviewForecast400 | GetOverviewForecast401,
>(
  params: undefined | GetOverviewForecastParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewForecast>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOverviewForecast>>,
          TError,
          Awaited<ReturnType<typeof getOverviewForecast>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOverviewForecast<
  TData = Awaited<ReturnType<typeof getOverviewForecast>>,
  TError = GetOverviewForecast400 | GetOverviewForecast401,
>(
  params?: GetOverviewForecastParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewForecast>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOverviewForecast>>,
          TError,
          Awaited<ReturnType<typeof getOverviewForecast>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOverviewForecast<
  TData = Awaited<ReturnType<typeof getOverviewForecast>>,
  TError = GetOverviewForecast400 | GetOverviewForecast401,
>(
  params?: GetOverviewForecastParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewForecast>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Saldo projetado (cash-flow forecast)
 */

export function useGetOverviewForecast<
  TData = Awaited<ReturnType<typeof getOverviewForecast>>,
  TError = GetOverviewForecast400 | GetOverviewForecast401,
>(
  params?: GetOverviewForecastParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewForecast>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOverviewForecastQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Insights comparativos (período atual vs média)
 */
export const getOverviewInsightsComparison = (
  params?: GetOverviewInsightsComparisonParams,
  signal?: AbortSignal,
) => {
  return customInstance<GetOverviewInsightsComparison200>({
    url: `/overview/insights/comparison`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetOverviewInsightsComparisonQueryKey = (
  params?: GetOverviewInsightsComparisonParams,
) => {
  return [
    `/overview/insights/comparison`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetOverviewInsightsComparisonQueryOptions = <
  TData = Awaited<ReturnType<typeof getOverviewInsightsComparison>>,
  TError = GetOverviewInsightsComparison400 | GetOverviewInsightsComparison401,
>(
  params?: GetOverviewInsightsComparisonParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewInsightsComparison>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetOverviewInsightsComparisonQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOverviewInsightsComparison>>
  > = ({ signal }) => getOverviewInsightsComparison(params, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOverviewInsightsComparison>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOverviewInsightsComparisonQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOverviewInsightsComparison>>
>;
export type GetOverviewInsightsComparisonQueryError =
  | GetOverviewInsightsComparison400
  | GetOverviewInsightsComparison401;

export function useGetOverviewInsightsComparison<
  TData = Awaited<ReturnType<typeof getOverviewInsightsComparison>>,
  TError = GetOverviewInsightsComparison400 | GetOverviewInsightsComparison401,
>(
  params: undefined | GetOverviewInsightsComparisonParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewInsightsComparison>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOverviewInsightsComparison>>,
          TError,
          Awaited<ReturnType<typeof getOverviewInsightsComparison>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOverviewInsightsComparison<
  TData = Awaited<ReturnType<typeof getOverviewInsightsComparison>>,
  TError = GetOverviewInsightsComparison400 | GetOverviewInsightsComparison401,
>(
  params?: GetOverviewInsightsComparisonParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewInsightsComparison>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOverviewInsightsComparison>>,
          TError,
          Awaited<ReturnType<typeof getOverviewInsightsComparison>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOverviewInsightsComparison<
  TData = Awaited<ReturnType<typeof getOverviewInsightsComparison>>,
  TError = GetOverviewInsightsComparison400 | GetOverviewInsightsComparison401,
>(
  params?: GetOverviewInsightsComparisonParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewInsightsComparison>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Insights comparativos (período atual vs média)
 */

export function useGetOverviewInsightsComparison<
  TData = Awaited<ReturnType<typeof getOverviewInsightsComparison>>,
  TError = GetOverviewInsightsComparison400 | GetOverviewInsightsComparison401,
>(
  params?: GetOverviewInsightsComparisonParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOverviewInsightsComparison>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOverviewInsightsComparisonQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
