/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Moneyly API
 * API para gerenciamento financeiro pessoal
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  DeleteRecurringTransactionsId200,
  GetRecurringTransactions200,
  GetRecurringTransactionsIdTransactions200,
  GetRecurringTransactionsParams,
  PatchRecurringTransactionsIdDeactivate200,
  PatchRecurringTransactionsIdReactivate200,
  PostRecurringTransactions201,
  PostRecurringTransactionsBody,
  PutRecurringTransactionsId200,
  PutRecurringTransactionsIdBody,
} from "../moneylyAPI.schemas";

import { customInstance } from "../../../../(utils)/axios-instance";

/**
 * @summary Criar transação recorrente
 */
export const postRecurringTransactions = (
  postRecurringTransactionsBody: PostRecurringTransactionsBody,
  signal?: AbortSignal,
) => {
  return customInstance<PostRecurringTransactions201>({
    url: `/recurring-transactions/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postRecurringTransactionsBody,
    signal,
  });
};

export const getPostRecurringTransactionsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postRecurringTransactions>>,
    TError,
    { data: PostRecurringTransactionsBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postRecurringTransactions>>,
  TError,
  { data: PostRecurringTransactionsBody },
  TContext
> => {
  const mutationKey = ["postRecurringTransactions"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postRecurringTransactions>>,
    { data: PostRecurringTransactionsBody }
  > = (props) => {
    const { data } = props ?? {};

    return postRecurringTransactions(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostRecurringTransactionsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postRecurringTransactions>>
>;
export type PostRecurringTransactionsMutationBody =
  PostRecurringTransactionsBody;
export type PostRecurringTransactionsMutationError = unknown;

/**
 * @summary Criar transação recorrente
 */
export const usePostRecurringTransactions = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postRecurringTransactions>>,
      TError,
      { data: PostRecurringTransactionsBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postRecurringTransactions>>,
  TError,
  { data: PostRecurringTransactionsBody },
  TContext
> => {
  return useMutation(
    getPostRecurringTransactionsMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Listar transações recorrentes
 */
export const getRecurringTransactions = (
  params?: GetRecurringTransactionsParams,
  signal?: AbortSignal,
) => {
  return customInstance<GetRecurringTransactions200>({
    url: `/recurring-transactions/`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetRecurringTransactionsQueryKey = (
  params?: GetRecurringTransactionsParams,
) => {
  return [`/recurring-transactions/`, ...(params ? [params] : [])] as const;
};

export const getGetRecurringTransactionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getRecurringTransactions>>,
  TError = unknown,
>(
  params?: GetRecurringTransactionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecurringTransactions>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetRecurringTransactionsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getRecurringTransactions>>
  > = ({ signal }) => getRecurringTransactions(params, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getRecurringTransactions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRecurringTransactionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRecurringTransactions>>
>;
export type GetRecurringTransactionsQueryError = unknown;

export function useGetRecurringTransactions<
  TData = Awaited<ReturnType<typeof getRecurringTransactions>>,
  TError = unknown,
>(
  params: undefined | GetRecurringTransactionsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecurringTransactions>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecurringTransactions>>,
          TError,
          Awaited<ReturnType<typeof getRecurringTransactions>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecurringTransactions<
  TData = Awaited<ReturnType<typeof getRecurringTransactions>>,
  TError = unknown,
>(
  params?: GetRecurringTransactionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecurringTransactions>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecurringTransactions>>,
          TError,
          Awaited<ReturnType<typeof getRecurringTransactions>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecurringTransactions<
  TData = Awaited<ReturnType<typeof getRecurringTransactions>>,
  TError = unknown,
>(
  params?: GetRecurringTransactionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecurringTransactions>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Listar transações recorrentes
 */

export function useGetRecurringTransactions<
  TData = Awaited<ReturnType<typeof getRecurringTransactions>>,
  TError = unknown,
>(
  params?: GetRecurringTransactionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecurringTransactions>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetRecurringTransactionsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Histórico de transações geradas por uma recorrente
 */
export const getRecurringTransactionsIdTransactions = (
  id: string,
  signal?: AbortSignal,
) => {
  return customInstance<GetRecurringTransactionsIdTransactions200>({
    url: `/recurring-transactions/${id}/transactions`,
    method: "GET",
    signal,
  });
};

export const getGetRecurringTransactionsIdTransactionsQueryKey = (
  id: string,
) => {
  return [`/recurring-transactions/${id}/transactions`] as const;
};

export const getGetRecurringTransactionsIdTransactionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getRecurringTransactionsIdTransactions>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecurringTransactionsIdTransactions>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetRecurringTransactionsIdTransactionsQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getRecurringTransactionsIdTransactions>>
  > = ({ signal }) => getRecurringTransactionsIdTransactions(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getRecurringTransactionsIdTransactions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRecurringTransactionsIdTransactionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRecurringTransactionsIdTransactions>>
>;
export type GetRecurringTransactionsIdTransactionsQueryError = unknown;

export function useGetRecurringTransactionsIdTransactions<
  TData = Awaited<ReturnType<typeof getRecurringTransactionsIdTransactions>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecurringTransactionsIdTransactions>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecurringTransactionsIdTransactions>>,
          TError,
          Awaited<ReturnType<typeof getRecurringTransactionsIdTransactions>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecurringTransactionsIdTransactions<
  TData = Awaited<ReturnType<typeof getRecurringTransactionsIdTransactions>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecurringTransactionsIdTransactions>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecurringTransactionsIdTransactions>>,
          TError,
          Awaited<ReturnType<typeof getRecurringTransactionsIdTransactions>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecurringTransactionsIdTransactions<
  TData = Awaited<ReturnType<typeof getRecurringTransactionsIdTransactions>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecurringTransactionsIdTransactions>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Histórico de transações geradas por uma recorrente
 */

export function useGetRecurringTransactionsIdTransactions<
  TData = Awaited<ReturnType<typeof getRecurringTransactionsIdTransactions>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecurringTransactionsIdTransactions>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetRecurringTransactionsIdTransactionsQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Atualizar transação recorrente
 */
export const putRecurringTransactionsId = (
  id: string,
  putRecurringTransactionsIdBody: PutRecurringTransactionsIdBody,
  signal?: AbortSignal,
) => {
  return customInstance<PutRecurringTransactionsId200>({
    url: `/recurring-transactions/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: putRecurringTransactionsIdBody,
    signal,
  });
};

export const getPutRecurringTransactionsIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putRecurringTransactionsId>>,
    TError,
    { id: string; data: PutRecurringTransactionsIdBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putRecurringTransactionsId>>,
  TError,
  { id: string; data: PutRecurringTransactionsIdBody },
  TContext
> => {
  const mutationKey = ["putRecurringTransactionsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putRecurringTransactionsId>>,
    { id: string; data: PutRecurringTransactionsIdBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return putRecurringTransactionsId(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutRecurringTransactionsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putRecurringTransactionsId>>
>;
export type PutRecurringTransactionsIdMutationBody =
  PutRecurringTransactionsIdBody;
export type PutRecurringTransactionsIdMutationError = void;

/**
 * @summary Atualizar transação recorrente
 */
export const usePutRecurringTransactionsId = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putRecurringTransactionsId>>,
      TError,
      { id: string; data: PutRecurringTransactionsIdBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putRecurringTransactionsId>>,
  TError,
  { id: string; data: PutRecurringTransactionsIdBody },
  TContext
> => {
  return useMutation(
    getPutRecurringTransactionsIdMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Deletar transação recorrente
 */
export const deleteRecurringTransactionsId = (
  id: string,
  signal?: AbortSignal,
) => {
  return customInstance<DeleteRecurringTransactionsId200>({
    url: `/recurring-transactions/${id}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteRecurringTransactionsIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRecurringTransactionsId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteRecurringTransactionsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteRecurringTransactionsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteRecurringTransactionsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteRecurringTransactionsId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteRecurringTransactionsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteRecurringTransactionsId>>
>;

export type DeleteRecurringTransactionsIdMutationError = void;

/**
 * @summary Deletar transação recorrente
 */
export const useDeleteRecurringTransactionsId = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteRecurringTransactionsId>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteRecurringTransactionsId>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getDeleteRecurringTransactionsIdMutationOptions(options),
    queryClient,
  );
};
/**
 * Reativa e recalcula nextExecution para o próximo ciclo futuro. Execuções perdidas durante inatividade não são recuperadas.
 * @summary Reativar transação recorrente
 */
export const patchRecurringTransactionsIdReactivate = (
  id: string,
  signal?: AbortSignal,
) => {
  return customInstance<PatchRecurringTransactionsIdReactivate200>({
    url: `/recurring-transactions/${id}/reactivate`,
    method: "PATCH",
    signal,
  });
};

export const getPatchRecurringTransactionsIdReactivateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchRecurringTransactionsIdReactivate>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchRecurringTransactionsIdReactivate>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["patchRecurringTransactionsIdReactivate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchRecurringTransactionsIdReactivate>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return patchRecurringTransactionsIdReactivate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchRecurringTransactionsIdReactivateMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchRecurringTransactionsIdReactivate>>
>;

export type PatchRecurringTransactionsIdReactivateMutationError = void;

/**
 * @summary Reativar transação recorrente
 */
export const usePatchRecurringTransactionsIdReactivate = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchRecurringTransactionsIdReactivate>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchRecurringTransactionsIdReactivate>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getPatchRecurringTransactionsIdReactivateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Desativar transação recorrente
 */
export const patchRecurringTransactionsIdDeactivate = (
  id: string,
  signal?: AbortSignal,
) => {
  return customInstance<PatchRecurringTransactionsIdDeactivate200>({
    url: `/recurring-transactions/${id}/deactivate`,
    method: "PATCH",
    signal,
  });
};

export const getPatchRecurringTransactionsIdDeactivateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchRecurringTransactionsIdDeactivate>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchRecurringTransactionsIdDeactivate>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["patchRecurringTransactionsIdDeactivate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchRecurringTransactionsIdDeactivate>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return patchRecurringTransactionsIdDeactivate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchRecurringTransactionsIdDeactivateMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchRecurringTransactionsIdDeactivate>>
>;

export type PatchRecurringTransactionsIdDeactivateMutationError = void;

/**
 * @summary Desativar transação recorrente
 */
export const usePatchRecurringTransactionsIdDeactivate = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchRecurringTransactionsIdDeactivate>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchRecurringTransactionsIdDeactivate>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getPatchRecurringTransactionsIdDeactivateMutationOptions(options),
    queryClient,
  );
};
