/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Moneyly API
 * API para gerenciamento financeiro pessoal
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  DeleteGoalsId200,
  GetGoals200,
  GetGoalsId200,
  PostGoals201,
  PostGoalsBody,
  PostGoalsIdAddAmount200,
  PostGoalsIdAddAmountBody,
  PutGoalsId200,
  PutGoalsIdBody,
} from "../moneylyAPI.schemas";

import { customInstance } from "../../../../(utils)/axios-instance";

/**
 * @summary Listar metas
 */
export const getGoals = (signal?: AbortSignal) => {
  return customInstance<GetGoals200>({ url: `/goals/`, method: "GET", signal });
};

export const getGetGoalsQueryKey = () => {
  return [`/goals/`] as const;
};

export const getGetGoalsQueryOptions = <
  TData = Awaited<ReturnType<typeof getGoals>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getGoals>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetGoalsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getGoals>>> = ({
    signal,
  }) => getGoals(signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getGoals>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetGoalsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGoals>>
>;
export type GetGoalsQueryError = unknown;

export function useGetGoals<
  TData = Awaited<ReturnType<typeof getGoals>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGoals>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGoals>>,
          TError,
          Awaited<ReturnType<typeof getGoals>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGoals<
  TData = Awaited<ReturnType<typeof getGoals>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGoals>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGoals>>,
          TError,
          Awaited<ReturnType<typeof getGoals>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGoals<
  TData = Awaited<ReturnType<typeof getGoals>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGoals>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Listar metas
 */

export function useGetGoals<
  TData = Awaited<ReturnType<typeof getGoals>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGoals>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGoalsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Criar meta
 */
export const postGoals = (
  postGoalsBody: PostGoalsBody,
  signal?: AbortSignal,
) => {
  return customInstance<PostGoals201>({
    url: `/goals/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postGoalsBody,
    signal,
  });
};

export const getPostGoalsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postGoals>>,
    TError,
    { data: PostGoalsBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postGoals>>,
  TError,
  { data: PostGoalsBody },
  TContext
> => {
  const mutationKey = ["postGoals"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postGoals>>,
    { data: PostGoalsBody }
  > = (props) => {
    const { data } = props ?? {};

    return postGoals(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostGoalsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postGoals>>
>;
export type PostGoalsMutationBody = PostGoalsBody;
export type PostGoalsMutationError = unknown;

/**
 * @summary Criar meta
 */
export const usePostGoals = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postGoals>>,
      TError,
      { data: PostGoalsBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postGoals>>,
  TError,
  { data: PostGoalsBody },
  TContext
> => {
  return useMutation(getPostGoalsMutationOptions(options), queryClient);
};
/**
 * @summary Obter meta
 */
export const getGoalsId = (id: string, signal?: AbortSignal) => {
  return customInstance<GetGoalsId200>({
    url: `/goals/${id}`,
    method: "GET",
    signal,
  });
};

export const getGetGoalsIdQueryKey = (id: string) => {
  return [`/goals/${id}`] as const;
};

export const getGetGoalsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getGoalsId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGoalsId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetGoalsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getGoalsId>>> = ({
    signal,
  }) => getGoalsId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getGoalsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGoalsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGoalsId>>
>;
export type GetGoalsIdQueryError = unknown;

export function useGetGoalsId<
  TData = Awaited<ReturnType<typeof getGoalsId>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGoalsId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGoalsId>>,
          TError,
          Awaited<ReturnType<typeof getGoalsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGoalsId<
  TData = Awaited<ReturnType<typeof getGoalsId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGoalsId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGoalsId>>,
          TError,
          Awaited<ReturnType<typeof getGoalsId>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGoalsId<
  TData = Awaited<ReturnType<typeof getGoalsId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGoalsId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Obter meta
 */

export function useGetGoalsId<
  TData = Awaited<ReturnType<typeof getGoalsId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGoalsId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGoalsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Atualizar meta
 */
export const putGoalsId = (
  id: string,
  putGoalsIdBody: PutGoalsIdBody,
  signal?: AbortSignal,
) => {
  return customInstance<PutGoalsId200>({
    url: `/goals/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: putGoalsIdBody,
    signal,
  });
};

export const getPutGoalsIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putGoalsId>>,
    TError,
    { id: string; data: PutGoalsIdBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putGoalsId>>,
  TError,
  { id: string; data: PutGoalsIdBody },
  TContext
> => {
  const mutationKey = ["putGoalsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putGoalsId>>,
    { id: string; data: PutGoalsIdBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return putGoalsId(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutGoalsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putGoalsId>>
>;
export type PutGoalsIdMutationBody = PutGoalsIdBody;
export type PutGoalsIdMutationError = unknown;

/**
 * @summary Atualizar meta
 */
export const usePutGoalsId = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putGoalsId>>,
      TError,
      { id: string; data: PutGoalsIdBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putGoalsId>>,
  TError,
  { id: string; data: PutGoalsIdBody },
  TContext
> => {
  return useMutation(getPutGoalsIdMutationOptions(options), queryClient);
};
/**
 * @summary Deletar meta
 */
export const deleteGoalsId = (id: string, signal?: AbortSignal) => {
  return customInstance<DeleteGoalsId200>({
    url: `/goals/${id}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteGoalsIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteGoalsId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteGoalsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteGoalsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteGoalsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteGoalsId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteGoalsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteGoalsId>>
>;

export type DeleteGoalsIdMutationError = unknown;

/**
 * @summary Deletar meta
 */
export const useDeleteGoalsId = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteGoalsId>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteGoalsId>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteGoalsIdMutationOptions(options), queryClient);
};
/**
 * @summary Adicionar valor à meta
 */
export const postGoalsIdAddAmount = (
  id: string,
  postGoalsIdAddAmountBody: PostGoalsIdAddAmountBody,
  signal?: AbortSignal,
) => {
  return customInstance<PostGoalsIdAddAmount200>({
    url: `/goals/${id}/add-amount`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postGoalsIdAddAmountBody,
    signal,
  });
};

export const getPostGoalsIdAddAmountMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postGoalsIdAddAmount>>,
    TError,
    { id: string; data: PostGoalsIdAddAmountBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postGoalsIdAddAmount>>,
  TError,
  { id: string; data: PostGoalsIdAddAmountBody },
  TContext
> => {
  const mutationKey = ["postGoalsIdAddAmount"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postGoalsIdAddAmount>>,
    { id: string; data: PostGoalsIdAddAmountBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return postGoalsIdAddAmount(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostGoalsIdAddAmountMutationResult = NonNullable<
  Awaited<ReturnType<typeof postGoalsIdAddAmount>>
>;
export type PostGoalsIdAddAmountMutationBody = PostGoalsIdAddAmountBody;
export type PostGoalsIdAddAmountMutationError = unknown;

/**
 * @summary Adicionar valor à meta
 */
export const usePostGoalsIdAddAmount = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postGoalsIdAddAmount>>,
      TError,
      { id: string; data: PostGoalsIdAddAmountBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postGoalsIdAddAmount>>,
  TError,
  { id: string; data: PostGoalsIdAddAmountBody },
  TContext
> => {
  return useMutation(
    getPostGoalsIdAddAmountMutationOptions(options),
    queryClient,
  );
};
