/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Moneyly API
 * API para gerenciamento financeiro pessoal
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  DeleteBudgetsId200,
  GetBudgets200,
  PostBudgets201,
  PostBudgetsBody,
  PutBudgetsId200,
  PutBudgetsIdBody,
} from "../moneylyAPI.schemas";

import { customInstance } from "../../../../(utils)/axios-instance";

/**
 * @summary Listar orçamentos
 */
export const getBudgets = (signal?: AbortSignal) => {
  return customInstance<GetBudgets200>({
    url: `/budgets/`,
    method: "GET",
    signal,
  });
};

export const getGetBudgetsQueryKey = () => {
  return [`/budgets/`] as const;
};

export const getGetBudgetsQueryOptions = <
  TData = Awaited<ReturnType<typeof getBudgets>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getBudgets>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBudgetsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBudgets>>> = ({
    signal,
  }) => getBudgets(signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getBudgets>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBudgetsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBudgets>>
>;
export type GetBudgetsQueryError = unknown;

export function useGetBudgets<
  TData = Awaited<ReturnType<typeof getBudgets>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBudgets>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBudgets>>,
          TError,
          Awaited<ReturnType<typeof getBudgets>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBudgets<
  TData = Awaited<ReturnType<typeof getBudgets>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBudgets>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBudgets>>,
          TError,
          Awaited<ReturnType<typeof getBudgets>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBudgets<
  TData = Awaited<ReturnType<typeof getBudgets>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBudgets>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Listar orçamentos
 */

export function useGetBudgets<
  TData = Awaited<ReturnType<typeof getBudgets>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getBudgets>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBudgetsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Criar orçamento
 */
export const postBudgets = (
  postBudgetsBody: PostBudgetsBody,
  signal?: AbortSignal,
) => {
  return customInstance<PostBudgets201>({
    url: `/budgets/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postBudgetsBody,
    signal,
  });
};

export const getPostBudgetsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postBudgets>>,
    TError,
    { data: PostBudgetsBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postBudgets>>,
  TError,
  { data: PostBudgetsBody },
  TContext
> => {
  const mutationKey = ["postBudgets"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postBudgets>>,
    { data: PostBudgetsBody }
  > = (props) => {
    const { data } = props ?? {};

    return postBudgets(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostBudgetsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postBudgets>>
>;
export type PostBudgetsMutationBody = PostBudgetsBody;
export type PostBudgetsMutationError = unknown;

/**
 * @summary Criar orçamento
 */
export const usePostBudgets = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postBudgets>>,
      TError,
      { data: PostBudgetsBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postBudgets>>,
  TError,
  { data: PostBudgetsBody },
  TContext
> => {
  return useMutation(getPostBudgetsMutationOptions(options), queryClient);
};
/**
 * @summary Atualizar orçamento
 */
export const putBudgetsId = (
  id: string,
  putBudgetsIdBody: PutBudgetsIdBody,
  signal?: AbortSignal,
) => {
  return customInstance<PutBudgetsId200>({
    url: `/budgets/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: putBudgetsIdBody,
    signal,
  });
};

export const getPutBudgetsIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putBudgetsId>>,
    TError,
    { id: string; data: PutBudgetsIdBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putBudgetsId>>,
  TError,
  { id: string; data: PutBudgetsIdBody },
  TContext
> => {
  const mutationKey = ["putBudgetsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putBudgetsId>>,
    { id: string; data: PutBudgetsIdBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return putBudgetsId(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutBudgetsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putBudgetsId>>
>;
export type PutBudgetsIdMutationBody = PutBudgetsIdBody;
export type PutBudgetsIdMutationError = unknown;

/**
 * @summary Atualizar orçamento
 */
export const usePutBudgetsId = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putBudgetsId>>,
      TError,
      { id: string; data: PutBudgetsIdBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putBudgetsId>>,
  TError,
  { id: string; data: PutBudgetsIdBody },
  TContext
> => {
  return useMutation(getPutBudgetsIdMutationOptions(options), queryClient);
};
/**
 * @summary Deletar orçamento
 */
export const deleteBudgetsId = (id: string, signal?: AbortSignal) => {
  return customInstance<DeleteBudgetsId200>({
    url: `/budgets/${id}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteBudgetsIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteBudgetsId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteBudgetsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteBudgetsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteBudgetsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteBudgetsId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteBudgetsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteBudgetsId>>
>;

export type DeleteBudgetsIdMutationError = unknown;

/**
 * @summary Deletar orçamento
 */
export const useDeleteBudgetsId = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteBudgetsId>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteBudgetsId>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteBudgetsIdMutationOptions(options), queryClient);
};
