/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Moneyly API
 * ARQUIVO GERADO por `pnpm openapi:gen` (zod-to-openapi). NÃO editar à mão. Ver moneyly/.specs/01-api-contract.md
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  DeleteOvertimeId200,
  DeleteOvertimeId400,
  DeleteOvertimeId401,
  DeleteOvertimeId404,
  GetOvertime200,
  GetOvertime400,
  GetOvertime401,
  GetOvertimeParams,
  GetOvertimeSummary200,
  GetOvertimeSummary400,
  GetOvertimeSummary401,
  GetOvertimeSummaryParams,
  PostOvertime200,
  PostOvertime400,
  PostOvertime401,
  PostOvertimeBody,
  PutOvertimeId200,
  PutOvertimeId400,
  PutOvertimeId401,
  PutOvertimeId404,
  PutOvertimeIdBody,
} from '../moneylyAPI.schemas';

import { customInstance } from '../../../../(utils)/axios-instance';

/**
 * @summary Criar registro de hora extra
 */
export const postOvertime = (postOvertimeBody: PostOvertimeBody, signal?: AbortSignal) => {
  return customInstance<PostOvertime200>({
    url: `/overtime/`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: postOvertimeBody,
    signal,
  });
};

export const getPostOvertimeMutationOptions = <
  TError = PostOvertime400 | PostOvertime401,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postOvertime>>,
    TError,
    { data: PostOvertimeBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postOvertime>>,
  TError,
  { data: PostOvertimeBody },
  TContext
> => {
  const mutationKey = ['postOvertime'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postOvertime>>,
    { data: PostOvertimeBody }
  > = (props) => {
    const { data } = props ?? {};

    return postOvertime(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostOvertimeMutationResult = NonNullable<Awaited<ReturnType<typeof postOvertime>>>;
export type PostOvertimeMutationBody = PostOvertimeBody;
export type PostOvertimeMutationError = PostOvertime400 | PostOvertime401;

/**
 * @summary Criar registro de hora extra
 */
export const usePostOvertime = <TError = PostOvertime400 | PostOvertime401, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postOvertime>>,
      TError,
      { data: PostOvertimeBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postOvertime>>,
  TError,
  { data: PostOvertimeBody },
  TContext
> => {
  return useMutation(getPostOvertimeMutationOptions(options), queryClient);
};
/**
 * @summary Listar registros de hora extra (filtros: month, year, companyId)
 */
export const getOvertime = (params?: GetOvertimeParams, signal?: AbortSignal) => {
  return customInstance<GetOvertime200>({ url: `/overtime/`, method: 'GET', params, signal });
};

export const getGetOvertimeQueryKey = (params?: GetOvertimeParams) => {
  return [`/overtime/`, ...(params ? [params] : [])] as const;
};

export const getGetOvertimeQueryOptions = <
  TData = Awaited<ReturnType<typeof getOvertime>>,
  TError = GetOvertime400 | GetOvertime401,
>(
  params?: GetOvertimeParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOvertime>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOvertimeQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOvertime>>> = ({ signal }) =>
    getOvertime(params, signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getOvertime>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOvertimeQueryResult = NonNullable<Awaited<ReturnType<typeof getOvertime>>>;
export type GetOvertimeQueryError = GetOvertime400 | GetOvertime401;

export function useGetOvertime<
  TData = Awaited<ReturnType<typeof getOvertime>>,
  TError = GetOvertime400 | GetOvertime401,
>(
  params: undefined | GetOvertimeParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOvertime>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOvertime>>,
          TError,
          Awaited<ReturnType<typeof getOvertime>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOvertime<
  TData = Awaited<ReturnType<typeof getOvertime>>,
  TError = GetOvertime400 | GetOvertime401,
>(
  params?: GetOvertimeParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOvertime>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOvertime>>,
          TError,
          Awaited<ReturnType<typeof getOvertime>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOvertime<
  TData = Awaited<ReturnType<typeof getOvertime>>,
  TError = GetOvertime400 | GetOvertime401,
>(
  params?: GetOvertimeParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOvertime>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Listar registros de hora extra (filtros: month, year, companyId)
 */

export function useGetOvertime<
  TData = Awaited<ReturnType<typeof getOvertime>>,
  TError = GetOvertime400 | GetOvertime401,
>(
  params?: GetOvertimeParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOvertime>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetOvertimeQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Resumo de horas extras por mês civil
 */
export const getOvertimeSummary = (params: GetOvertimeSummaryParams, signal?: AbortSignal) => {
  return customInstance<GetOvertimeSummary200>({
    url: `/overtime/summary`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetOvertimeSummaryQueryKey = (params?: GetOvertimeSummaryParams) => {
  return [`/overtime/summary`, ...(params ? [params] : [])] as const;
};

export const getGetOvertimeSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getOvertimeSummary>>,
  TError = GetOvertimeSummary400 | GetOvertimeSummary401,
>(
  params: GetOvertimeSummaryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOvertimeSummary>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOvertimeSummaryQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOvertimeSummary>>> = ({ signal }) =>
    getOvertimeSummary(params, signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getOvertimeSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOvertimeSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOvertimeSummary>>
>;
export type GetOvertimeSummaryQueryError = GetOvertimeSummary400 | GetOvertimeSummary401;

export function useGetOvertimeSummary<
  TData = Awaited<ReturnType<typeof getOvertimeSummary>>,
  TError = GetOvertimeSummary400 | GetOvertimeSummary401,
>(
  params: GetOvertimeSummaryParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOvertimeSummary>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOvertimeSummary>>,
          TError,
          Awaited<ReturnType<typeof getOvertimeSummary>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOvertimeSummary<
  TData = Awaited<ReturnType<typeof getOvertimeSummary>>,
  TError = GetOvertimeSummary400 | GetOvertimeSummary401,
>(
  params: GetOvertimeSummaryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getOvertimeSummary>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOvertimeSummary>>,
          TError,
          Awaited<ReturnType<typeof getOvertimeSummary>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOvertimeSummary<
  TData = Awaited<ReturnType<typeof getOvertimeSummary>>,
  TError = GetOvertimeSummary400 | GetOvertimeSummary401,
>(
  params: GetOvertimeSummaryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOvertimeSummary>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Resumo de horas extras por mês civil
 */

export function useGetOvertimeSummary<
  TData = Awaited<ReturnType<typeof getOvertimeSummary>>,
  TError = GetOvertimeSummary400 | GetOvertimeSummary401,
>(
  params: GetOvertimeSummaryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOvertimeSummary>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetOvertimeSummaryQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Editar registro de hora extra
 */
export const putOvertimeId = (
  id: string,
  putOvertimeIdBody: PutOvertimeIdBody,
  signal?: AbortSignal
) => {
  return customInstance<PutOvertimeId200>({
    url: `/overtime/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: putOvertimeIdBody,
    signal,
  });
};

export const getPutOvertimeIdMutationOptions = <
  TError = PutOvertimeId400 | PutOvertimeId401 | PutOvertimeId404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putOvertimeId>>,
    TError,
    { id: string; data: PutOvertimeIdBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putOvertimeId>>,
  TError,
  { id: string; data: PutOvertimeIdBody },
  TContext
> => {
  const mutationKey = ['putOvertimeId'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putOvertimeId>>,
    { id: string; data: PutOvertimeIdBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return putOvertimeId(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutOvertimeIdMutationResult = NonNullable<Awaited<ReturnType<typeof putOvertimeId>>>;
export type PutOvertimeIdMutationBody = PutOvertimeIdBody;
export type PutOvertimeIdMutationError = PutOvertimeId400 | PutOvertimeId401 | PutOvertimeId404;

/**
 * @summary Editar registro de hora extra
 */
export const usePutOvertimeId = <
  TError = PutOvertimeId400 | PutOvertimeId401 | PutOvertimeId404,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putOvertimeId>>,
      TError,
      { id: string; data: PutOvertimeIdBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof putOvertimeId>>,
  TError,
  { id: string; data: PutOvertimeIdBody },
  TContext
> => {
  return useMutation(getPutOvertimeIdMutationOptions(options), queryClient);
};
/**
 * @summary Deletar registro e transaction vinculada
 */
export const deleteOvertimeId = (id: string, signal?: AbortSignal) => {
  return customInstance<DeleteOvertimeId200>({ url: `/overtime/${id}`, method: 'DELETE', signal });
};

export const getDeleteOvertimeIdMutationOptions = <
  TError = DeleteOvertimeId400 | DeleteOvertimeId401 | DeleteOvertimeId404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteOvertimeId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteOvertimeId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['deleteOvertimeId'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteOvertimeId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteOvertimeId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteOvertimeIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteOvertimeId>>
>;

export type DeleteOvertimeIdMutationError =
  | DeleteOvertimeId400
  | DeleteOvertimeId401
  | DeleteOvertimeId404;

/**
 * @summary Deletar registro e transaction vinculada
 */
export const useDeleteOvertimeId = <
  TError = DeleteOvertimeId400 | DeleteOvertimeId401 | DeleteOvertimeId404,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteOvertimeId>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteOvertimeId>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteOvertimeIdMutationOptions(options), queryClient);
};
