import type { Metadata } from "next";
import "./globals.css";
import { Contexts } from "./(contexts)";

export const metadata: Metadata = {
  title: "Moneyly - Financeiro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body
        className="antialiased"
      >
        <Contexts>
          {children}
        </Contexts>
      </body>
    </html>
  );
}
