import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Contexts } from "./(contexts)";
import "./globals.css";

export const metadata: Metadata = {
  title: "Moneyly - Financeiro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <Contexts>
          {children}
          <Toaster richColors position="bottom-center" />
        </Contexts>
      </body>
    </html>
  );
}
