/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Moneyly API
 * API para gerenciamento financeiro pessoal
 * OpenAPI spec version: 1.0.0
 */
export interface User {
  id: string;
  name: string;
  email: string;
  /** @nullable */
  googleId?: string | null;
  /** @nullable */
  avatar?: string | null;
  /** @nullable */
  monthlyIncome?: string | null;
  /**
   * @minimum 1
   * @maximum 31
   * @nullable
   */
  financialDayStart?: number | null;
  /**
   * @minimum 1
   * @maximum 31
   * @nullable
   */
  financialDayEnd?: number | null;
  /** @nullable */
  firstAccess?: boolean | null;
  createdAt: string;
  updatedAt: string;
}

export type TransactionType =
  (typeof TransactionType)[keyof typeof TransactionType];

export const TransactionType = {
  income: "income",
  expense: "expense",
} as const;

export type TransactionCategory = {
  id: string;
  name: string;
};

export interface Transaction {
  id: string;
  userId: string;
  type: TransactionType;
  title: string;
  amount: string;
  /** @nullable */
  description?: string | null;
  date: string;
  categoryId: string;
  /** @nullable */
  periodId?: string | null;
  createdAt: string;
  updatedAt: string;
  category?: TransactionCategory;
}

export type BudgetStatus = (typeof BudgetStatus)[keyof typeof BudgetStatus];

export const BudgetStatus = {
  safe: "safe",
  warning: "warning",
  danger: "danger",
  exceeded: "exceeded",
  attention: "attention",
} as const;

export type BudgetCategory = {
  id: string;
  name: string;
};

export interface Budget {
  id: string;
  userId: string;
  categoryId: string;
  monthlyLimit: string;
  createdAt: string;
  updatedAt: string;
  spent?: number;
  remaining?: number;
  percentage?: number;
  status?: BudgetStatus;
  category?: BudgetCategory;
}

export type GoalProgress = {
  percentage: number;
  daysRemaining: number;
  remaining: number;
};

export type GoalMilestonesItem = {
  id: string;
  goalId: string;
  percentage: number;
  amount: string;
  isReached: boolean;
  /** @nullable */
  reachedAt?: string | null;
  createdAt: string;
};

export interface Goal {
  id: string;
  userId: string;
  title: string;
  /** @nullable */
  description?: string | null;
  targetAmount: string;
  currentAmount: string;
  targetDate: string;
  startDate: string;
  /** @nullable */
  isActive?: boolean | null;
  createdAt: string;
  updatedAt: string;
  progress?: GoalProgress;
  milestones?: GoalMilestonesItem[];
}

export interface Category {
  id: string;
  /** @nullable */
  userId?: string | null;
  name: string;
  isGlobal: boolean;
  createdAt: string;
  updatedAt: string;
}

export type SuccessResponseData = { [key: string]: unknown };

export interface SuccessResponse {
  success: boolean;
  data?: SuccessResponseData;
  message?: string;
}

export type AuthResponseData = {
  user: User;
  accessToken: string;
  refreshToken: string;
};

export interface AuthResponse {
  success: boolean;
  data?: AuthResponseData;
  message?: string;
}

export interface Pagination {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
  hasNext: boolean;
  hasPrev: boolean;
}

export type PaginatedResponseDataItem = { [key: string]: unknown };

export interface PaginatedResponse {
  success: boolean;
  data: PaginatedResponseDataItem[];
  pagination: Pagination;
  message?: string;
}

export interface FinancialPeriod {
  id: string;
  startDate: string;
  endDate: string;
  label?: string;
  transactionCount?: number;
}

export interface SelectedPeriod {
  id: string;
  startDate: string;
  endDate: string;
  label: string;
  transactionCount: number;
  description: string;
}

export interface DashboardStats {
  totalIncome: number;
  totalExpense: number;
  balance: number;
  /** @nullable */
  percentUsed?: number | null;
  remainingBudget: number;
}

export type MonthlyHistoryItemType =
  (typeof MonthlyHistoryItemType)[keyof typeof MonthlyHistoryItemType];

export const MonthlyHistoryItemType = {
  income: "income",
  expense: "expense",
} as const;

export interface MonthlyHistoryItem {
  id: string;
  type: MonthlyHistoryItemType;
  amount: number;
  date: string;
  category: string;
  description?: string;
}

export interface ExpensesByCategoryItem {
  id: string;
  name: string;
  amount: number;
  percentage: number;
}

export interface PlannerStats {
  totalBudgeted: number;
  totalSavingsGoal: number;
  totalSaved: number;
  savingsProgress: number;
  budgetPercentage: number;
  savingsPercentage: number;
  remainingToSave: number;
  availableForBudget: number;
}

export type PlannerAlertType =
  (typeof PlannerAlertType)[keyof typeof PlannerAlertType];

export const PlannerAlertType = {
  danger: "danger",
  warning: "warning",
  info: "info",
} as const;

export type PlannerAlertPriority =
  (typeof PlannerAlertPriority)[keyof typeof PlannerAlertPriority];

export const PlannerAlertPriority = {
  high: "high",
  medium: "medium",
  low: "low",
} as const;

export interface PlannerAlert {
  type: PlannerAlertType;
  message: string;
  priority: PlannerAlertPriority;
  category?: string;
  goal?: string;
  daysRemaining?: number;
  percentage?: number;
}

export type PostAuthSignUpBody = {
  name: string;
  email: string;
  /** @minLength 6 */
  password: string;
};

export type PostAuthSignInBody = {
  email: string;
  password: string;
};

export type PostAuthGoogleBody = {
  idToken: string;
};

export type PostAuthRefreshBody = {
  refreshToken: string;
};

export type PostAuthRefresh200Data = {
  user: User;
  accessToken: string;
};

export type PostAuthRefresh200 = {
  success: boolean;
  data?: PostAuthRefresh200Data;
  message?: string;
};

export type PostAuthLogoutBody = {
  refreshToken: string;
};

export type PostAuthLogout200Data = {
  success?: boolean;
};

export type PostAuthLogout200 = {
  success: boolean;
  data?: PostAuthLogout200Data;
  message?: string;
};

export type PostTransactionsCreateBodyType =
  (typeof PostTransactionsCreateBodyType)[keyof typeof PostTransactionsCreateBodyType];

export const PostTransactionsCreateBodyType = {
  income: "income",
  expense: "expense",
} as const;

export type PostTransactionsCreateBody = {
  type: PostTransactionsCreateBodyType;
  title: string;
  amount: number;
  category: string;
  description?: string;
  date?: string;
};

export type PostTransactionsCreate201 = {
  success: boolean;
  data: Transaction;
  message?: string;
};

export type GetTransactionsParams = {
  page?: number;
  limit?: number;
};

export type GetTransactions200 = {
  success: boolean;
  data: Transaction[];
  pagination: Pagination;
  message?: string;
};

export type PutTransactionsIdBodyType =
  (typeof PutTransactionsIdBodyType)[keyof typeof PutTransactionsIdBodyType];

export const PutTransactionsIdBodyType = {
  income: "income",
  expense: "expense",
} as const;

export type PutTransactionsIdBody = {
  type?: PutTransactionsIdBodyType;
  title?: string;
  amount?: number;
  category?: string;
  description?: string;
  date?: string;
};

export type PutTransactionsId200 = {
  success: boolean;
  data: Transaction;
  message?: string;
};

export type DeleteTransactionsId200 = {
  success: boolean;
  message?: string;
};

export type GetTransactionsSummary200Data = {
  totalIncome: number;
  totalExpense: number;
  balance: number;
  monthlyIncome?: number;
};

export type GetTransactionsSummary200 = {
  success: boolean;
  data: GetTransactionsSummary200Data;
  message?: string;
};

export type GetTransactionsSummaryByMonth200Data = {
  totalIncome: number;
  totalExpense: number;
  balance: number;
  monthlyIncome?: number;
};

export type GetTransactionsSummaryByMonth200 = {
  success: boolean;
  data: GetTransactionsSummaryByMonth200Data;
  message?: string;
};

export type GetTransactionsSummaryCurrentPeriod200Data = {
  totalIncome: number;
  totalExpense: number;
  balance: number;
  monthlyIncome?: number;
  percentUsed?: number;
  alert?: string;
};

export type GetTransactionsSummaryCurrentPeriod200 = {
  success: boolean;
  data: GetTransactionsSummaryCurrentPeriod200Data;
  message?: string;
};

export type GetBudgets200 = {
  success: boolean;
  data: Budget[];
  message?: string;
};

export type PostBudgetsBody = {
  categoryId: string;
  monthlyLimit: number;
};

export type PostBudgets201 = {
  success: boolean;
  data: Budget;
  message?: string;
};

export type PutBudgetsIdBody = {
  monthlyLimit: number;
};

export type PutBudgetsId200 = {
  success: boolean;
  data: Budget;
  message?: string;
};

export type DeleteBudgetsId200 = {
  success: boolean;
  message?: string;
};

export type GetGoals200 = {
  success: boolean;
  data: Goal[];
  message?: string;
};

export type PostGoalsBody = {
  title: string;
  description?: string;
  targetAmount: number;
  targetDate: string;
};

export type PostGoals201 = {
  success: boolean;
  data: Goal;
  message?: string;
};

export type GetGoalsId200 = {
  success: boolean;
  data: Goal;
  message?: string;
};

export type PutGoalsIdBody = {
  title?: string;
  description?: string;
  targetAmount?: number;
  targetDate?: string;
  currentAmount?: number;
  isActive?: boolean;
};

export type PutGoalsId200 = {
  success: boolean;
  data: Goal;
  message?: string;
};

export type DeleteGoalsId200 = {
  success: boolean;
  message?: string;
};

export type PostGoalsIdAddAmountBody = {
  amount: number;
};

export type PostGoalsIdAddAmount200 = {
  success: boolean;
  data: Goal;
  message?: string;
};

export type GetCategoriesParams = {
  page?: number;
  limit?: number;
};

export type GetCategories200 = {
  success: boolean;
  data: Category[];
  pagination: Pagination;
  message?: string;
};

export type PostCategoriesCreateBody = {
  name: string;
};

export type PostCategoriesCreate201 = {
  success: boolean;
  data: Category;
  message?: string;
};

export type PutCategoriesUpdateIdBody = {
  name: string;
};

export type PutCategoriesUpdateId200 = {
  success: boolean;
  data: Category;
  message?: string;
};

export type DeleteCategoriesDeleteId200 = {
  success: boolean;
  message?: string;
};

export type GetUserMe200 = {
  success: boolean;
  data: User;
  message?: string;
};

export type PutUserIncomeBody = {
  /**
   * @minimum 0.01
   * @maximum 999999999.99
   */
  monthlyIncome: number;
};

export type PutUserIncome200Data = {
  monthlyIncome: number;
  firstAccess: boolean;
};

export type PutUserIncome200 = {
  success: boolean;
  data: PutUserIncome200Data;
  message?: string;
};

export type PutUserFinancialPeriodBody = {
  /**
   * @minimum 1
   * @maximum 31
   */
  financialDayStart: number;
  /**
   * @minimum 1
   * @maximum 31
   */
  financialDayEnd: number;
};

export type PutUserFinancialPeriod200Data = {
  financialDayStart: number;
  financialDayEnd: number;
  firstAccess: boolean;
};

export type PutUserFinancialPeriod200 = {
  success: boolean;
  data: PutUserFinancialPeriod200Data;
  message?: string;
};

export type PutUserIncomeAndPeriodBody = {
  /**
   * @minimum 0.01
   * @maximum 999999999.99
   */
  monthlyIncome: number;
  /**
   * @minimum 1
   * @maximum 31
   */
  financialDayStart: number;
  /**
   * @minimum 1
   * @maximum 31
   */
  financialDayEnd: number;
};

export type PutUserIncomeAndPeriod200Data = {
  monthlyIncome: number;
  financialDayStart: number;
  financialDayEnd: number;
  firstAccess: boolean;
};

export type PutUserIncomeAndPeriod200 = {
  success: boolean;
  data: PutUserIncomeAndPeriod200Data;
  message?: string;
};

export type GetUserFinancialPeriods200 = {
  success: boolean;
  data: FinancialPeriod[];
  message?: string;
};

export type GetUserFinancialPeriodsPeriodId200Data = {
  id: string;
  startDate: string;
  endDate: string;
  isActive?: boolean;
};

export type GetUserFinancialPeriodsPeriodId200 = {
  success: boolean;
  data: GetUserFinancialPeriodsPeriodId200Data;
  message?: string;
};

export type GetOverviewPeriods200 = {
  success: boolean;
  data: FinancialPeriod[];
  message?: string;
};

export type GetOverviewDashboardParams = {
  periodId?: string;
  startDate?: string;
  endDate?: string;
};

export type GetOverviewDashboard200Data = {
  stats: DashboardStats;
  selectedPeriod?: SelectedPeriod | null;
  availablePeriods: FinancialPeriod[];
  monthlyHistory: MonthlyHistoryItem[];
  expensesByCategory: ExpensesByCategoryItem[];
  transactionsCount: number;
};

export type GetOverviewDashboard200 = {
  success: boolean;
  data: GetOverviewDashboard200Data;
  message?: string;
};

export type GetOverviewPlanner200DataCurrentPeriod = {
  startDate: string;
  endDate: string;
  description: string;
};

export type GetOverviewPlanner200Data = {
  stats: PlannerStats;
  currentPeriod: GetOverviewPlanner200DataCurrentPeriod;
  alerts: PlannerAlert[];
};

export type GetOverviewPlanner200 = {
  success: boolean;
  data: GetOverviewPlanner200Data;
  message?: string;
};
