/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Moneyly API
 * ARQUIVO GERADO por `pnpm openapi:gen` (zod-to-openapi). NÃO editar à mão. Ver moneyly/.specs/01-api-contract.md
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetNotifications200,
  GetNotifications400,
  GetNotifications401,
  GetNotificationsParams,
  PatchNotificationsIdRead200,
  PatchNotificationsIdRead400,
  PatchNotificationsIdRead401,
  PatchNotificationsIdRead404,
  PatchNotificationsReadAll200,
  PatchNotificationsReadAll400,
  PatchNotificationsReadAll401,
} from '../moneylyAPI.schemas';

import { customInstance } from '../../../../(utils)/axios-instance';

/**
 * @summary Listar notificações (paginado)
 */
export const getNotifications = (params?: GetNotificationsParams, signal?: AbortSignal) => {
  return customInstance<GetNotifications200>({
    url: `/notifications/`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetNotificationsQueryKey = (params?: GetNotificationsParams) => {
  return [`/notifications/`, ...(params ? [params] : [])] as const;
};

export const getGetNotificationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = GetNotifications400 | GetNotifications401,
>(
  params?: GetNotificationsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetNotificationsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotifications>>> = ({ signal }) =>
    getNotifications(params, signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getNotifications>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNotificationsQueryResult = NonNullable<Awaited<ReturnType<typeof getNotifications>>>;
export type GetNotificationsQueryError = GetNotifications400 | GetNotifications401;

export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = GetNotifications400 | GetNotifications401,
>(
  params: undefined | GetNotificationsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotifications>>,
          TError,
          Awaited<ReturnType<typeof getNotifications>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = GetNotifications400 | GetNotifications401,
>(
  params?: GetNotificationsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotifications>>,
          TError,
          Awaited<ReturnType<typeof getNotifications>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = GetNotifications400 | GetNotifications401,
>(
  params?: GetNotificationsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Listar notificações (paginado)
 */

export function useGetNotifications<
  TData = Awaited<ReturnType<typeof getNotifications>>,
  TError = GetNotifications400 | GetNotifications401,
>(
  params?: GetNotificationsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetNotificationsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Marcar todas como lidas
 */
export const patchNotificationsReadAll = (signal?: AbortSignal) => {
  return customInstance<PatchNotificationsReadAll200>({
    url: `/notifications/read-all`,
    method: 'PATCH',
    signal,
  });
};

export const getPatchNotificationsReadAllMutationOptions = <
  TError = PatchNotificationsReadAll400 | PatchNotificationsReadAll401,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchNotificationsReadAll>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchNotificationsReadAll>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['patchNotificationsReadAll'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchNotificationsReadAll>>,
    void
  > = () => {
    return patchNotificationsReadAll();
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchNotificationsReadAllMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchNotificationsReadAll>>
>;

export type PatchNotificationsReadAllMutationError =
  | PatchNotificationsReadAll400
  | PatchNotificationsReadAll401;

/**
 * @summary Marcar todas como lidas
 */
export const usePatchNotificationsReadAll = <
  TError = PatchNotificationsReadAll400 | PatchNotificationsReadAll401,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchNotificationsReadAll>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof patchNotificationsReadAll>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getPatchNotificationsReadAllMutationOptions(options), queryClient);
};
/**
 * @summary Marcar notificação como lida
 */
export const patchNotificationsIdRead = (id: string, signal?: AbortSignal) => {
  return customInstance<PatchNotificationsIdRead200>({
    url: `/notifications/${id}/read`,
    method: 'PATCH',
    signal,
  });
};

export const getPatchNotificationsIdReadMutationOptions = <
  TError = PatchNotificationsIdRead400 | PatchNotificationsIdRead401 | PatchNotificationsIdRead404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchNotificationsIdRead>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchNotificationsIdRead>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['patchNotificationsIdRead'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchNotificationsIdRead>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return patchNotificationsIdRead(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchNotificationsIdReadMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchNotificationsIdRead>>
>;

export type PatchNotificationsIdReadMutationError =
  | PatchNotificationsIdRead400
  | PatchNotificationsIdRead401
  | PatchNotificationsIdRead404;

/**
 * @summary Marcar notificação como lida
 */
export const usePatchNotificationsIdRead = <
  TError = PatchNotificationsIdRead400 | PatchNotificationsIdRead401 | PatchNotificationsIdRead404,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchNotificationsIdRead>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof patchNotificationsIdRead>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getPatchNotificationsIdReadMutationOptions(options), queryClient);
};
