/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Moneyly API
 * API para gerenciamento financeiro pessoal
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  DeleteCategoriesDeleteId200,
  GetCategories200,
  GetCategoriesParams,
  PostCategoriesCreate201,
  PostCategoriesCreateBody,
  PutCategoriesUpdateId200,
  PutCategoriesUpdateIdBody,
} from "../moneylyAPI.schemas";

import { customInstance } from "../../../../(utils)/axios-instance";

/**
 * @summary Listar categorias
 */
export const getCategories = (
  params?: GetCategoriesParams,
  signal?: AbortSignal,
) => {
  return customInstance<GetCategories200>({
    url: `/categories/`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetCategoriesQueryKey = (params?: GetCategoriesParams) => {
  return [`/categories/`, ...(params ? [params] : [])] as const;
};

export const getGetCategoriesQueryOptions = <
  TData = Awaited<ReturnType<typeof getCategories>>,
  TError = unknown,
>(
  params?: GetCategoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCategoriesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCategories>>> = ({
    signal,
  }) => getCategories(params, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCategories>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCategoriesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCategories>>
>;
export type GetCategoriesQueryError = unknown;

export function useGetCategories<
  TData = Awaited<ReturnType<typeof getCategories>>,
  TError = unknown,
>(
  params: undefined | GetCategoriesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategories>>,
          TError,
          Awaited<ReturnType<typeof getCategories>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCategories<
  TData = Awaited<ReturnType<typeof getCategories>>,
  TError = unknown,
>(
  params?: GetCategoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCategories>>,
          TError,
          Awaited<ReturnType<typeof getCategories>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCategories<
  TData = Awaited<ReturnType<typeof getCategories>>,
  TError = unknown,
>(
  params?: GetCategoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Listar categorias
 */

export function useGetCategories<
  TData = Awaited<ReturnType<typeof getCategories>>,
  TError = unknown,
>(
  params?: GetCategoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCategories>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCategoriesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Criar categoria customizada
 */
export const postCategoriesCreate = (
  postCategoriesCreateBody: PostCategoriesCreateBody,
  signal?: AbortSignal,
) => {
  return customInstance<PostCategoriesCreate201>({
    url: `/categories/create`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postCategoriesCreateBody,
    signal,
  });
};

export const getPostCategoriesCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postCategoriesCreate>>,
    TError,
    { data: PostCategoriesCreateBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postCategoriesCreate>>,
  TError,
  { data: PostCategoriesCreateBody },
  TContext
> => {
  const mutationKey = ["postCategoriesCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postCategoriesCreate>>,
    { data: PostCategoriesCreateBody }
  > = (props) => {
    const { data } = props ?? {};

    return postCategoriesCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostCategoriesCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postCategoriesCreate>>
>;
export type PostCategoriesCreateMutationBody = PostCategoriesCreateBody;
export type PostCategoriesCreateMutationError = unknown;

/**
 * @summary Criar categoria customizada
 */
export const usePostCategoriesCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postCategoriesCreate>>,
      TError,
      { data: PostCategoriesCreateBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postCategoriesCreate>>,
  TError,
  { data: PostCategoriesCreateBody },
  TContext
> => {
  return useMutation(
    getPostCategoriesCreateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Atualizar categoria
 */
export const putCategoriesUpdateId = (
  id: string,
  putCategoriesUpdateIdBody: PutCategoriesUpdateIdBody,
  signal?: AbortSignal,
) => {
  return customInstance<PutCategoriesUpdateId200>({
    url: `/categories/update/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: putCategoriesUpdateIdBody,
    signal,
  });
};

export const getPutCategoriesUpdateIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putCategoriesUpdateId>>,
    TError,
    { id: string; data: PutCategoriesUpdateIdBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putCategoriesUpdateId>>,
  TError,
  { id: string; data: PutCategoriesUpdateIdBody },
  TContext
> => {
  const mutationKey = ["putCategoriesUpdateId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putCategoriesUpdateId>>,
    { id: string; data: PutCategoriesUpdateIdBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return putCategoriesUpdateId(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutCategoriesUpdateIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putCategoriesUpdateId>>
>;
export type PutCategoriesUpdateIdMutationBody = PutCategoriesUpdateIdBody;
export type PutCategoriesUpdateIdMutationError = unknown;

/**
 * @summary Atualizar categoria
 */
export const usePutCategoriesUpdateId = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putCategoriesUpdateId>>,
      TError,
      { id: string; data: PutCategoriesUpdateIdBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putCategoriesUpdateId>>,
  TError,
  { id: string; data: PutCategoriesUpdateIdBody },
  TContext
> => {
  return useMutation(
    getPutCategoriesUpdateIdMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Deletar categoria
 */
export const deleteCategoriesDeleteId = (id: string, signal?: AbortSignal) => {
  return customInstance<DeleteCategoriesDeleteId200>({
    url: `/categories/delete/${id}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteCategoriesDeleteIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCategoriesDeleteId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCategoriesDeleteId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteCategoriesDeleteId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCategoriesDeleteId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteCategoriesDeleteId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCategoriesDeleteIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCategoriesDeleteId>>
>;

export type DeleteCategoriesDeleteIdMutationError = unknown;

/**
 * @summary Deletar categoria
 */
export const useDeleteCategoriesDeleteId = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCategoriesDeleteId>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCategoriesDeleteId>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getDeleteCategoriesDeleteIdMutationOptions(options),
    queryClient,
  );
};
