/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from './User.ts';

export type AuthRefresh = {
  /**
   * @type object
   */
  user: User;
  /**
   * @type string
   */
  accessToken: string;
};
