/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from "./User.js";

export type AuthResponse = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type object | undefined
     */
    user?: User;
    /**
     * @type string | undefined
     */
    token?: string;
  };
  /**
   * @type string | undefined
   */
  message?: string;
};
