/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from "./User.ts";

export type AuthResponse = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type object
     */
    user: User;
    /**
     * @type string
     */
    accessToken: string;
    /**
     * @type string
     */
    refreshToken: string;
  };
  /**
   * @type string | undefined
   */
  message?: string;
};
