/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Budget = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string, uuid
   */
  userId: string;
  /**
   * @type string, uuid
   */
  categoryId: string;
  /**
   * @description Valor decimal como string
   * @type string
   */
  monthlyLimit: string;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
};
