/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const categoryTypeEnum = {
    "income": "income",
    "expense": "expense",
    "both": "both"
} as const;

export type CategoryTypeEnumKey = (typeof categoryTypeEnum)[keyof typeof categoryTypeEnum];

export type Category = {
    /**
     * @type string | undefined, uuid
    */
    id?: string;
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string | undefined
    */
    icon?: string;
    /**
     * @type string | undefined
    */
    type?: CategoryTypeEnumKey;
    /**
     * @type boolean | undefined
    */
    isDefault?: boolean;
    /**
     * @type string, uuid
    */
    userId?: string | null;
};