/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type Category = {
    /**
     * @type string | undefined, uuid
    */
    id?: string;
    /**
     * @type string, uuid
    */
    userId?: string | null;
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type boolean | undefined
    */
    isGlobal?: boolean;
    /**
     * @type string | undefined, date-time
    */
    createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    updatedAt?: string;
};