/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CategoryChartItem = {
  /**
   * @description Category name
   * @type string
   */
  name: string;
  /**
   * @type number
   */
  income: number;
  /**
   * @type number
   */
  expense: number;
};
