/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const totalsSignalEnum = {
  up: 'up',
  down: 'down',
  stable: 'stable',
} as const;

export type TotalsSignalEnumKey = (typeof totalsSignalEnum)[keyof typeof totalsSignalEnum];

export const byCategorySignalEnum = {
  up: 'up',
  down: 'down',
  stable: 'stable',
} as const;

export type ByCategorySignalEnumKey =
  (typeof byCategorySignalEnum)[keyof typeof byCategorySignalEnum];

export type ComparativeInsights = {
  /**
   * @type object
   */
  basis: {
    /**
     * @type integer
     */
    periodsCompared: number;
    /**
     * @type object
     */
    currentPeriod: {
      /**
       * @type string
       */
      startDate: string;
      /**
       * @type string
       */
      endDate: string;
      /**
       * @type string
       */
      label: string;
    };
  };
  /**
   * @type object
   */
  totals: {
    /**
     * @type number
     */
    currentExpense: number;
    /**
     * @type number
     */
    averageExpense: number;
    /**
     * @type number
     */
    deltaPct: number | null;
    /**
     * @type string
     */
    signal: TotalsSignalEnumKey;
  };
  /**
   * @type array
   */
  byCategory: {
    /**
     * @type string, uuid
     */
    categoryId: string;
    /**
     * @type string
     */
    categoryName: string;
    /**
     * @type number
     */
    currentExpense: number;
    /**
     * @type number
     */
    averageExpense: number;
    /**
     * @type number
     */
    deltaPct: number | null;
    /**
     * @type string
     */
    signal: ByCategorySignalEnumKey;
    /**
     * @type string
     */
    message: string;
  }[];
  /**
   * @type array
   */
  highlights: string[];
};
