/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DashboardStats = {
  /**
   * @type number
   */
  totalIncome: number;
  /**
   * @type number
   */
  totalExpense: number;
  /**
   * @type number
   */
  balance: number;
  /**
   * @type number
   */
  percentUsed?: number | null;
  /**
   * @type number
   */
  remainingBudget: number;
};
