/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DashboardStats } from "./DashboardStats.ts";
import type { FinancialPeriodSummary } from "./FinancialPeriodSummary.ts";
import type { RecentTransactionItem } from "./RecentTransactionItem.ts";

export type DashboardOverview = {
  /**
   * @type object
   */
  stats: DashboardStats;
  /**
   * @type object
   */
  selectedPeriod: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string
     */
    startDate: string;
    /**
     * @type string
     */
    endDate: string;
    /**
     * @type string
     */
    label: string;
    /**
     * @type integer
     */
    transactionCount: number;
    /**
     * @type string
     */
    description: string;
  } | null;
  /**
   * @type array
   */
  availablePeriods: FinancialPeriodSummary[];
  /**
   * @type object
   */
  chart: {
    /**
     * @type array
     */
    data: {
      /**
       * @type string
       */
      name: string;
      /**
       * @type number
       */
      income: number;
      /**
       * @type number
       */
      expense: number;
    }[];
    /**
     * @type array
     */
    categories: {
      /**
       * @type string
       */
      id: string;
      /**
       * @type string
       */
      name: string;
    }[];
  };
  /**
   * @type array
   */
  recentTransactions: RecentTransactionItem[];
  /**
   * @type integer
   */
  transactionsCount: number;
};
