/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteNotificationsDevicesFidPathParams = {
  /**
   * @type string
   */
  fid: string;
};

/**
 * @description Sucesso
 */
export type DeleteNotificationsDevicesFid200 = {
  /**
   * @type object
   */
  data: {
    /**
     * @type boolean
     */
    unregistered: boolean;
  };
  /**
   * @type string | undefined
   */
  message?: string;
};

export const deleteNotificationsDevicesFid400SuccessEnum = {
  false: false,
} as const;

export type DeleteNotificationsDevicesFid400SuccessEnumKey =
  (typeof deleteNotificationsDevicesFid400SuccessEnum)[keyof typeof deleteNotificationsDevicesFid400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type DeleteNotificationsDevicesFid400 = {
  /**
   * @type boolean
   */
  success: DeleteNotificationsDevicesFid400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const deleteNotificationsDevicesFid401SuccessEnum = {
  false: false,
} as const;

export type DeleteNotificationsDevicesFid401SuccessEnumKey =
  (typeof deleteNotificationsDevicesFid401SuccessEnum)[keyof typeof deleteNotificationsDevicesFid401SuccessEnum];

/**
 * @description Não autenticado
 */
export type DeleteNotificationsDevicesFid401 = {
  /**
   * @type boolean
   */
  success: DeleteNotificationsDevicesFid401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const deleteNotificationsDevicesFid404SuccessEnum = {
  false: false,
} as const;

export type DeleteNotificationsDevicesFid404SuccessEnumKey =
  (typeof deleteNotificationsDevicesFid404SuccessEnum)[keyof typeof deleteNotificationsDevicesFid404SuccessEnum];

/**
 * @description Recurso não encontrado
 */
export type DeleteNotificationsDevicesFid404 = {
  /**
   * @type boolean
   */
  success: DeleteNotificationsDevicesFid404SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type DeleteNotificationsDevicesFidMutationResponse = DeleteNotificationsDevicesFid200;

export type DeleteNotificationsDevicesFidMutation = {
  Response: DeleteNotificationsDevicesFid200;
  PathParams: DeleteNotificationsDevicesFidPathParams;
  Errors:
    | DeleteNotificationsDevicesFid400
    | DeleteNotificationsDevicesFid401
    | DeleteNotificationsDevicesFid404;
};
