/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteCompaniesIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Sucesso
 */
export type DeleteCompaniesId200 = {
  data: any | null;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const deleteCompaniesId400SuccessEnum = {
  false: false,
} as const;

export type DeleteCompaniesId400SuccessEnumKey =
  (typeof deleteCompaniesId400SuccessEnum)[keyof typeof deleteCompaniesId400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type DeleteCompaniesId400 = {
  /**
   * @type boolean
   */
  success: DeleteCompaniesId400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const deleteCompaniesId401SuccessEnum = {
  false: false,
} as const;

export type DeleteCompaniesId401SuccessEnumKey =
  (typeof deleteCompaniesId401SuccessEnum)[keyof typeof deleteCompaniesId401SuccessEnum];

/**
 * @description Não autenticado
 */
export type DeleteCompaniesId401 = {
  /**
   * @type boolean
   */
  success: DeleteCompaniesId401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const deleteCompaniesId404SuccessEnum = {
  false: false,
} as const;

export type DeleteCompaniesId404SuccessEnumKey =
  (typeof deleteCompaniesId404SuccessEnum)[keyof typeof deleteCompaniesId404SuccessEnum];

/**
 * @description Recurso não encontrado
 */
export type DeleteCompaniesId404 = {
  /**
   * @type boolean
   */
  success: DeleteCompaniesId404SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type DeleteCompaniesIdMutationResponse = DeleteCompaniesId200;

export type DeleteCompaniesIdMutation = {
  Response: DeleteCompaniesId200;
  PathParams: DeleteCompaniesIdPathParams;
  Errors: DeleteCompaniesId400 | DeleteCompaniesId401 | DeleteCompaniesId404;
};
