/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteTransactionsIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Deletada
 */
export type DeleteTransactionsId200 = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type DeleteTransactionsIdMutationResponse = DeleteTransactionsId200;

export type DeleteTransactionsIdMutation = {
  Response: DeleteTransactionsId200;
  PathParams: DeleteTransactionsIdPathParams;
  Errors: any;
};
