/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteRecurringTransactionsIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Deletada
 */
export type DeleteRecurringTransactionsId200 = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Não encontrada
 */
export type DeleteRecurringTransactionsId404 = any;

export type DeleteRecurringTransactionsIdMutationResponse =
  DeleteRecurringTransactionsId200;

export type DeleteRecurringTransactionsIdMutation = {
  Response: DeleteRecurringTransactionsId200;
  PathParams: DeleteRecurringTransactionsIdPathParams;
  Errors: DeleteRecurringTransactionsId404;
};
