/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ExpensesByCategoryItem = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type number
   */
  amount: number;
  /**
   * @type number
   */
  percentage: number;
};
