/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const occurrencesTypeEnum = {
  income: "income",
  expense: "expense",
} as const;

export type OccurrencesTypeEnumKey =
  (typeof occurrencesTypeEnum)[keyof typeof occurrencesTypeEnum];

export type ForecastResponse = {
  /**
   * @type object
   */
  period: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string
     */
    startDate: string;
    /**
     * @type string
     */
    endDate: string;
    /**
     * @type string
     */
    label: string;
  };
  /**
   * @type object
   */
  realized: {
    /**
     * @type number
     */
    income: number;
    /**
     * @type number
     */
    expense: number;
    /**
     * @type number
     */
    balance: number;
  };
  /**
   * @type object
   */
  projected: {
    /**
     * @type number
     */
    recurringIncome: number;
    /**
     * @type number
     */
    recurringExpense: number;
    /**
     * @type array
     */
    occurrences: {
      /**
       * @type string, uuid
       */
      recurringTransactionId: string;
      /**
       * @type string
       */
      title: string;
      /**
       * @type string
       */
      type: OccurrencesTypeEnumKey;
      /**
       * @type number
       */
      amount: number;
      /**
       * @type string
       */
      date: string;
    }[];
  };
  /**
   * @type number
   */
  projectedEndBalance: number;
  /**
   * @type string
   */
  asOf: string;
};
