/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaginatedResponse } from "./PaginatedResponse";

export type GetCategoriesQueryParams = {
  /**
   * @type number | undefined
   */
  page?: number;
  /**
   * @type number | undefined
   */
  limit?: number;
};

/**
 * @description Lista de categorias
 */
export type GetCategories200 = PaginatedResponse;

export type GetCategoriesQueryResponse = GetCategories200;

export type GetCategoriesQuery = {
  Response: GetCategories200;
  QueryParams: GetCategoriesQueryParams;
  Errors: any;
};
