/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Goal } from "./Goal";

/**
 * @description Lista de metas
 */
export type GetGoals200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type array | undefined
   */
  data?: Goal[];
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetGoalsQueryResponse = GetGoals200;

export type GetGoalsQuery = {
  Response: GetGoals200;
  Errors: any;
};
