/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Sucesso
 */
export type GetHealth200 = {
  /**
   * @type string
   */
  status: string;
  /**
   * @type string
   */
  message: string;
  /**
   * @type string
   */
  timestamp: string;
  /**
   * @type string
   */
  environment: string;
};

export const getHealth400SuccessEnum = {
  false: false,
} as const;

export type GetHealth400SuccessEnumKey =
  (typeof getHealth400SuccessEnum)[keyof typeof getHealth400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type GetHealth400 = {
  /**
   * @type boolean
   */
  success: GetHealth400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type GetHealthQueryResponse = GetHealth200;

export type GetHealthQuery = {
  Response: GetHealth200;
  Errors: GetHealth400;
};
