/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Notification } from './Notification.ts';

export type GetNotificationsQueryParams = {
  /**
   * @type boolean
   */
  unreadOnly?: boolean | null;
  /**
   * @type integer | undefined
   */
  page?: number;
  /**
   * @type integer | undefined
   */
  limit?: number;
};

export const getNotifications200SuccessEnum = {
  true: true,
} as const;

export type GetNotifications200SuccessEnumKey =
  (typeof getNotifications200SuccessEnum)[keyof typeof getNotifications200SuccessEnum];

/**
 * @description Sucesso
 */
export type GetNotifications200 = {
  /**
   * @type boolean
   */
  success: GetNotifications200SuccessEnumKey;
  /**
   * @type array
   */
  data: Notification[];
  /**
   * @type object
   */
  pagination: {
    /**
     * @type number
     */
    page: number;
    /**
     * @type number
     */
    limit: number;
    /**
     * @type number
     */
    total: number;
    /**
     * @type number
     */
    totalPages: number;
    /**
     * @type boolean
     */
    hasNext: boolean;
    /**
     * @type boolean
     */
    hasPrev: boolean;
  };
  /**
   * @type string | undefined
   */
  message?: string;
};

export const getNotifications400SuccessEnum = {
  false: false,
} as const;

export type GetNotifications400SuccessEnumKey =
  (typeof getNotifications400SuccessEnum)[keyof typeof getNotifications400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type GetNotifications400 = {
  /**
   * @type boolean
   */
  success: GetNotifications400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const getNotifications401SuccessEnum = {
  false: false,
} as const;

export type GetNotifications401SuccessEnumKey =
  (typeof getNotifications401SuccessEnum)[keyof typeof getNotifications401SuccessEnum];

/**
 * @description Não autenticado
 */
export type GetNotifications401 = {
  /**
   * @type boolean
   */
  success: GetNotifications401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type GetNotificationsQueryResponse = GetNotifications200;

export type GetNotificationsQuery = {
  Response: GetNotifications200;
  QueryParams: GetNotificationsQueryParams;
  Errors: GetNotifications400 | GetNotifications401;
};
