/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OvertimeRecord } from './OvertimeRecord.ts';

export type GetOvertimeQueryParams = {
  /**
   * @minLength 1
   * @maxLength 12
   * @type integer | undefined
   */
  month?: number;
  /**
   * @minLength 2000
   * @type integer | undefined
   */
  year?: number;
  /**
   * @type string | undefined, uuid
   */
  companyId?: string;
  /**
   * @type integer | undefined
   */
  page?: number;
  /**
   * @maxLength 100
   * @type integer | undefined
   */
  limit?: number;
};

export const getOvertime200SuccessEnum = {
  true: true,
} as const;

export type GetOvertime200SuccessEnumKey =
  (typeof getOvertime200SuccessEnum)[keyof typeof getOvertime200SuccessEnum];

/**
 * @description Sucesso
 */
export type GetOvertime200 = {
  /**
   * @type boolean
   */
  success: GetOvertime200SuccessEnumKey;
  /**
   * @type array
   */
  data: OvertimeRecord[];
  /**
   * @type object
   */
  pagination: {
    /**
     * @type number
     */
    page: number;
    /**
     * @type number
     */
    limit: number;
    /**
     * @type number
     */
    total: number;
    /**
     * @type number
     */
    totalPages: number;
    /**
     * @type boolean
     */
    hasNext: boolean;
    /**
     * @type boolean
     */
    hasPrev: boolean;
  };
  /**
   * @type string | undefined
   */
  message?: string;
};

export const getOvertime400SuccessEnum = {
  false: false,
} as const;

export type GetOvertime400SuccessEnumKey =
  (typeof getOvertime400SuccessEnum)[keyof typeof getOvertime400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type GetOvertime400 = {
  /**
   * @type boolean
   */
  success: GetOvertime400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const getOvertime401SuccessEnum = {
  false: false,
} as const;

export type GetOvertime401SuccessEnumKey =
  (typeof getOvertime401SuccessEnum)[keyof typeof getOvertime401SuccessEnum];

/**
 * @description Não autenticado
 */
export type GetOvertime401 = {
  /**
   * @type boolean
   */
  success: GetOvertime401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type GetOvertimeQueryResponse = GetOvertime200;

export type GetOvertimeQuery = {
  Response: GetOvertime200;
  QueryParams: GetOvertimeQueryParams;
  Errors: GetOvertime400 | GetOvertime401;
};
