/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetOvertimeExportQueryParams = {
  /**
   * @minLength 1
   * @maxLength 12
   * @type integer | undefined
   */
  month?: number;
  /**
   * @minLength 2000
   * @type integer | undefined
   */
  year?: number;
  /**
   * @type string | undefined, uuid
   */
  companyId?: string;
};

/**
 * @description Sucesso
 */
export type GetOvertimeExport200 = string;

export const getOvertimeExport400SuccessEnum = {
  false: false,
} as const;

export type GetOvertimeExport400SuccessEnumKey =
  (typeof getOvertimeExport400SuccessEnum)[keyof typeof getOvertimeExport400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type GetOvertimeExport400 = {
  /**
   * @type boolean
   */
  success: GetOvertimeExport400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const getOvertimeExport401SuccessEnum = {
  false: false,
} as const;

export type GetOvertimeExport401SuccessEnumKey =
  (typeof getOvertimeExport401SuccessEnum)[keyof typeof getOvertimeExport401SuccessEnum];

/**
 * @description Não autenticado
 */
export type GetOvertimeExport401 = {
  /**
   * @type boolean
   */
  success: GetOvertimeExport401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type GetOvertimeExportQueryResponse = GetOvertimeExport200;

export type GetOvertimeExportQuery = {
  Response: GetOvertimeExport200;
  QueryParams: GetOvertimeExportQueryParams;
  Errors: GetOvertimeExport400 | GetOvertimeExport401;
};
