/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FinancialPeriod } from "./FinancialPeriod.ts";

/**
 * @description Lista de períodos
 */
export type GetOverviewPeriods200 = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type array
   */
  data: FinancialPeriod[];
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetOverviewPeriodsQueryResponse = GetOverviewPeriods200;

export type GetOverviewPeriodsQuery = {
  Response: GetOverviewPeriods200;
  Errors: any;
};
