/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OvertimeSummary } from './OvertimeSummary.ts';

export type GetOvertimeSummaryQueryParams = {
  /**
   * @minLength 1
   * @maxLength 12
   * @type integer
   */
  month: number;
  /**
   * @minLength 2000
   * @type integer
   */
  year: number;
};

/**
 * @description Sucesso
 */
export type GetOvertimeSummary200 = {
  /**
   * @type object
   */
  data: OvertimeSummary;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const getOvertimeSummary400SuccessEnum = {
  false: false,
} as const;

export type GetOvertimeSummary400SuccessEnumKey =
  (typeof getOvertimeSummary400SuccessEnum)[keyof typeof getOvertimeSummary400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type GetOvertimeSummary400 = {
  /**
   * @type boolean
   */
  success: GetOvertimeSummary400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const getOvertimeSummary401SuccessEnum = {
  false: false,
} as const;

export type GetOvertimeSummary401SuccessEnumKey =
  (typeof getOvertimeSummary401SuccessEnum)[keyof typeof getOvertimeSummary401SuccessEnum];

/**
 * @description Não autenticado
 */
export type GetOvertimeSummary401 = {
  /**
   * @type boolean
   */
  success: GetOvertimeSummary401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type GetOvertimeSummaryQueryResponse = GetOvertimeSummary200;

export type GetOvertimeSummaryQuery = {
  Response: GetOvertimeSummary200;
  QueryParams: GetOvertimeSummaryQueryParams;
  Errors: GetOvertimeSummary400 | GetOvertimeSummary401;
};
