/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ComparativeInsights } from "./ComparativeInsights.ts";

export type GetOverviewInsightsComparisonQueryParams = {
  /**
   * @minLength 1
   * @maxLength 12
   * @type integer | undefined
   */
  periodsBack?: number;
};

/**
 * @description Sucesso
 */
export type GetOverviewInsightsComparison200 = {
  /**
   * @type object
   */
  data: ComparativeInsights;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const getOverviewInsightsComparison400SuccessEnum = {
  false: false,
} as const;

export type GetOverviewInsightsComparison400SuccessEnumKey =
  (typeof getOverviewInsightsComparison400SuccessEnum)[keyof typeof getOverviewInsightsComparison400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type GetOverviewInsightsComparison400 = {
  /**
   * @type boolean
   */
  success: GetOverviewInsightsComparison400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const getOverviewInsightsComparison401SuccessEnum = {
  false: false,
} as const;

export type GetOverviewInsightsComparison401SuccessEnumKey =
  (typeof getOverviewInsightsComparison401SuccessEnum)[keyof typeof getOverviewInsightsComparison401SuccessEnum];

/**
 * @description Não autenticado
 */
export type GetOverviewInsightsComparison401 = {
  /**
   * @type boolean
   */
  success: GetOverviewInsightsComparison401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type GetOverviewInsightsComparisonQueryResponse =
  GetOverviewInsightsComparison200;

export type GetOverviewInsightsComparisonQuery = {
  Response: GetOverviewInsightsComparison200;
  QueryParams: GetOverviewInsightsComparisonQueryParams;
  Errors: GetOverviewInsightsComparison400 | GetOverviewInsightsComparison401;
};
