/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ForecastResponse } from "./ForecastResponse.ts";

export type GetOverviewForecastQueryParams = {
  /**
   * @type string | undefined, uuid
   */
  periodId?: string;
};

/**
 * @description Sucesso
 */
export type GetOverviewForecast200 = {
  /**
   * @type object
   */
  data: ForecastResponse;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const getOverviewForecast400SuccessEnum = {
  false: false,
} as const;

export type GetOverviewForecast400SuccessEnumKey =
  (typeof getOverviewForecast400SuccessEnum)[keyof typeof getOverviewForecast400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type GetOverviewForecast400 = {
  /**
   * @type boolean
   */
  success: GetOverviewForecast400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const getOverviewForecast401SuccessEnum = {
  false: false,
} as const;

export type GetOverviewForecast401SuccessEnumKey =
  (typeof getOverviewForecast401SuccessEnum)[keyof typeof getOverviewForecast401SuccessEnum];

/**
 * @description Não autenticado
 */
export type GetOverviewForecast401 = {
  /**
   * @type boolean
   */
  success: GetOverviewForecast401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type GetOverviewForecastQueryResponse = GetOverviewForecast200;

export type GetOverviewForecastQuery = {
  Response: GetOverviewForecast200;
  QueryParams: GetOverviewForecastQueryParams;
  Errors: GetOverviewForecast400 | GetOverviewForecast401;
};
