/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PlannerOverview } from "./PlannerOverview.ts";

/**
 * @description Sucesso
 */
export type GetOverviewPlanner200 = {
  /**
   * @type object
   */
  data: PlannerOverview;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const getOverviewPlanner400SuccessEnum = {
  false: false,
} as const;

export type GetOverviewPlanner400SuccessEnumKey =
  (typeof getOverviewPlanner400SuccessEnum)[keyof typeof getOverviewPlanner400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type GetOverviewPlanner400 = {
  /**
   * @type boolean
   */
  success: GetOverviewPlanner400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const getOverviewPlanner401SuccessEnum = {
  false: false,
} as const;

export type GetOverviewPlanner401SuccessEnumKey =
  (typeof getOverviewPlanner401SuccessEnum)[keyof typeof getOverviewPlanner401SuccessEnum];

/**
 * @description Não autenticado
 */
export type GetOverviewPlanner401 = {
  /**
   * @type boolean
   */
  success: GetOverviewPlanner401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type GetOverviewPlannerQueryResponse = GetOverviewPlanner200;

export type GetOverviewPlannerQuery = {
  Response: GetOverviewPlanner200;
  Errors: GetOverviewPlanner400 | GetOverviewPlanner401;
};
