/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CategoryChartItem } from "./CategoryChartItem.ts";
import type { ChartCategory } from "./ChartCategory.ts";
import type { DashboardStats } from "./DashboardStats.ts";
import type { FinancialPeriod } from "./FinancialPeriod.ts";
import type { RecentTransactionItem } from "./RecentTransactionItem.ts";
import type { SelectedPeriod } from "./SelectedPeriod.ts";

export type GetOverviewDashboardQueryParams = {
  /**
   * @type string | undefined, uuid
   */
  periodId?: string;
  /**
   * @type string | undefined, date-time
   */
  startDate?: string;
  /**
   * @type string | undefined, date-time
   */
  endDate?: string;
};

/**
 * @description Dados do dashboard
 */
export type GetOverviewDashboard200 = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type object
   */
  data: {
    /**
     * @type object
     */
    stats: DashboardStats;
    /**
     * @type object
     */
    selectedPeriod?: SelectedPeriod | null;
    /**
     * @type array
     */
    availablePeriods: FinancialPeriod[];
    /**
     * @type object
     */
    chart: {
      /**
       * @type array
       */
      data: CategoryChartItem[];
      /**
       * @type array
       */
      categories: ChartCategory[];
    };
    /**
     * @type array | undefined
     */
    recentTransactions?: RecentTransactionItem[];
    /**
     * @type number
     */
    transactionsCount: number;
  };
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetOverviewDashboardQueryResponse = GetOverviewDashboard200;

export type GetOverviewDashboardQuery = {
  Response: GetOverviewDashboard200;
  QueryParams: GetOverviewDashboardQueryParams;
  Errors: any;
};
