/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DashboardOverview } from "./DashboardOverview.ts";

export type GetOverviewDashboardQueryParams = {
  /**
   * @type string | undefined, uuid
   */
  periodId?: string;
  /**
   * @type string | undefined
   */
  startDate?: string;
  /**
   * @type string | undefined
   */
  endDate?: string;
};

/**
 * @description Sucesso
 */
export type GetOverviewDashboard200 = {
  /**
   * @type object
   */
  data: DashboardOverview;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const getOverviewDashboard400SuccessEnum = {
  false: false,
} as const;

export type GetOverviewDashboard400SuccessEnumKey =
  (typeof getOverviewDashboard400SuccessEnum)[keyof typeof getOverviewDashboard400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type GetOverviewDashboard400 = {
  /**
   * @type boolean
   */
  success: GetOverviewDashboard400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const getOverviewDashboard401SuccessEnum = {
  false: false,
} as const;

export type GetOverviewDashboard401SuccessEnumKey =
  (typeof getOverviewDashboard401SuccessEnum)[keyof typeof getOverviewDashboard401SuccessEnum];

/**
 * @description Não autenticado
 */
export type GetOverviewDashboard401 = {
  /**
   * @type boolean
   */
  success: GetOverviewDashboard401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type GetOverviewDashboardQueryResponse = GetOverviewDashboard200;

export type GetOverviewDashboardQuery = {
  Response: GetOverviewDashboard200;
  QueryParams: GetOverviewDashboardQueryParams;
  Errors: GetOverviewDashboard400 | GetOverviewDashboard401;
};
