/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Planejamento financeiro
*/
export type GetOverviewPlanner200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @type object | undefined
        */
        stats?: object;
        /**
         * @type array | undefined
        */
        alerts?: string[];
    };
    /**
     * @type string | undefined
    */
    message?: string;
};

export type GetOverviewPlannerQueryResponse = GetOverviewPlanner200;

export type GetOverviewPlannerQuery = {
    Response: GetOverviewPlanner200;
    Errors: any;
};