/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OvertimeRecord } from './OvertimeRecord.ts';

export type GetOvertimeQueryParams = {
  /**
   * @type string | undefined, uuid
   */
  periodId?: string;
  /**
   * @type string | undefined, uuid
   */
  companyId?: string;
};

/**
 * @description Sucesso
 */
export type GetOvertime200 = {
  /**
   * @type array
   */
  data: OvertimeRecord[];
  /**
   * @type string | undefined
   */
  message?: string;
};

export const getOvertime400SuccessEnum = {
  false: false,
} as const;

export type GetOvertime400SuccessEnumKey =
  (typeof getOvertime400SuccessEnum)[keyof typeof getOvertime400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type GetOvertime400 = {
  /**
   * @type boolean
   */
  success: GetOvertime400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const getOvertime401SuccessEnum = {
  false: false,
} as const;

export type GetOvertime401SuccessEnumKey =
  (typeof getOvertime401SuccessEnum)[keyof typeof getOvertime401SuccessEnum];

/**
 * @description Não autenticado
 */
export type GetOvertime401 = {
  /**
   * @type boolean
   */
  success: GetOvertime401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type GetOvertimeQueryResponse = GetOvertime200;

export type GetOvertimeQuery = {
  Response: GetOvertime200;
  QueryParams: GetOvertimeQueryParams;
  Errors: GetOvertime400 | GetOvertime401;
};
