/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FinancialInsights } from './FinancialInsights.ts';

/**
 * @description Sucesso
 */
export type GetOverviewInsights200 = {
  /**
   * @type object
   */
  data: FinancialInsights;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const getOverviewInsights400SuccessEnum = {
  false: false,
} as const;

export type GetOverviewInsights400SuccessEnumKey =
  (typeof getOverviewInsights400SuccessEnum)[keyof typeof getOverviewInsights400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type GetOverviewInsights400 = {
  /**
   * @type boolean
   */
  success: GetOverviewInsights400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const getOverviewInsights401SuccessEnum = {
  false: false,
} as const;

export type GetOverviewInsights401SuccessEnumKey =
  (typeof getOverviewInsights401SuccessEnum)[keyof typeof getOverviewInsights401SuccessEnum];

/**
 * @description Não autenticado
 */
export type GetOverviewInsights401 = {
  /**
   * @type boolean
   */
  success: GetOverviewInsights401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type GetOverviewInsightsQueryResponse = GetOverviewInsights200;

export type GetOverviewInsightsQuery = {
  Response: GetOverviewInsights200;
  Errors: GetOverviewInsights400 | GetOverviewInsights401;
};
