/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RecurringTransaction } from "./RecurringTransaction.ts";

export type GetRecurringTransactionsQueryParams = {
  /**
   * @type boolean
   */
  includeInactive?: boolean | null;
  /**
   * @type integer | undefined
   */
  page?: number;
  /**
   * @type integer | undefined
   */
  limit?: number;
};

export const getRecurringTransactions200SuccessEnum = {
  true: true,
} as const;

export type GetRecurringTransactions200SuccessEnumKey =
  (typeof getRecurringTransactions200SuccessEnum)[keyof typeof getRecurringTransactions200SuccessEnum];

/**
 * @description Sucesso
 */
export type GetRecurringTransactions200 = {
  /**
   * @type boolean
   */
  success: GetRecurringTransactions200SuccessEnumKey;
  /**
   * @type array
   */
  data: RecurringTransaction[];
  /**
   * @type object
   */
  pagination: {
    /**
     * @type number
     */
    page: number;
    /**
     * @type number
     */
    limit: number;
    /**
     * @type number
     */
    total: number;
    /**
     * @type number
     */
    totalPages: number;
    /**
     * @type boolean
     */
    hasNext: boolean;
    /**
     * @type boolean
     */
    hasPrev: boolean;
  };
  /**
   * @type string | undefined
   */
  message?: string;
};

export const getRecurringTransactions400SuccessEnum = {
  false: false,
} as const;

export type GetRecurringTransactions400SuccessEnumKey =
  (typeof getRecurringTransactions400SuccessEnum)[keyof typeof getRecurringTransactions400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type GetRecurringTransactions400 = {
  /**
   * @type boolean
   */
  success: GetRecurringTransactions400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const getRecurringTransactions401SuccessEnum = {
  false: false,
} as const;

export type GetRecurringTransactions401SuccessEnumKey =
  (typeof getRecurringTransactions401SuccessEnum)[keyof typeof getRecurringTransactions401SuccessEnum];

/**
 * @description Não autenticado
 */
export type GetRecurringTransactions401 = {
  /**
   * @type boolean
   */
  success: GetRecurringTransactions401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type GetRecurringTransactionsQueryResponse = GetRecurringTransactions200;

export type GetRecurringTransactionsQuery = {
  Response: GetRecurringTransactions200;
  QueryParams: GetRecurringTransactionsQueryParams;
  Errors: GetRecurringTransactions400 | GetRecurringTransactions401;
};
