/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaginatedResponse } from "./PaginatedResponse";

export type GetTransactionsQueryParams = {
  /**
   * @type number | undefined
   */
  page?: number;
  /**
   * @type number | undefined
   */
  limit?: number;
};

/**
 * @description Lista de transações
 */
export type GetTransactions200 = PaginatedResponse;

export type GetTransactionsQueryResponse = GetTransactions200;

export type GetTransactionsQuery = {
  Response: GetTransactions200;
  QueryParams: GetTransactionsQueryParams;
  Errors: any;
};
