/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MonthlySummaryItem } from "./MonthlySummaryItem.ts";

/**
 * @description Sucesso
 */
export type GetTransactionsSummaryByMonth200 = {
  /**
   * @type array
   */
  data: MonthlySummaryItem[];
  /**
   * @type string | undefined
   */
  message?: string;
};

export const getTransactionsSummaryByMonth400SuccessEnum = {
  false: false,
} as const;

export type GetTransactionsSummaryByMonth400SuccessEnumKey =
  (typeof getTransactionsSummaryByMonth400SuccessEnum)[keyof typeof getTransactionsSummaryByMonth400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type GetTransactionsSummaryByMonth400 = {
  /**
   * @type boolean
   */
  success: GetTransactionsSummaryByMonth400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const getTransactionsSummaryByMonth401SuccessEnum = {
  false: false,
} as const;

export type GetTransactionsSummaryByMonth401SuccessEnumKey =
  (typeof getTransactionsSummaryByMonth401SuccessEnum)[keyof typeof getTransactionsSummaryByMonth401SuccessEnum];

/**
 * @description Não autenticado
 */
export type GetTransactionsSummaryByMonth401 = {
  /**
   * @type boolean
   */
  success: GetTransactionsSummaryByMonth401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type GetTransactionsSummaryByMonthQueryResponse =
  GetTransactionsSummaryByMonth200;

export type GetTransactionsSummaryByMonthQuery = {
  Response: GetTransactionsSummaryByMonth200;
  Errors: GetTransactionsSummaryByMonth400 | GetTransactionsSummaryByMonth401;
};
