/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Resumo financeiro
 */
export type GetTransactionsSummary200 = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type object
   */
  data: {
    /**
     * @type number
     */
    totalIncome: number;
    /**
     * @type number
     */
    totalExpenses: number;
    /**
     * @type number
     */
    balance: number;
    /**
     * @type number
     */
    monthlyIncome: number;
    /**
     * @type number
     */
    percentUsed: number;
    /**
     * @type string
     */
    alert?: string | null;
    /**
     * @type object | undefined
     */
    byCategory?: {
      [key: string]: number;
    };
  };
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetTransactionsSummaryQueryResponse = GetTransactionsSummary200;

export type GetTransactionsSummaryQuery = {
  Response: GetTransactionsSummary200;
  Errors: any;
};
