/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Resumo financeiro
*/
export type GetTransactionsSummary200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @type number | undefined
        */
        totalIncome?: number;
        /**
         * @type number | undefined
        */
        totalExpense?: number;
        /**
         * @type number | undefined
        */
        balance?: number;
        /**
         * @type number | undefined
        */
        monthlyIncome?: number;
    };
    /**
     * @type string | undefined
    */
    message?: string;
};

export type GetTransactionsSummaryQueryResponse = GetTransactionsSummary200;

export type GetTransactionsSummaryQuery = {
    Response: GetTransactionsSummary200;
    Errors: any;
};