/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Resumo do período atual
 */
export type GetTransactionsSummaryCurrentPeriod200 = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type object
   */
  data: {
    /**
     * @type number
     */
    totalIncome: number;
    /**
     * @type number
     */
    totalExpense: number;
    /**
     * @type number
     */
    balance: number;
    /**
     * @type number | undefined
     */
    monthlyIncome?: number;
    /**
     * @type number | undefined
     */
    percentUsed?: number;
    /**
     * @type string | undefined
     */
    alert?: string;
  };
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetTransactionsSummaryCurrentPeriodQueryResponse =
  GetTransactionsSummaryCurrentPeriod200;

export type GetTransactionsSummaryCurrentPeriodQuery = {
  Response: GetTransactionsSummaryCurrentPeriod200;
  Errors: any;
};
