/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Pagination } from "./Pagination.ts";
import type { Transaction } from "./Transaction.ts";
import type { TransactionListSummary } from "./TransactionListSummary.ts";

export type GetTransactionsQueryParams = {
  /**
   * @type number | undefined
   */
  page?: number;
  /**
   * @type number | undefined
   */
  limit?: number;
};

/**
 * @description Lista de transações com resumo do período
 */
export type GetTransactions200 = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type array
   */
  data: Transaction[];
  /**
   * @type object
   */
  pagination: Pagination;
  /**
   * @type object
   */
  summary: TransactionListSummary;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetTransactionsQueryResponse = GetTransactions200;

export type GetTransactionsQuery = {
  Response: GetTransactions200;
  QueryParams: GetTransactionsQueryParams;
  Errors: any;
};
