/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Resumo mensal
*/
export type GetTransactionsSummaryByMonth200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @type number | undefined
        */
        totalIncome?: number;
        /**
         * @type number | undefined
        */
        totalExpense?: number;
        /**
         * @type number | undefined
        */
        balance?: number;
        /**
         * @type number | undefined
        */
        monthlyIncome?: number;
    };
    /**
     * @type string | undefined
    */
    message?: string;
};

export type GetTransactionsSummaryByMonthQueryResponse = GetTransactionsSummaryByMonth200;

export type GetTransactionsSummaryByMonthQuery = {
    Response: GetTransactionsSummaryByMonth200;
    Errors: any;
};