/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Resumo do período atual
*/
export type GetTransactionsSummaryCurrentPeriod200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @type number | undefined
        */
        totalIncome?: number;
        /**
         * @type number | undefined
        */
        totalExpense?: number;
        /**
         * @type number | undefined
        */
        balance?: number;
        /**
         * @type number | undefined
        */
        monthlyIncome?: number;
        /**
         * @type number | undefined
        */
        percentUsed?: number;
        /**
         * @type string | undefined
        */
        alert?: string;
    };
    /**
     * @type string | undefined
    */
    message?: string;
};

export type GetTransactionsSummaryCurrentPeriodQueryResponse = GetTransactionsSummaryCurrentPeriod200;

export type GetTransactionsSummaryCurrentPeriodQuery = {
    Response: GetTransactionsSummaryCurrentPeriod200;
    Errors: any;
};