/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TransactionSummary } from './TransactionSummary.ts';

/**
 * @description Sucesso
 */
export type GetTransactionsSummary200 = {
  /**
   * @type object
   */
  data: TransactionSummary;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const getTransactionsSummary400SuccessEnum = {
  false: false,
} as const;

export type GetTransactionsSummary400SuccessEnumKey =
  (typeof getTransactionsSummary400SuccessEnum)[keyof typeof getTransactionsSummary400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type GetTransactionsSummary400 = {
  /**
   * @type boolean
   */
  success: GetTransactionsSummary400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const getTransactionsSummary401SuccessEnum = {
  false: false,
} as const;

export type GetTransactionsSummary401SuccessEnumKey =
  (typeof getTransactionsSummary401SuccessEnum)[keyof typeof getTransactionsSummary401SuccessEnum];

/**
 * @description Não autenticado
 */
export type GetTransactionsSummary401 = {
  /**
   * @type boolean
   */
  success: GetTransactionsSummary401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type GetTransactionsSummaryQueryResponse = GetTransactionsSummary200;

export type GetTransactionsSummaryQuery = {
  Response: GetTransactionsSummary200;
  Errors: GetTransactionsSummary400 | GetTransactionsSummary401;
};
