/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getTransactionsExportQueryParamsTypeEnum = {
  income: 'income',
  expense: 'expense',
} as const;

export type GetTransactionsExportQueryParamsTypeEnumKey =
  (typeof getTransactionsExportQueryParamsTypeEnum)[keyof typeof getTransactionsExportQueryParamsTypeEnum];

export type GetTransactionsExportQueryParams = {
  /**
   * @type string | undefined
   */
  startDate?: string;
  /**
   * @type string | undefined
   */
  endDate?: string;
  /**
   * @type string | undefined, uuid
   */
  periodId?: string;
  /**
   * @type string | undefined
   */
  type?: GetTransactionsExportQueryParamsTypeEnumKey;
};

/**
 * @description Sucesso
 */
export type GetTransactionsExport200 = string;

export const getTransactionsExport400SuccessEnum = {
  false: false,
} as const;

export type GetTransactionsExport400SuccessEnumKey =
  (typeof getTransactionsExport400SuccessEnum)[keyof typeof getTransactionsExport400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type GetTransactionsExport400 = {
  /**
   * @type boolean
   */
  success: GetTransactionsExport400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const getTransactionsExport401SuccessEnum = {
  false: false,
} as const;

export type GetTransactionsExport401SuccessEnumKey =
  (typeof getTransactionsExport401SuccessEnum)[keyof typeof getTransactionsExport401SuccessEnum];

/**
 * @description Não autenticado
 */
export type GetTransactionsExport401 = {
  /**
   * @type boolean
   */
  success: GetTransactionsExport401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type GetTransactionsExportQueryResponse = GetTransactionsExport200;

export type GetTransactionsExportQuery = {
  Response: GetTransactionsExport200;
  QueryParams: GetTransactionsExportQueryParams;
  Errors: GetTransactionsExport400 | GetTransactionsExport401;
};
