/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Resumo mensal
 */
export type GetTransactionsSummaryByMonth200 = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type object
   */
  data: {
    /**
     * @type number
     */
    totalIncome: number;
    /**
     * @type number
     */
    totalExpense: number;
    /**
     * @type number
     */
    balance: number;
    /**
     * @type number | undefined
     */
    monthlyIncome?: number;
  };
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetTransactionsSummaryByMonthQueryResponse =
  GetTransactionsSummaryByMonth200;

export type GetTransactionsSummaryByMonthQuery = {
  Response: GetTransactionsSummaryByMonth200;
  Errors: any;
};
