/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetUserFinancialPeriodsPeriodidPathParams = {
    /**
     * @type string
    */
    periodId: string;
};

/**
 * @description Período financeiro
*/
export type GetUserFinancialPeriodsPeriodid200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @type string | undefined
        */
        id?: string;
        /**
         * @type string | undefined, date-time
        */
        startDate?: string;
        /**
         * @type string | undefined, date-time
        */
        endDate?: string;
        /**
         * @type boolean | undefined
        */
        isActive?: boolean;
    };
    /**
     * @type string | undefined
    */
    message?: string;
};

/**
 * @description Período não encontrado
*/
export type GetUserFinancialPeriodsPeriodid404 = any;

export type GetUserFinancialPeriodsPeriodidQueryResponse = GetUserFinancialPeriodsPeriodid200;

export type GetUserFinancialPeriodsPeriodidQuery = {
    Response: GetUserFinancialPeriodsPeriodid200;
    PathParams: GetUserFinancialPeriodsPeriodidPathParams;
    Errors: GetUserFinancialPeriodsPeriodid404;
};