/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from "./User.ts";

/**
 * @description Dados do usuário
 */
export type GetUserMe200 = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type object
   */
  data: User;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type GetUserMeQueryResponse = GetUserMe200;

export type GetUserMeQuery = {
  Response: GetUserMe200;
  Errors: any;
};
