/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Lista de períodos financeiros
*/
export type GetUserFinancialPeriods200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type array | undefined
    */
    data?: {
        /**
         * @type string | undefined
        */
        id?: string;
        /**
         * @type string | undefined, date-time
        */
        startDate?: string;
        /**
         * @type string | undefined, date-time
        */
        endDate?: string;
        /**
         * @type boolean | undefined
        */
        isStored?: boolean;
    }[];
    /**
     * @type string | undefined
    */
    message?: string;
};

export type GetUserFinancialPeriodsQueryResponse = GetUserFinancialPeriods200;

export type GetUserFinancialPeriodsQuery = {
    Response: GetUserFinancialPeriods200;
    Errors: any;
};