/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Goal = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string, uuid
   */
  userId: string;
  /**
   * @type string
   */
  title: string;
  /**
   * @type string
   */
  description?: string | null;
  /**
   * @type string
   */
  targetAmount: string;
  /**
   * @type string
   */
  currentAmount: string;
  /**
   * @type string, date-time
   */
  targetDate: string;
  /**
   * @type string, date-time
   */
  startDate: string;
  /**
   * @type boolean
   */
  isActive?: boolean | null;
  /**
   * @type string, date-time
   */
  createdAt: string;
  /**
   * @type string, date-time
   */
  updatedAt: string;
  /**
   * @type object | undefined
   */
  progress?: {
    /**
     * @type number
     */
    percentage: number;
    /**
     * @type number
     */
    daysRemaining: number;
    /**
     * @type number
     */
    remaining: number;
  };
  /**
   * @type array | undefined
   */
  milestones?: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    goalId: string;
    /**
     * @type number
     */
    percentage: number;
    /**
     * @type string
     */
    amount: string;
    /**
     * @type boolean
     */
    isReached: boolean;
    /**
     * @type string, date-time
     */
    reachedAt?: string | null;
    /**
     * @type string, date-time
     */
    createdAt: string;
  }[];
};
