/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Goal = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string, uuid
   */
  userId: string;
  /**
   * @type string
   */
  title: string;
  /**
   * @type string
   */
  description: string | null;
  /**
   * @description Valor decimal como string
   * @type string
   */
  targetAmount: string;
  /**
   * @description Valor decimal como string
   * @type string
   */
  currentAmount: string | null;
  /**
   * @type string
   */
  targetDate: string;
  /**
   * @type string
   */
  startDate: string;
  /**
   * @type boolean
   */
  isActive: boolean | null;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
};
