/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type Goal = {
    /**
     * @type string | undefined, uuid
    */
    id?: string;
    /**
     * @type string | undefined, uuid
    */
    userId?: string;
    /**
     * @type string | undefined
    */
    title?: string;
    /**
     * @type string
    */
    description?: string | null;
    /**
     * @type string | undefined
    */
    targetAmount?: string;
    /**
     * @type string | undefined
    */
    currentAmount?: string;
    /**
     * @type string | undefined, date-time
    */
    targetDate?: string;
    /**
     * @type string | undefined, date-time
    */
    startDate?: string;
    /**
     * @type boolean
    */
    isActive?: boolean | null;
    /**
     * @type string | undefined, date-time
    */
    createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    updatedAt?: string;
    /**
     * @type object | undefined
    */
    progress?: {
        /**
         * @type number | undefined
        */
        percentage?: number;
        /**
         * @type number | undefined
        */
        daysRemaining?: number;
        /**
         * @type number | undefined
        */
        remaining?: number;
    };
    /**
     * @type array | undefined
    */
    milestones?: {
        /**
         * @type string | undefined, uuid
        */
        id?: string;
        /**
         * @type string | undefined, uuid
        */
        goalId?: string;
        /**
         * @type number | undefined
        */
        percentage?: number;
        /**
         * @type string | undefined
        */
        amount?: string;
        /**
         * @type boolean | undefined
        */
        isReached?: boolean;
        /**
         * @type string, date-time
        */
        reachedAt?: string | null;
        /**
         * @type string | undefined, date-time
        */
        createdAt?: string;
    }[];
};