/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type IncomeAndPeriodUpdate = {
  monthlyIncome: string | number;
  /**
   * @type integer
   */
  financialDayStart: number;
  /**
   * @type integer
   */
  financialDayEnd: number;
  /**
   * @type boolean
   */
  firstAccess: boolean;
};
