/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type MonthlyChartItem = {
  /**
   * @description Formato yyyy-MM
   * @type string
   */
  month: string;
  /**
   * @description Ex: maio 2026
   * @type string
   */
  label: string;
  /**
   * @type number
   */
  income: number;
  [key: string]: unknown;
};
