/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type OvertimeSummary = {
  /**
   * @type integer
   */
  month: number;
  /**
   * @type integer
   */
  year: number;
  /**
   * @type number
   */
  totalHours: number;
  /**
   * @type number
   */
  totalAmount: number;
  /**
   * @type array
   */
  byCompany: {
    /**
     * @type string, uuid
     */
    companyId: string;
    /**
     * @type string
     */
    companyName: string;
    /**
     * @type number
     */
    hours: number;
    /**
     * @type number
     */
    amount: number;
  }[];
};
