/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Transaction } from "./Transaction.js";

export type PaginatedTransactions = {
  /**
   * @type array | undefined
   */
  data?: Transaction[];
  /**
   * @type object | undefined
   */
  pagination?: {
    /**
     * @type number | undefined
     */
    page?: number;
    /**
     * @type number | undefined
     */
    limit?: number;
    /**
     * @type number | undefined
     */
    total?: number;
    /**
     * @type number | undefined
     */
    totalPages?: number;
  };
};
