/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Pagination } from "./Pagination.ts";

export type PaginatedResponse = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type array
   */
  data: object[];
  /**
   * @type object
   */
  pagination: Pagination;
  /**
   * @type string | undefined
   */
  message?: string;
};
