/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RecurringTransaction } from './RecurringTransaction.ts';

export type PatchRecurringTransactionsIdReactivatePathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Sucesso
 */
export type PatchRecurringTransactionsIdReactivate200 = {
  /**
   * @type object
   */
  data: RecurringTransaction;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const patchRecurringTransactionsIdReactivate400SuccessEnum = {
  false: false,
} as const;

export type PatchRecurringTransactionsIdReactivate400SuccessEnumKey =
  (typeof patchRecurringTransactionsIdReactivate400SuccessEnum)[keyof typeof patchRecurringTransactionsIdReactivate400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type PatchRecurringTransactionsIdReactivate400 = {
  /**
   * @type boolean
   */
  success: PatchRecurringTransactionsIdReactivate400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const patchRecurringTransactionsIdReactivate401SuccessEnum = {
  false: false,
} as const;

export type PatchRecurringTransactionsIdReactivate401SuccessEnumKey =
  (typeof patchRecurringTransactionsIdReactivate401SuccessEnum)[keyof typeof patchRecurringTransactionsIdReactivate401SuccessEnum];

/**
 * @description Não autenticado
 */
export type PatchRecurringTransactionsIdReactivate401 = {
  /**
   * @type boolean
   */
  success: PatchRecurringTransactionsIdReactivate401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const patchRecurringTransactionsIdReactivate404SuccessEnum = {
  false: false,
} as const;

export type PatchRecurringTransactionsIdReactivate404SuccessEnumKey =
  (typeof patchRecurringTransactionsIdReactivate404SuccessEnum)[keyof typeof patchRecurringTransactionsIdReactivate404SuccessEnum];

/**
 * @description Recurso não encontrado
 */
export type PatchRecurringTransactionsIdReactivate404 = {
  /**
   * @type boolean
   */
  success: PatchRecurringTransactionsIdReactivate404SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type PatchRecurringTransactionsIdReactivateMutationResponse =
  PatchRecurringTransactionsIdReactivate200;

export type PatchRecurringTransactionsIdReactivateMutation = {
  Response: PatchRecurringTransactionsIdReactivate200;
  PathParams: PatchRecurringTransactionsIdReactivatePathParams;
  Errors:
    | PatchRecurringTransactionsIdReactivate400
    | PatchRecurringTransactionsIdReactivate401
    | PatchRecurringTransactionsIdReactivate404;
};
