/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PatchRecurringTransactionsIdDeactivatePathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Desativada
 */
export type PatchRecurringTransactionsIdDeactivate200 = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Não encontrada
 */
export type PatchRecurringTransactionsIdDeactivate404 = any;

export type PatchRecurringTransactionsIdDeactivateMutationResponse =
  PatchRecurringTransactionsIdDeactivate200;

export type PatchRecurringTransactionsIdDeactivateMutation = {
  Response: PatchRecurringTransactionsIdDeactivate200;
  PathParams: PatchRecurringTransactionsIdDeactivatePathParams;
  Errors: PatchRecurringTransactionsIdDeactivate404;
};
