/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RecurringTransaction } from "./RecurringTransaction.ts";

export type PatchRecurringTransactionsIdReactivatePathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Reativada
 */
export type PatchRecurringTransactionsIdReactivate200 = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type object
   */
  data: RecurringTransaction;
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Não encontrada
 */
export type PatchRecurringTransactionsIdReactivate404 = any;

export type PatchRecurringTransactionsIdReactivateMutationResponse =
  PatchRecurringTransactionsIdReactivate200;

export type PatchRecurringTransactionsIdReactivateMutation = {
  Response: PatchRecurringTransactionsIdReactivate200;
  PathParams: PatchRecurringTransactionsIdReactivatePathParams;
  Errors: PatchRecurringTransactionsIdReactivate404;
};
