/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Sucesso
 */
export type PatchNotificationsReadAll200 = {
  /**
   * @type object
   */
  data: {
    /**
     * @type integer
     */
    updatedCount: number;
  };
  /**
   * @type string | undefined
   */
  message?: string;
};

export const patchNotificationsReadAll400SuccessEnum = {
  false: false,
} as const;

export type PatchNotificationsReadAll400SuccessEnumKey =
  (typeof patchNotificationsReadAll400SuccessEnum)[keyof typeof patchNotificationsReadAll400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type PatchNotificationsReadAll400 = {
  /**
   * @type boolean
   */
  success: PatchNotificationsReadAll400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const patchNotificationsReadAll401SuccessEnum = {
  false: false,
} as const;

export type PatchNotificationsReadAll401SuccessEnumKey =
  (typeof patchNotificationsReadAll401SuccessEnum)[keyof typeof patchNotificationsReadAll401SuccessEnum];

/**
 * @description Não autenticado
 */
export type PatchNotificationsReadAll401 = {
  /**
   * @type boolean
   */
  success: PatchNotificationsReadAll401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type PatchNotificationsReadAllMutationResponse =
  PatchNotificationsReadAll200;

export type PatchNotificationsReadAllMutation = {
  Response: PatchNotificationsReadAll200;
  Errors: PatchNotificationsReadAll400 | PatchNotificationsReadAll401;
};
