/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Notification } from './Notification.ts';

export type PatchNotificationsIdReadPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Sucesso
 */
export type PatchNotificationsIdRead200 = {
  /**
   * @type object
   */
  data: Notification;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const patchNotificationsIdRead400SuccessEnum = {
  false: false,
} as const;

export type PatchNotificationsIdRead400SuccessEnumKey =
  (typeof patchNotificationsIdRead400SuccessEnum)[keyof typeof patchNotificationsIdRead400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type PatchNotificationsIdRead400 = {
  /**
   * @type boolean
   */
  success: PatchNotificationsIdRead400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const patchNotificationsIdRead401SuccessEnum = {
  false: false,
} as const;

export type PatchNotificationsIdRead401SuccessEnumKey =
  (typeof patchNotificationsIdRead401SuccessEnum)[keyof typeof patchNotificationsIdRead401SuccessEnum];

/**
 * @description Não autenticado
 */
export type PatchNotificationsIdRead401 = {
  /**
   * @type boolean
   */
  success: PatchNotificationsIdRead401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const patchNotificationsIdRead404SuccessEnum = {
  false: false,
} as const;

export type PatchNotificationsIdRead404SuccessEnumKey =
  (typeof patchNotificationsIdRead404SuccessEnum)[keyof typeof patchNotificationsIdRead404SuccessEnum];

/**
 * @description Recurso não encontrado
 */
export type PatchNotificationsIdRead404 = {
  /**
   * @type boolean
   */
  success: PatchNotificationsIdRead404SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type PatchNotificationsIdReadMutationResponse = PatchNotificationsIdRead200;

export type PatchNotificationsIdReadMutation = {
  Response: PatchNotificationsIdRead200;
  PathParams: PatchNotificationsIdReadPathParams;
  Errors: PatchNotificationsIdRead400 | PatchNotificationsIdRead401 | PatchNotificationsIdRead404;
};
