/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const alertsTypeEnum = {
  danger: 'danger',
  warning: 'warning',
  info: 'info',
} as const;

export type AlertsTypeEnumKey = (typeof alertsTypeEnum)[keyof typeof alertsTypeEnum];

export const alertsPriorityEnum = {
  high: 'high',
  medium: 'medium',
  low: 'low',
} as const;

export type AlertsPriorityEnumKey = (typeof alertsPriorityEnum)[keyof typeof alertsPriorityEnum];

export type PlannerOverview = {
  /**
   * @type object
   */
  stats: {
    /**
     * @type number
     */
    totalBudgeted: number;
    /**
     * @type number
     */
    totalSavingsGoal: number;
    /**
     * @type number
     */
    totalSaved: number;
    /**
     * @type number
     */
    savingsProgress: number;
    /**
     * @type number
     */
    budgetPercentage: number;
    /**
     * @type number
     */
    savingsPercentage: number;
    /**
     * @type number
     */
    remainingToSave: number;
    /**
     * @type number
     */
    availableForBudget: number;
  };
  /**
   * @type object
   */
  currentPeriod: {
    /**
     * @type string
     */
    startDate: string;
    /**
     * @type string
     */
    endDate: string;
    /**
     * @type string
     */
    description: string;
  };
  /**
   * @type array
   */
  alerts: {
    /**
     * @type string
     */
    type: AlertsTypeEnumKey;
    /**
     * @type string
     */
    message: string;
    /**
     * @type string
     */
    priority: AlertsPriorityEnumKey;
    /**
     * @type string | undefined
     */
    category?: string;
    /**
     * @type string | undefined
     */
    goal?: string;
    /**
     * @type number | undefined
     */
    percentage?: number;
    /**
     * @type number | undefined
     */
    daysRemaining?: number;
  }[];
};
