/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PlannerStats = {
  /**
   * @type number
   */
  totalBudgeted: number;
  /**
   * @type number
   */
  totalSavingsGoal: number;
  /**
   * @type number
   */
  totalSaved: number;
  /**
   * @type number
   */
  savingsProgress: number;
  /**
   * @type number
   */
  budgetPercentage: number;
  /**
   * @type number
   */
  savingsPercentage: number;
  /**
   * @type number
   */
  remainingToSave: number;
  /**
   * @type number
   */
  availableForBudget: number;
};
