/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RecurringTransaction } from "./RecurringTransaction.ts";

/**
 * @description Criada
 */
export type PostRecurringTransactions201 = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type object
   */
  data: RecurringTransaction;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const postRecurringTransactionsMutationRequestTypeEnum = {
  income: "income",
  expense: "expense",
} as const;

export type PostRecurringTransactionsMutationRequestTypeEnumKey =
  (typeof postRecurringTransactionsMutationRequestTypeEnum)[keyof typeof postRecurringTransactionsMutationRequestTypeEnum];

export const postRecurringTransactionsMutationRequestFrequencyEnum = {
  daily: "daily",
  weekly: "weekly",
  monthly: "monthly",
  yearly: "yearly",
} as const;

export type PostRecurringTransactionsMutationRequestFrequencyEnumKey =
  (typeof postRecurringTransactionsMutationRequestFrequencyEnum)[keyof typeof postRecurringTransactionsMutationRequestFrequencyEnum];

export type PostRecurringTransactionsMutationRequest = {
  /**
   * @type string
   */
  type: PostRecurringTransactionsMutationRequestTypeEnumKey;
  /**
   * @type string
   */
  title: string;
  /**
   * @type number
   */
  amount: number;
  /**
   * @type string, uuid
   */
  categoryId: string;
  /**
   * @type string
   */
  frequency: PostRecurringTransactionsMutationRequestFrequencyEnumKey;
  /**
   * @description Dia do mês (para frequency=monthly)
   * @minLength 1
   * @maxLength 31
   * @type number | undefined
   */
  dayOfMonth?: number;
  /**
   * @description Dia da semana (0=domingo, 6=sábado, para frequency=weekly)
   * @minLength 0
   * @maxLength 6
   * @type number | undefined
   */
  dayOfWeek?: number;
  /**
   * @type string | undefined
   */
  description?: string;
  /**
   * @description Quantidade de parcelas. Omitir para recorrência sem fim
   * @minLength 1
   * @type number | undefined
   */
  totalInstallments?: number;
  /**
   * @description Data de início. Se <= hoje cria imediatamente. Se futura, agenda. Omitir = agora
   * @type string | undefined, date-time
   */
  startDate?: string;
};

export type PostRecurringTransactionsMutationResponse =
  PostRecurringTransactions201;

export type PostRecurringTransactionsMutation = {
  Response: PostRecurringTransactions201;
  Request: PostRecurringTransactionsMutationRequest;
  Errors: any;
};
