/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Sucesso
 */
export type PostNotificationsDevices200 = {
  /**
   * @type object
   */
  data: {
    /**
     * @type boolean
     */
    registered: boolean;
  };
  /**
   * @type string | undefined
   */
  message?: string;
};

export const postNotificationsDevices400SuccessEnum = {
  false: false,
} as const;

export type PostNotificationsDevices400SuccessEnumKey =
  (typeof postNotificationsDevices400SuccessEnum)[keyof typeof postNotificationsDevices400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type PostNotificationsDevices400 = {
  /**
   * @type boolean
   */
  success: PostNotificationsDevices400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const postNotificationsDevices401SuccessEnum = {
  false: false,
} as const;

export type PostNotificationsDevices401SuccessEnumKey =
  (typeof postNotificationsDevices401SuccessEnum)[keyof typeof postNotificationsDevices401SuccessEnum];

/**
 * @description Não autenticado
 */
export type PostNotificationsDevices401 = {
  /**
   * @type boolean
   */
  success: PostNotificationsDevices401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type PostNotificationsDevicesMutationRequest = {
  /**
   * @type string
   */
  fid: string;
};

export type PostNotificationsDevicesMutationResponse = PostNotificationsDevices200;

export type PostNotificationsDevicesMutation = {
  Response: PostNotificationsDevices200;
  Request: PostNotificationsDevicesMutationRequest;
  Errors: PostNotificationsDevices400 | PostNotificationsDevices401;
};
