/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Logout realizado
*/
export type PostAuthLogout200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @type boolean | undefined
        */
        success?: boolean;
    };
    /**
     * @type string | undefined
    */
    message?: string;
};

export type PostAuthLogoutMutationRequest = {
    /**
     * @type string
    */
    refreshToken: string;
};

export type PostAuthLogoutMutationResponse = PostAuthLogout200;

export type PostAuthLogoutMutation = {
    Response: PostAuthLogout200;
    Request: PostAuthLogoutMutationRequest;
    Errors: any;
};