/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RecurringTransaction } from "./RecurringTransaction.ts";

/**
 * @description Sucesso
 */
export type PostRecurringTransactions201 = {
  /**
   * @type object
   */
  data: RecurringTransaction;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const postRecurringTransactions400SuccessEnum = {
  false: false,
} as const;

export type PostRecurringTransactions400SuccessEnumKey =
  (typeof postRecurringTransactions400SuccessEnum)[keyof typeof postRecurringTransactions400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type PostRecurringTransactions400 = {
  /**
   * @type boolean
   */
  success: PostRecurringTransactions400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const postRecurringTransactions401SuccessEnum = {
  false: false,
} as const;

export type PostRecurringTransactions401SuccessEnumKey =
  (typeof postRecurringTransactions401SuccessEnum)[keyof typeof postRecurringTransactions401SuccessEnum];

/**
 * @description Não autenticado
 */
export type PostRecurringTransactions401 = {
  /**
   * @type boolean
   */
  success: PostRecurringTransactions401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const postRecurringTransactionsMutationRequestTypeEnum = {
  income: "income",
  expense: "expense",
} as const;

export type PostRecurringTransactionsMutationRequestTypeEnumKey =
  (typeof postRecurringTransactionsMutationRequestTypeEnum)[keyof typeof postRecurringTransactionsMutationRequestTypeEnum];

export const postRecurringTransactionsMutationRequestFrequencyEnum = {
  daily: "daily",
  weekly: "weekly",
  monthly: "monthly",
  yearly: "yearly",
} as const;

export type PostRecurringTransactionsMutationRequestFrequencyEnumKey =
  (typeof postRecurringTransactionsMutationRequestFrequencyEnum)[keyof typeof postRecurringTransactionsMutationRequestFrequencyEnum];

export type PostRecurringTransactionsMutationRequest = {
  /**
   * @type string
   */
  type: PostRecurringTransactionsMutationRequestTypeEnumKey;
  /**
   * @minLength 1
   * @maxLength 100
   * @type string
   */
  title: string;
  amount: string | number;
  /**
   * @type string, uuid
   */
  categoryId: string;
  /**
   * @type string
   */
  frequency: PostRecurringTransactionsMutationRequestFrequencyEnumKey;
  /**
   * @minLength 1
   * @maxLength 31
   * @type integer | undefined
   */
  dayOfMonth?: number;
  /**
   * @minLength 0
   * @maxLength 6
   * @type integer | undefined
   */
  dayOfWeek?: number;
  /**
   * @maxLength 500
   * @type string | undefined
   */
  description?: string;
  /**
   * @minLength 1
   * @type integer | undefined
   */
  totalInstallments?: number;
  /**
   * @type string | undefined, date-time
   */
  startDate?: string;
};

export type PostRecurringTransactionsMutationResponse =
  PostRecurringTransactions201;

export type PostRecurringTransactionsMutation = {
  Response: PostRecurringTransactions201;
  Request: PostRecurringTransactionsMutationRequest;
  Errors: PostRecurringTransactions400 | PostRecurringTransactions401;
};
