/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Sucesso
 */
export type PostAuthLogout200 = {
  /**
   * @type object
   */
  data: {
    /**
     * @type boolean
     */
    success: boolean;
  };
  /**
   * @type string | undefined
   */
  message?: string;
};

export const postAuthLogout400SuccessEnum = {
  false: false,
} as const;

export type PostAuthLogout400SuccessEnumKey =
  (typeof postAuthLogout400SuccessEnum)[keyof typeof postAuthLogout400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type PostAuthLogout400 = {
  /**
   * @type boolean
   */
  success: PostAuthLogout400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const postAuthLogout401SuccessEnum = {
  false: false,
} as const;

export type PostAuthLogout401SuccessEnumKey =
  (typeof postAuthLogout401SuccessEnum)[keyof typeof postAuthLogout401SuccessEnum];

/**
 * @description Não autenticado
 */
export type PostAuthLogout401 = {
  /**
   * @type boolean
   */
  success: PostAuthLogout401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type PostAuthLogoutMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  refreshToken: string;
};

export type PostAuthLogoutMutationResponse = PostAuthLogout200;

export type PostAuthLogoutMutation = {
  Response: PostAuthLogout200;
  Request: PostAuthLogoutMutationRequest;
  Errors: PostAuthLogout400 | PostAuthLogout401;
};
