/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Goal } from "./Goal.ts";

export type PostGoalsIdAddAmountPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Valor adicionado
 */
export type PostGoalsIdAddAmount200 = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type object
   */
  data: Goal;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostGoalsIdAddAmountMutationRequest = {
  /**
   * @type number
   */
  amount: number;
};

export type PostGoalsIdAddAmountMutationResponse = PostGoalsIdAddAmount200;

export type PostGoalsIdAddAmountMutation = {
  Response: PostGoalsIdAddAmount200;
  Request: PostGoalsIdAddAmountMutationRequest;
  PathParams: PostGoalsIdAddAmountPathParams;
  Errors: any;
};
