/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Category } from "./Category.ts";

/**
 * @description Categoria criada
 */
export type PostCategoriesCreate201 = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type object
   */
  data: Category;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostCategoriesCreateMutationRequest = {
  /**
   * @type string
   */
  name: string;
};

export type PostCategoriesCreateMutationResponse = PostCategoriesCreate201;

export type PostCategoriesCreateMutation = {
  Response: PostCategoriesCreate201;
  Request: PostCategoriesCreateMutationRequest;
  Errors: any;
};
