/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RecurringTransaction } from './RecurringTransaction.ts';

/**
 * @description Sucesso
 */
export type PostRecurringTransactionsFromSubscription201 = {
  /**
   * @type object
   */
  data: RecurringTransaction;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const postRecurringTransactionsFromSubscription400SuccessEnum = {
  false: false,
} as const;

export type PostRecurringTransactionsFromSubscription400SuccessEnumKey =
  (typeof postRecurringTransactionsFromSubscription400SuccessEnum)[keyof typeof postRecurringTransactionsFromSubscription400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type PostRecurringTransactionsFromSubscription400 = {
  /**
   * @type boolean
   */
  success: PostRecurringTransactionsFromSubscription400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const postRecurringTransactionsFromSubscription401SuccessEnum = {
  false: false,
} as const;

export type PostRecurringTransactionsFromSubscription401SuccessEnumKey =
  (typeof postRecurringTransactionsFromSubscription401SuccessEnum)[keyof typeof postRecurringTransactionsFromSubscription401SuccessEnum];

/**
 * @description Não autenticado
 */
export type PostRecurringTransactionsFromSubscription401 = {
  /**
   * @type boolean
   */
  success: PostRecurringTransactionsFromSubscription401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const postRecurringTransactionsFromSubscriptionMutationRequestCadenceEnum = {
  weekly: 'weekly',
  monthly: 'monthly',
  yearly: 'yearly',
} as const;

export type PostRecurringTransactionsFromSubscriptionMutationRequestCadenceEnumKey =
  (typeof postRecurringTransactionsFromSubscriptionMutationRequestCadenceEnum)[keyof typeof postRecurringTransactionsFromSubscriptionMutationRequestCadenceEnum];

export type PostRecurringTransactionsFromSubscriptionMutationRequest = {
  /**
   * @minLength 1
   * @maxLength 100
   * @type string
   */
  title: string;
  amount: string | number;
  /**
   * @type string, uuid
   */
  categoryId: string;
  /**
   * @type string
   */
  cadence: PostRecurringTransactionsFromSubscriptionMutationRequestCadenceEnumKey;
  /**
   * @type string, date-time
   */
  nextEstimatedDate: string;
  /**
   * @maxLength 500
   * @type string | undefined
   */
  description?: string;
};

export type PostRecurringTransactionsFromSubscriptionMutationResponse =
  PostRecurringTransactionsFromSubscription201;

export type PostRecurringTransactionsFromSubscriptionMutation = {
  Response: PostRecurringTransactionsFromSubscription201;
  Request: PostRecurringTransactionsFromSubscriptionMutationRequest;
  Errors:
    | PostRecurringTransactionsFromSubscription400
    | PostRecurringTransactionsFromSubscription401;
};
