/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AuthSession } from "./AuthSession.ts";

/**
 * @description Sucesso
 */
export type PostAuthGoogle200 = {
  /**
   * @type object
   */
  data: AuthSession;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const postAuthGoogle400SuccessEnum = {
  false: false,
} as const;

export type PostAuthGoogle400SuccessEnumKey =
  (typeof postAuthGoogle400SuccessEnum)[keyof typeof postAuthGoogle400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type PostAuthGoogle400 = {
  /**
   * @type boolean
   */
  success: PostAuthGoogle400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type PostAuthGoogleMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  idToken: string;
};

export type PostAuthGoogleMutationResponse = PostAuthGoogle200;

export type PostAuthGoogleMutation = {
  Response: PostAuthGoogle200;
  Request: PostAuthGoogleMutationRequest;
  Errors: PostAuthGoogle400;
};
