/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from "./User";

/**
 * @description Token renovado
 */
export type PostAuthRefresh200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: {
    /**
     * @type object | undefined
     */
    user?: User;
    /**
     * @type string | undefined
     */
    accessToken?: string;
  };
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Refresh token inválido ou expirado
 */
export type PostAuthRefresh401 = any;

export type PostAuthRefreshMutationRequest = {
  /**
   * @type string
   */
  refreshToken: string;
};

export type PostAuthRefreshMutationResponse = PostAuthRefresh200;

export type PostAuthRefreshMutation = {
  Response: PostAuthRefresh200;
  Request: PostAuthRefreshMutationRequest;
  Errors: PostAuthRefresh401;
};
