/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AuthResponse } from "./AuthResponse";

/**
 * @description Login realizado
 */
export type PostAuthSignIn200 = AuthResponse;

/**
 * @description Credenciais inválidas
 */
export type PostAuthSignIn401 = any;

export type PostAuthSignInMutationRequest = {
  /**
   * @type string, email
   */
  email: string;
  /**
   * @type string
   */
  password: string;
};

export type PostAuthSignInMutationResponse = PostAuthSignIn200;

export type PostAuthSignInMutation = {
  Response: PostAuthSignIn200;
  Request: PostAuthSignInMutationRequest;
  Errors: PostAuthSignIn401;
};
