/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Category } from './Category.ts';

/**
 * @description Sucesso
 */
export type PostCategoriesCreate201 = {
  /**
   * @type object
   */
  data: Category;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const postCategoriesCreate400SuccessEnum = {
  false: false,
} as const;

export type PostCategoriesCreate400SuccessEnumKey =
  (typeof postCategoriesCreate400SuccessEnum)[keyof typeof postCategoriesCreate400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type PostCategoriesCreate400 = {
  /**
   * @type boolean
   */
  success: PostCategoriesCreate400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const postCategoriesCreate401SuccessEnum = {
  false: false,
} as const;

export type PostCategoriesCreate401SuccessEnumKey =
  (typeof postCategoriesCreate401SuccessEnum)[keyof typeof postCategoriesCreate401SuccessEnum];

/**
 * @description Não autenticado
 */
export type PostCategoriesCreate401 = {
  /**
   * @type boolean
   */
  success: PostCategoriesCreate401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type PostCategoriesCreateMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  name: string;
};

export type PostCategoriesCreateMutationResponse = PostCategoriesCreate201;

export type PostCategoriesCreateMutation = {
  Response: PostCategoriesCreate201;
  Request: PostCategoriesCreateMutationRequest;
  Errors: PostCategoriesCreate400 | PostCategoriesCreate401;
};
