/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Budget } from "./Budget";

/**
 * @description Criado
 */
export type PostBudgets201 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: Budget;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostBudgetsMutationRequest = {
  /**
   * @type string, uuid
   */
  categoryId: string;
  /**
   * @type number
   */
  monthlyLimit: number;
};

export type PostBudgetsMutationResponse = PostBudgets201;

export type PostBudgetsMutation = {
  Response: PostBudgets201;
  Request: PostBudgetsMutationRequest;
  Errors: any;
};
