/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AuthSession } from './AuthSession.ts';

/**
 * @description Sucesso
 */
export type PostAuthSignIn200 = {
  /**
   * @type object
   */
  data: AuthSession;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const postAuthSignIn400SuccessEnum = {
  false: false,
} as const;

export type PostAuthSignIn400SuccessEnumKey =
  (typeof postAuthSignIn400SuccessEnum)[keyof typeof postAuthSignIn400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type PostAuthSignIn400 = {
  /**
   * @type boolean
   */
  success: PostAuthSignIn400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type PostAuthSignInMutationRequest = {
  /**
   * @maxLength 100
   * @type string, email
   */
  email: string;
  /**
   * @minLength 1
   * @maxLength 128
   * @type string
   */
  password: string;
};

export type PostAuthSignInMutationResponse = PostAuthSignIn200;

export type PostAuthSignInMutation = {
  Response: PostAuthSignIn200;
  Request: PostAuthSignInMutationRequest;
  Errors: PostAuthSignIn400;
};
