/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AuthResponse } from "./AuthResponse.js";

/**
 * @description Usuário criado
 */
export type PostAuthSignUp201 = AuthResponse;

/**
 * @description Email já cadastrado
 */
export type PostAuthSignUp409 = any;

export type PostAuthSignUpMutationRequest = {
  /**
   * @type string
   */
  name: string;
  /**
   * @type string, email
   */
  email: string;
  /**
   * @minLength 6
   * @type string
   */
  password: string;
};

export type PostAuthSignUpMutationResponse = PostAuthSignUp201;

export type PostAuthSignUpMutation = {
  Response: PostAuthSignUp201;
  Request: PostAuthSignUpMutationRequest;
  Errors: PostAuthSignUp409;
};
