/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OvertimeRecord } from './OvertimeRecord.ts';

/**
 * @description Sucesso
 */
export type PostOvertime200 = {
  /**
   * @type object
   */
  data: OvertimeRecord;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const postOvertime400SuccessEnum = {
  false: false,
} as const;

export type PostOvertime400SuccessEnumKey =
  (typeof postOvertime400SuccessEnum)[keyof typeof postOvertime400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type PostOvertime400 = {
  /**
   * @type boolean
   */
  success: PostOvertime400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const postOvertime401SuccessEnum = {
  false: false,
} as const;

export type PostOvertime401SuccessEnumKey =
  (typeof postOvertime401SuccessEnum)[keyof typeof postOvertime401SuccessEnum];

/**
 * @description Não autenticado
 */
export type PostOvertime401 = {
  /**
   * @type boolean
   */
  success: PostOvertime401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type PostOvertimeMutationRequest = {
  /**
   * @type string, uuid
   */
  companyId: string;
  /**
   * @type string | undefined, uuid
   */
  categoryId?: string;
  /**
   * @maxLength 500
   * @type string | undefined
   */
  description?: string;
  /**
   * @type string, date-time
   */
  startTime: string;
  /**
   * @type string, date-time
   */
  endTime: string;
};

export type PostOvertimeMutationResponse = PostOvertime200;

export type PostOvertimeMutation = {
  Response: PostOvertime200;
  Request: PostOvertimeMutationRequest;
  Errors: PostOvertime400 | PostOvertime401;
};
