/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Budget } from "./Budget.ts";

export type PutBudgetsIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Sucesso
 */
export type PutBudgetsId200 = {
  /**
   * @type object
   */
  data: Budget;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const putBudgetsId400SuccessEnum = {
  false: false,
} as const;

export type PutBudgetsId400SuccessEnumKey =
  (typeof putBudgetsId400SuccessEnum)[keyof typeof putBudgetsId400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type PutBudgetsId400 = {
  /**
   * @type boolean
   */
  success: PutBudgetsId400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const putBudgetsId401SuccessEnum = {
  false: false,
} as const;

export type PutBudgetsId401SuccessEnumKey =
  (typeof putBudgetsId401SuccessEnum)[keyof typeof putBudgetsId401SuccessEnum];

/**
 * @description Não autenticado
 */
export type PutBudgetsId401 = {
  /**
   * @type boolean
   */
  success: PutBudgetsId401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const putBudgetsId404SuccessEnum = {
  false: false,
} as const;

export type PutBudgetsId404SuccessEnumKey =
  (typeof putBudgetsId404SuccessEnum)[keyof typeof putBudgetsId404SuccessEnum];

/**
 * @description Recurso não encontrado
 */
export type PutBudgetsId404 = {
  /**
   * @type boolean
   */
  success: PutBudgetsId404SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type PutBudgetsIdMutationRequest = {
  monthlyLimit: string | number;
};

export type PutBudgetsIdMutationResponse = PutBudgetsId200;

export type PutBudgetsIdMutation = {
  Response: PutBudgetsId200;
  Request: PutBudgetsIdMutationRequest;
  PathParams: PutBudgetsIdPathParams;
  Errors: PutBudgetsId400 | PutBudgetsId401 | PutBudgetsId404;
};
