/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Goal } from "./Goal.ts";

export type PutGoalsIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Atualizada
 */
export type PutGoalsId200 = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type object
   */
  data: Goal;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PutGoalsIdMutationRequest = {
  /**
   * @type string | undefined
   */
  title?: string;
  /**
   * @type string | undefined
   */
  description?: string;
  /**
   * @type number | undefined
   */
  targetAmount?: number;
  /**
   * @type string | undefined, date
   */
  targetDate?: string;
  /**
   * @type number | undefined
   */
  currentAmount?: number;
  /**
   * @type boolean | undefined
   */
  isActive?: boolean;
};

export type PutGoalsIdMutationResponse = PutGoalsId200;

export type PutGoalsIdMutation = {
  Response: PutGoalsId200;
  Request: PutGoalsIdMutationRequest;
  PathParams: PutGoalsIdPathParams;
  Errors: any;
};
