/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OvertimeRecord } from './OvertimeRecord.ts';

export type PutOvertimeIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Sucesso
 */
export type PutOvertimeId200 = {
  /**
   * @type object
   */
  data: OvertimeRecord;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const putOvertimeId400SuccessEnum = {
  false: false,
} as const;

export type PutOvertimeId400SuccessEnumKey =
  (typeof putOvertimeId400SuccessEnum)[keyof typeof putOvertimeId400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type PutOvertimeId400 = {
  /**
   * @type boolean
   */
  success: PutOvertimeId400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const putOvertimeId401SuccessEnum = {
  false: false,
} as const;

export type PutOvertimeId401SuccessEnumKey =
  (typeof putOvertimeId401SuccessEnum)[keyof typeof putOvertimeId401SuccessEnum];

/**
 * @description Não autenticado
 */
export type PutOvertimeId401 = {
  /**
   * @type boolean
   */
  success: PutOvertimeId401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const putOvertimeId404SuccessEnum = {
  false: false,
} as const;

export type PutOvertimeId404SuccessEnumKey =
  (typeof putOvertimeId404SuccessEnum)[keyof typeof putOvertimeId404SuccessEnum];

/**
 * @description Recurso não encontrado
 */
export type PutOvertimeId404 = {
  /**
   * @type boolean
   */
  success: PutOvertimeId404SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type PutOvertimeIdMutationRequest = {
  /**
   * @type string | undefined, uuid
   */
  companyId?: string;
  /**
   * @type string | undefined, uuid
   */
  categoryId?: string;
  /**
   * @maxLength 500
   * @type string | undefined
   */
  description?: string;
  /**
   * @type string | undefined, date-time
   */
  startTime?: string;
  /**
   * @type string | undefined, date-time
   */
  endTime?: string;
};

export type PutOvertimeIdMutationResponse = PutOvertimeId200;

export type PutOvertimeIdMutation = {
  Response: PutOvertimeId200;
  Request: PutOvertimeIdMutationRequest;
  PathParams: PutOvertimeIdPathParams;
  Errors: PutOvertimeId400 | PutOvertimeId401 | PutOvertimeId404;
};
