/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Transaction } from './Transaction.ts';

export type PutTransactionsIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Sucesso
 */
export type PutTransactionsId200 = {
  /**
   * @type object
   */
  data: Transaction;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const putTransactionsId400SuccessEnum = {
  false: false,
} as const;

export type PutTransactionsId400SuccessEnumKey =
  (typeof putTransactionsId400SuccessEnum)[keyof typeof putTransactionsId400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type PutTransactionsId400 = {
  /**
   * @type boolean
   */
  success: PutTransactionsId400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const putTransactionsId401SuccessEnum = {
  false: false,
} as const;

export type PutTransactionsId401SuccessEnumKey =
  (typeof putTransactionsId401SuccessEnum)[keyof typeof putTransactionsId401SuccessEnum];

/**
 * @description Não autenticado
 */
export type PutTransactionsId401 = {
  /**
   * @type boolean
   */
  success: PutTransactionsId401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const putTransactionsId404SuccessEnum = {
  false: false,
} as const;

export type PutTransactionsId404SuccessEnumKey =
  (typeof putTransactionsId404SuccessEnum)[keyof typeof putTransactionsId404SuccessEnum];

/**
 * @description Recurso não encontrado
 */
export type PutTransactionsId404 = {
  /**
   * @type boolean
   */
  success: PutTransactionsId404SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const putTransactionsIdMutationRequestTypeEnum = {
  income: 'income',
  expense: 'expense',
} as const;

export type PutTransactionsIdMutationRequestTypeEnumKey =
  (typeof putTransactionsIdMutationRequestTypeEnum)[keyof typeof putTransactionsIdMutationRequestTypeEnum];

export type PutTransactionsIdMutationRequest = {
  /**
   * @type string | undefined
   */
  type?: PutTransactionsIdMutationRequestTypeEnumKey;
  /**
   * @minLength 1
   * @maxLength 100
   * @type string | undefined
   */
  title?: string;
  amount?: string | number;
  /**
   * @minLength 1
   * @type string | undefined, uuid
   */
  category?: string;
  /**
   * @type string | undefined, uuid
   */
  periodId?: string;
  /**
   * @maxLength 500
   * @type string | undefined
   */
  description?: string;
  /**
   * @type string | undefined
   */
  date?: string;
};

export type PutTransactionsIdMutationResponse = PutTransactionsId200;

export type PutTransactionsIdMutation = {
  Response: PutTransactionsId200;
  Request: PutTransactionsIdMutationRequest;
  PathParams: PutTransactionsIdPathParams;
  Errors: PutTransactionsId400 | PutTransactionsId401 | PutTransactionsId404;
};
