/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Transaction } from "./Transaction.js";

export type PutTransactionsIdPathParams = {
  /**
   * @type string
   */
  id: string;
};

/**
 * @description Atualizada
 */
export type PutTransactionsId200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
  /**
   * @type object | undefined
   */
  data?: Transaction;
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PutTransactionsIdMutationResponse = PutTransactionsId200;

export type PutTransactionsIdMutation = {
  Response: PutTransactionsId200;
  PathParams: PutTransactionsIdPathParams;
  Errors: any;
};
