/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Rendimento e período financeiro atualizados
*/
export type PutUserIncomeAndPeriod200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @type number | undefined
        */
        monthlyIncome?: number;
        /**
         * @type number | undefined
        */
        financialDayStart?: number;
        /**
         * @type number | undefined
        */
        financialDayEnd?: number;
        /**
         * @type boolean | undefined
        */
        firstAccess?: boolean;
    };
    /**
     * @type string | undefined
    */
    message?: string;
};

export type PutUserIncomeAndPeriodMutationRequest = {
    /**
     * @minLength 0.01
     * @maxLength 999999999.99
     * @type number
    */
    monthlyIncome: number;
    /**
     * @minLength 1
     * @maxLength 31
     * @type number
    */
    financialDayStart: number;
    /**
     * @minLength 1
     * @maxLength 31
     * @type number
    */
    financialDayEnd: number;
};

export type PutUserIncomeAndPeriodMutationResponse = PutUserIncomeAndPeriod200;

export type PutUserIncomeAndPeriodMutation = {
    Response: PutUserIncomeAndPeriod200;
    Request: PutUserIncomeAndPeriodMutationRequest;
    Errors: any;
};