/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Rendimento atualizado
*/
export type PutUserIncome200 = {
    /**
     * @type boolean | undefined
    */
    success?: boolean;
    /**
     * @type object | undefined
    */
    data?: {
        /**
         * @type number | undefined
        */
        monthlyIncome?: number;
        /**
         * @type boolean | undefined
        */
        firstAccess?: boolean;
    };
    /**
     * @type string | undefined
    */
    message?: string;
};

export type PutUserIncomeMutationRequest = {
    /**
     * @minLength 0.01
     * @maxLength 999999999.99
     * @type number
    */
    monthlyIncome: number;
};

export type PutUserIncomeMutationResponse = PutUserIncome200;

export type PutUserIncomeMutation = {
    Response: PutUserIncome200;
    Request: PutUserIncomeMutationRequest;
    Errors: any;
};