/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Período financeiro atualizado
 */
export type PutUserFinancialPeriod200 = {
  /**
   * @type boolean
   */
  success: boolean;
  /**
   * @type object
   */
  data: {
    /**
     * @type number
     */
    financialDayStart: number;
    /**
     * @type number
     */
    financialDayEnd: number;
    /**
     * @type boolean
     */
    firstAccess: boolean;
  };
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PutUserFinancialPeriodMutationRequest = {
  /**
   * @minLength 1
   * @maxLength 31
   * @type number
   */
  financialDayStart: number;
  /**
   * @minLength 1
   * @maxLength 31
   * @type number
   */
  financialDayEnd: number;
};

export type PutUserFinancialPeriodMutationResponse = PutUserFinancialPeriod200;

export type PutUserFinancialPeriodMutation = {
  Response: PutUserFinancialPeriod200;
  Request: PutUserFinancialPeriodMutationRequest;
  Errors: any;
};
