/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { IncomeAndPeriodUpdate } from "./IncomeAndPeriodUpdate.ts";

/**
 * @description Sucesso
 */
export type PutUserIncomeAndPeriod200 = {
  /**
   * @type object
   */
  data: IncomeAndPeriodUpdate;
  /**
   * @type string | undefined
   */
  message?: string;
};

export const putUserIncomeAndPeriod400SuccessEnum = {
  false: false,
} as const;

export type PutUserIncomeAndPeriod400SuccessEnumKey =
  (typeof putUserIncomeAndPeriod400SuccessEnum)[keyof typeof putUserIncomeAndPeriod400SuccessEnum];

/**
 * @description Requisição inválida
 */
export type PutUserIncomeAndPeriod400 = {
  /**
   * @type boolean
   */
  success: PutUserIncomeAndPeriod400SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export const putUserIncomeAndPeriod401SuccessEnum = {
  false: false,
} as const;

export type PutUserIncomeAndPeriod401SuccessEnumKey =
  (typeof putUserIncomeAndPeriod401SuccessEnum)[keyof typeof putUserIncomeAndPeriod401SuccessEnum];

/**
 * @description Não autenticado
 */
export type PutUserIncomeAndPeriod401 = {
  /**
   * @type boolean
   */
  success: PutUserIncomeAndPeriod401SuccessEnumKey;
  /**
   * @type string
   */
  error: string;
  details?: any | null;
};

export type PutUserIncomeAndPeriodMutationRequest = {
  monthlyIncome: string | number;
  /**
   * @minLength 1
   * @maxLength 31
   * @type number
   */
  financialDayStart: number;
  /**
   * @minLength 1
   * @maxLength 31
   * @type number
   */
  financialDayEnd: number;
};

export type PutUserIncomeAndPeriodMutationResponse = PutUserIncomeAndPeriod200;

export type PutUserIncomeAndPeriodMutation = {
  Response: PutUserIncomeAndPeriod200;
  Request: PutUserIncomeAndPeriodMutationRequest;
  Errors: PutUserIncomeAndPeriod400 | PutUserIncomeAndPeriod401;
};
