/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const recentTransactionItemTypeEnum = {
  income: 'income',
  expense: 'expense',
} as const;

export type RecentTransactionItemTypeEnumKey =
  (typeof recentTransactionItemTypeEnum)[keyof typeof recentTransactionItemTypeEnum];

export type RecentTransactionItem = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string
   */
  type: RecentTransactionItemTypeEnumKey;
  /**
   * @type number
   */
  amount: number;
  /**
   * @description dd/MM/yyyy
   * @type string
   */
  date: string;
  /**
   * @type string
   */
  category: string;
  /**
   * @type string
   */
  description: string;
};
