/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const recurringTransactionTypeEnum = {
  income: "income",
  expense: "expense",
} as const;

export type RecurringTransactionTypeEnumKey =
  (typeof recurringTransactionTypeEnum)[keyof typeof recurringTransactionTypeEnum];

export const recurringTransactionFrequencyEnum = {
  daily: "daily",
  weekly: "weekly",
  monthly: "monthly",
  yearly: "yearly",
} as const;

export type RecurringTransactionFrequencyEnumKey =
  (typeof recurringTransactionFrequencyEnum)[keyof typeof recurringTransactionFrequencyEnum];

export type RecurringTransaction = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string, uuid
   */
  userId: string;
  /**
   * @type string
   */
  type: RecurringTransactionTypeEnumKey;
  /**
   * @type string
   */
  title: string;
  /**
   * @description Valor decimal como string
   * @type string
   */
  amount: string;
  /**
   * @type string, uuid
   */
  categoryId: string;
  /**
   * @type string
   */
  frequency: RecurringTransactionFrequencyEnumKey;
  /**
   * @type integer
   */
  dayOfMonth: number | null;
  /**
   * @type integer
   */
  dayOfWeek: number | null;
  /**
   * @type string
   */
  startDate: string | null;
  /**
   * @type integer
   */
  totalInstallments: number | null;
  /**
   * @type integer
   */
  executedInstallments: number;
  /**
   * @type string
   */
  nextExecution: string;
  /**
   * @type boolean
   */
  isActive: boolean;
  /**
   * @type string
   */
  description: string | null;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
};
