/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const recurringTransactionTypeEnum = {
  income: "income",
  expense: "expense",
} as const;

export type RecurringTransactionTypeEnumKey =
  (typeof recurringTransactionTypeEnum)[keyof typeof recurringTransactionTypeEnum];

export const recurringTransactionFrequencyEnum = {
  daily: "daily",
  weekly: "weekly",
  monthly: "monthly",
  yearly: "yearly",
} as const;

export type RecurringTransactionFrequencyEnumKey =
  (typeof recurringTransactionFrequencyEnum)[keyof typeof recurringTransactionFrequencyEnum];

export type RecurringTransaction = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string, uuid
   */
  userId: string;
  /**
   * @type string
   */
  type: RecurringTransactionTypeEnumKey;
  /**
   * @type string
   */
  title: string;
  /**
   * @type string
   */
  amount: string;
  /**
   * @type string
   */
  description?: string | null;
  /**
   * @type string, uuid
   */
  categoryId: string;
  /**
   * @type string
   */
  frequency: RecurringTransactionFrequencyEnumKey;
  /**
   * @minLength 1
   * @maxLength 31
   * @type number
   */
  dayOfMonth?: number | null;
  /**
   * @minLength 0
   * @maxLength 6
   * @type number
   */
  dayOfWeek?: number | null;
  /**
   * @description Data de início. null = criado imediatamente
   * @type string, date-time
   */
  startDate?: string | null;
  /**
   * @description Total de parcelas. null = sem limite
   * @type number
   */
  totalInstallments?: number | null;
  /**
   * @description Quantas parcelas já foram executadas
   * @type number | undefined
   */
  executedInstallments?: number;
  /**
   * @type boolean
   */
  isActive: boolean;
  /**
   * @type string, date-time
   */
  nextExecution: string;
  /**
   * @type string, date-time
   */
  createdAt: string;
  /**
   * @type string, date-time
   */
  updatedAt: string;
};
