/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type TransactionListSummary = {
  /**
   * @description Total de despesas no período filtrado
   * @type number
   */
  totalExpense: number;
  /**
   * @description Total de receitas no período filtrado
   * @type number
   */
  totalIncome: number;
  /**
   * @description Rendimento mensal cadastrado pelo usuário
   * @type number
   */
  monthlyIncome: number;
  /**
   * @description % do rendimento gasto
   * @type number
   */
  percentUsed?: number | null;
  /**
   * @description Alerta se percentUsed >= 80%
   * @type string
   */
  alert?: string | null;
};
