/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type TransactionSummary = {
  /**
   * @type number
   */
  totalIncome: number;
  /**
   * @type number
   */
  totalExpenses: number;
  /**
   * @type number
   */
  monthlyIncome: number;
  /**
   * @type number
   */
  balance: number;
  /**
   * @type number
   */
  percentUsed: number | null;
  /**
   * @type object
   */
  byCategory: {
    [key: string]: number;
  };
  /**
   * @type string
   */
  alert: string | null;
};
