/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TransactionCategory } from "./TransactionCategory.ts";

export const transactionTypeEnum = {
  income: "income",
  expense: "expense",
} as const;

export type TransactionTypeEnumKey =
  (typeof transactionTypeEnum)[keyof typeof transactionTypeEnum];

export type Transaction = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string
   */
  type: TransactionTypeEnumKey;
  /**
   * @type string
   */
  title: string;
  /**
   * @description Valor decimal como string
   * @type string
   */
  amount: string;
  /**
   * @type string
   */
  description: string | null;
  /**
   * @type string
   */
  date: string;
  /**
   * @type string, uuid
   */
  periodId: string | null;
  /**
   * @type string, uuid
   */
  recurringTransactionId: string | null;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
  /**
   * @type object
   */
  category: TransactionCategory;
};
