/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type User = {
    /**
     * @type string | undefined, uuid
    */
    id?: string;
    /**
     * @type string | undefined
    */
    name?: string;
    /**
     * @type string | undefined, email
    */
    email?: string;
    /**
     * @type string
    */
    googleId?: string | null;
    /**
     * @type string
    */
    avatar?: string | null;
    /**
     * @type string
    */
    monthlyIncome?: string | null;
    /**
     * @minLength 1
     * @maxLength 31
     * @type number
    */
    financialDayStart?: number | null;
    /**
     * @minLength 1
     * @maxLength 31
     * @type number
    */
    financialDayEnd?: number | null;
    /**
     * @type boolean
    */
    firstAccess?: boolean | null;
    /**
     * @type string | undefined, date-time
    */
    createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    updatedAt?: string;
};