/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Moneyly API
 * API para gerenciamento financeiro pessoal
 * OpenAPI spec version: 1.0.0
 */
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";

import type {
  PostTransactions200,
  PostTransactionsBody,
  PostTransactionsCreate201,
  PostTransactionsCreateBody,
  PutTransactionsId200,
} from "../moneylyAPI.schemas";

import api from "@/app/(utils)/axios-instance";

/**
 * @summary Criar transação
 */
export const postTransactionsCreate = (
  postTransactionsCreateBody: PostTransactionsCreateBody,
  signal?: AbortSignal
) => {
  return api<PostTransactionsCreate201>({
    url: `/transactions/create`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postTransactionsCreateBody,
    signal,
  });
};

export const getPostTransactionsCreateMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTransactionsCreate>>,
    TError,
    { data: PostTransactionsCreateBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTransactionsCreate>>,
  TError,
  { data: PostTransactionsCreateBody },
  TContext
> => {
  const mutationKey = ["postTransactionsCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTransactionsCreate>>,
    { data: PostTransactionsCreateBody }
  > = (props) => {
    const { data } = props ?? {};

    return postTransactionsCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostTransactionsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTransactionsCreate>>
>;
export type PostTransactionsCreateMutationBody = PostTransactionsCreateBody;
export type PostTransactionsCreateMutationError = unknown;

/**
 * @summary Criar transação
 */
export const usePostTransactionsCreate = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTransactionsCreate>>,
    TError,
    { data: PostTransactionsCreateBody },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof postTransactionsCreate>>,
  TError,
  { data: PostTransactionsCreateBody },
  TContext
> => {
  const mutationOptions = getPostTransactionsCreateMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Listar transações
 */
export const postTransactions = (
  postTransactionsBody: PostTransactionsBody,
  signal?: AbortSignal
) => {
  return api<PostTransactions200>({
    url: `/transactions/`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postTransactionsBody,
    signal,
  });
};

export const getPostTransactionsMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTransactions>>,
    TError,
    { data: PostTransactionsBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTransactions>>,
  TError,
  { data: PostTransactionsBody },
  TContext
> => {
  const mutationKey = ["postTransactions"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTransactions>>,
    { data: PostTransactionsBody }
  > = (props) => {
    const { data } = props ?? {};

    return postTransactions(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostTransactionsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTransactions>>
>;
export type PostTransactionsMutationBody = PostTransactionsBody;
export type PostTransactionsMutationError = unknown;

/**
 * @summary Listar transações
 */
export const usePostTransactions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTransactions>>,
    TError,
    { data: PostTransactionsBody },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof postTransactions>>,
  TError,
  { data: PostTransactionsBody },
  TContext
> => {
  const mutationOptions = getPostTransactionsMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Atualizar transação
 */
export const putTransactionsId = (id: string) => {
  return api<PutTransactionsId200>({
    url: `/transactions/${id}`,
    method: "PUT",
  });
};

export const getPutTransactionsIdMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putTransactionsId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putTransactionsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["putTransactionsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putTransactionsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return putTransactionsId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutTransactionsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putTransactionsId>>
>;

export type PutTransactionsIdMutationError = unknown;

/**
 * @summary Atualizar transação
 */
export const usePutTransactionsId = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putTransactionsId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof putTransactionsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getPutTransactionsIdMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Deletar transação
 */
export const deleteTransactionsId = (id: string) => {
  return api<void>({ url: `/transactions/${id}`, method: "DELETE" });
};

export const getDeleteTransactionsIdMutationOptions = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTransactionsId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteTransactionsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteTransactionsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteTransactionsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteTransactionsId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteTransactionsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteTransactionsId>>
>;

export type DeleteTransactionsIdMutationError = unknown;

/**
 * @summary Deletar transação
 */
export const useDeleteTransactionsId = <
  TError = unknown,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTransactionsId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteTransactionsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteTransactionsIdMutationOptions(options);

  return useMutation(mutationOptions);
};
