/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Moneyly API
 * ARQUIVO GERADO por `pnpm openapi:gen` (zod-to-openapi). NÃO editar à mão. Ver moneyly/.specs/01-api-contract.md
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  DeleteTransactionsId200,
  DeleteTransactionsId400,
  DeleteTransactionsId401,
  DeleteTransactionsId404,
  GetTransactions200,
  GetTransactions400,
  GetTransactions401,
  GetTransactionsExport400,
  GetTransactionsExport401,
  GetTransactionsExportParams,
  GetTransactionsParams,
  GetTransactionsSubscriptions200,
  GetTransactionsSubscriptions400,
  GetTransactionsSubscriptions401,
  GetTransactionsSummary200,
  GetTransactionsSummary400,
  GetTransactionsSummary401,
  GetTransactionsSummaryByMonth200,
  GetTransactionsSummaryByMonth400,
  GetTransactionsSummaryByMonth401,
  GetTransactionsSummaryCurrentPeriod200,
  GetTransactionsSummaryCurrentPeriod400,
  GetTransactionsSummaryCurrentPeriod401,
  PostTransactionsCreate201,
  PostTransactionsCreate400,
  PostTransactionsCreate401,
  PostTransactionsCreateBody,
  PutTransactionsId200,
  PutTransactionsId400,
  PutTransactionsId401,
  PutTransactionsId404,
  PutTransactionsIdBody,
} from "../moneylyAPI.schemas";

import { customInstance } from "../../../../(utils)/axios-instance";

/**
 * @summary Criar transação
 */
export const postTransactionsCreate = (
  postTransactionsCreateBody: PostTransactionsCreateBody,
  signal?: AbortSignal,
) => {
  return customInstance<PostTransactionsCreate201>({
    url: `/transactions/create`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: postTransactionsCreateBody,
    signal,
  });
};

export const getPostTransactionsCreateMutationOptions = <
  TError = PostTransactionsCreate400 | PostTransactionsCreate401,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postTransactionsCreate>>,
    TError,
    { data: PostTransactionsCreateBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postTransactionsCreate>>,
  TError,
  { data: PostTransactionsCreateBody },
  TContext
> => {
  const mutationKey = ["postTransactionsCreate"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postTransactionsCreate>>,
    { data: PostTransactionsCreateBody }
  > = (props) => {
    const { data } = props ?? {};

    return postTransactionsCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostTransactionsCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postTransactionsCreate>>
>;
export type PostTransactionsCreateMutationBody = PostTransactionsCreateBody;
export type PostTransactionsCreateMutationError =
  | PostTransactionsCreate400
  | PostTransactionsCreate401;

/**
 * @summary Criar transação
 */
export const usePostTransactionsCreate = <
  TError = PostTransactionsCreate400 | PostTransactionsCreate401,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postTransactionsCreate>>,
      TError,
      { data: PostTransactionsCreateBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postTransactionsCreate>>,
  TError,
  { data: PostTransactionsCreateBody },
  TContext
> => {
  return useMutation(
    getPostTransactionsCreateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Listar transações (paginado)
 */
export const getTransactions = (
  params?: GetTransactionsParams,
  signal?: AbortSignal,
) => {
  return customInstance<GetTransactions200>({
    url: `/transactions/`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetTransactionsQueryKey = (params?: GetTransactionsParams) => {
  return [`/transactions/`, ...(params ? [params] : [])] as const;
};

export const getGetTransactionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getTransactions>>,
  TError = GetTransactions400 | GetTransactions401,
>(
  params?: GetTransactionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactions>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTransactionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTransactions>>> = ({
    signal,
  }) => getTransactions(params, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTransactions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTransactionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTransactions>>
>;
export type GetTransactionsQueryError = GetTransactions400 | GetTransactions401;

export function useGetTransactions<
  TData = Awaited<ReturnType<typeof getTransactions>>,
  TError = GetTransactions400 | GetTransactions401,
>(
  params: undefined | GetTransactionsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactions>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransactions>>,
          TError,
          Awaited<ReturnType<typeof getTransactions>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTransactions<
  TData = Awaited<ReturnType<typeof getTransactions>>,
  TError = GetTransactions400 | GetTransactions401,
>(
  params?: GetTransactionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactions>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransactions>>,
          TError,
          Awaited<ReturnType<typeof getTransactions>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTransactions<
  TData = Awaited<ReturnType<typeof getTransactions>>,
  TError = GetTransactions400 | GetTransactions401,
>(
  params?: GetTransactionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactions>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Listar transações (paginado)
 */

export function useGetTransactions<
  TData = Awaited<ReturnType<typeof getTransactions>>,
  TError = GetTransactions400 | GetTransactions401,
>(
  params?: GetTransactionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactions>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTransactionsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Atualizar transação
 */
export const putTransactionsId = (
  id: string,
  putTransactionsIdBody: PutTransactionsIdBody,
  signal?: AbortSignal,
) => {
  return customInstance<PutTransactionsId200>({
    url: `/transactions/${id}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: putTransactionsIdBody,
    signal,
  });
};

export const getPutTransactionsIdMutationOptions = <
  TError = PutTransactionsId400 | PutTransactionsId401 | PutTransactionsId404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putTransactionsId>>,
    TError,
    { id: string; data: PutTransactionsIdBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putTransactionsId>>,
  TError,
  { id: string; data: PutTransactionsIdBody },
  TContext
> => {
  const mutationKey = ["putTransactionsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putTransactionsId>>,
    { id: string; data: PutTransactionsIdBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return putTransactionsId(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutTransactionsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putTransactionsId>>
>;
export type PutTransactionsIdMutationBody = PutTransactionsIdBody;
export type PutTransactionsIdMutationError =
  | PutTransactionsId400
  | PutTransactionsId401
  | PutTransactionsId404;

/**
 * @summary Atualizar transação
 */
export const usePutTransactionsId = <
  TError = PutTransactionsId400 | PutTransactionsId401 | PutTransactionsId404,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putTransactionsId>>,
      TError,
      { id: string; data: PutTransactionsIdBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putTransactionsId>>,
  TError,
  { id: string; data: PutTransactionsIdBody },
  TContext
> => {
  return useMutation(getPutTransactionsIdMutationOptions(options), queryClient);
};
/**
 * @summary Deletar transação
 */
export const deleteTransactionsId = (id: string, signal?: AbortSignal) => {
  return customInstance<DeleteTransactionsId200>({
    url: `/transactions/${id}`,
    method: "DELETE",
    signal,
  });
};

export const getDeleteTransactionsIdMutationOptions = <
  TError =
    | DeleteTransactionsId400
    | DeleteTransactionsId401
    | DeleteTransactionsId404,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTransactionsId>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteTransactionsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteTransactionsId"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteTransactionsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteTransactionsId(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteTransactionsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteTransactionsId>>
>;

export type DeleteTransactionsIdMutationError =
  | DeleteTransactionsId400
  | DeleteTransactionsId401
  | DeleteTransactionsId404;

/**
 * @summary Deletar transação
 */
export const useDeleteTransactionsId = <
  TError =
    | DeleteTransactionsId400
    | DeleteTransactionsId401
    | DeleteTransactionsId404,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteTransactionsId>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteTransactionsId>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getDeleteTransactionsIdMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Resumo financeiro
 */
export const getTransactionsSummary = (signal?: AbortSignal) => {
  return customInstance<GetTransactionsSummary200>({
    url: `/transactions/summary`,
    method: "GET",
    signal,
  });
};

export const getGetTransactionsSummaryQueryKey = () => {
  return [`/transactions/summary`] as const;
};

export const getGetTransactionsSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getTransactionsSummary>>,
  TError = GetTransactionsSummary400 | GetTransactionsSummary401,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getTransactionsSummary>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTransactionsSummaryQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTransactionsSummary>>
  > = ({ signal }) => getTransactionsSummary(signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTransactionsSummary>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTransactionsSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTransactionsSummary>>
>;
export type GetTransactionsSummaryQueryError =
  | GetTransactionsSummary400
  | GetTransactionsSummary401;

export function useGetTransactionsSummary<
  TData = Awaited<ReturnType<typeof getTransactionsSummary>>,
  TError = GetTransactionsSummary400 | GetTransactionsSummary401,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransactionsSummary>>,
          TError,
          Awaited<ReturnType<typeof getTransactionsSummary>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTransactionsSummary<
  TData = Awaited<ReturnType<typeof getTransactionsSummary>>,
  TError = GetTransactionsSummary400 | GetTransactionsSummary401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsSummary>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransactionsSummary>>,
          TError,
          Awaited<ReturnType<typeof getTransactionsSummary>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTransactionsSummary<
  TData = Awaited<ReturnType<typeof getTransactionsSummary>>,
  TError = GetTransactionsSummary400 | GetTransactionsSummary401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsSummary>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Resumo financeiro
 */

export function useGetTransactionsSummary<
  TData = Awaited<ReturnType<typeof getTransactionsSummary>>,
  TError = GetTransactionsSummary400 | GetTransactionsSummary401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsSummary>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTransactionsSummaryQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Resumo agregado por mês
 */
export const getTransactionsSummaryByMonth = (signal?: AbortSignal) => {
  return customInstance<GetTransactionsSummaryByMonth200>({
    url: `/transactions/summary-by-month`,
    method: "GET",
    signal,
  });
};

export const getGetTransactionsSummaryByMonthQueryKey = () => {
  return [`/transactions/summary-by-month`] as const;
};

export const getGetTransactionsSummaryByMonthQueryOptions = <
  TData = Awaited<ReturnType<typeof getTransactionsSummaryByMonth>>,
  TError = GetTransactionsSummaryByMonth400 | GetTransactionsSummaryByMonth401,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getTransactionsSummaryByMonth>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTransactionsSummaryByMonthQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTransactionsSummaryByMonth>>
  > = ({ signal }) => getTransactionsSummaryByMonth(signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTransactionsSummaryByMonth>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTransactionsSummaryByMonthQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTransactionsSummaryByMonth>>
>;
export type GetTransactionsSummaryByMonthQueryError =
  | GetTransactionsSummaryByMonth400
  | GetTransactionsSummaryByMonth401;

export function useGetTransactionsSummaryByMonth<
  TData = Awaited<ReturnType<typeof getTransactionsSummaryByMonth>>,
  TError = GetTransactionsSummaryByMonth400 | GetTransactionsSummaryByMonth401,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsSummaryByMonth>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransactionsSummaryByMonth>>,
          TError,
          Awaited<ReturnType<typeof getTransactionsSummaryByMonth>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTransactionsSummaryByMonth<
  TData = Awaited<ReturnType<typeof getTransactionsSummaryByMonth>>,
  TError = GetTransactionsSummaryByMonth400 | GetTransactionsSummaryByMonth401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsSummaryByMonth>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransactionsSummaryByMonth>>,
          TError,
          Awaited<ReturnType<typeof getTransactionsSummaryByMonth>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTransactionsSummaryByMonth<
  TData = Awaited<ReturnType<typeof getTransactionsSummaryByMonth>>,
  TError = GetTransactionsSummaryByMonth400 | GetTransactionsSummaryByMonth401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsSummaryByMonth>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Resumo agregado por mês
 */

export function useGetTransactionsSummaryByMonth<
  TData = Awaited<ReturnType<typeof getTransactionsSummaryByMonth>>,
  TError = GetTransactionsSummaryByMonth400 | GetTransactionsSummaryByMonth401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsSummaryByMonth>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTransactionsSummaryByMonthQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Resumo do período atual
 */
export const getTransactionsSummaryCurrentPeriod = (signal?: AbortSignal) => {
  return customInstance<GetTransactionsSummaryCurrentPeriod200>({
    url: `/transactions/summary-current-period`,
    method: "GET",
    signal,
  });
};

export const getGetTransactionsSummaryCurrentPeriodQueryKey = () => {
  return [`/transactions/summary-current-period`] as const;
};

export const getGetTransactionsSummaryCurrentPeriodQueryOptions = <
  TData = Awaited<ReturnType<typeof getTransactionsSummaryCurrentPeriod>>,
  TError =
    | GetTransactionsSummaryCurrentPeriod400
    | GetTransactionsSummaryCurrentPeriod401,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getTransactionsSummaryCurrentPeriod>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTransactionsSummaryCurrentPeriodQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTransactionsSummaryCurrentPeriod>>
  > = ({ signal }) => getTransactionsSummaryCurrentPeriod(signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTransactionsSummaryCurrentPeriod>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTransactionsSummaryCurrentPeriodQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTransactionsSummaryCurrentPeriod>>
>;
export type GetTransactionsSummaryCurrentPeriodQueryError =
  | GetTransactionsSummaryCurrentPeriod400
  | GetTransactionsSummaryCurrentPeriod401;

export function useGetTransactionsSummaryCurrentPeriod<
  TData = Awaited<ReturnType<typeof getTransactionsSummaryCurrentPeriod>>,
  TError =
    | GetTransactionsSummaryCurrentPeriod400
    | GetTransactionsSummaryCurrentPeriod401,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsSummaryCurrentPeriod>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransactionsSummaryCurrentPeriod>>,
          TError,
          Awaited<ReturnType<typeof getTransactionsSummaryCurrentPeriod>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTransactionsSummaryCurrentPeriod<
  TData = Awaited<ReturnType<typeof getTransactionsSummaryCurrentPeriod>>,
  TError =
    | GetTransactionsSummaryCurrentPeriod400
    | GetTransactionsSummaryCurrentPeriod401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsSummaryCurrentPeriod>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransactionsSummaryCurrentPeriod>>,
          TError,
          Awaited<ReturnType<typeof getTransactionsSummaryCurrentPeriod>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTransactionsSummaryCurrentPeriod<
  TData = Awaited<ReturnType<typeof getTransactionsSummaryCurrentPeriod>>,
  TError =
    | GetTransactionsSummaryCurrentPeriod400
    | GetTransactionsSummaryCurrentPeriod401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsSummaryCurrentPeriod>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Resumo do período atual
 */

export function useGetTransactionsSummaryCurrentPeriod<
  TData = Awaited<ReturnType<typeof getTransactionsSummaryCurrentPeriod>>,
  TError =
    | GetTransactionsSummaryCurrentPeriod400
    | GetTransactionsSummaryCurrentPeriod401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsSummaryCurrentPeriod>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetTransactionsSummaryCurrentPeriodQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Exportar transações em CSV
 */
export const getTransactionsExport = (
  params?: GetTransactionsExportParams,
  signal?: AbortSignal,
) => {
  return customInstance<string>({
    url: `/transactions/export`,
    method: "GET",
    params,
    signal,
  });
};

export const getGetTransactionsExportQueryKey = (
  params?: GetTransactionsExportParams,
) => {
  return [`/transactions/export`, ...(params ? [params] : [])] as const;
};

export const getGetTransactionsExportQueryOptions = <
  TData = Awaited<ReturnType<typeof getTransactionsExport>>,
  TError = GetTransactionsExport400 | GetTransactionsExport401,
>(
  params?: GetTransactionsExportParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsExport>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTransactionsExportQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTransactionsExport>>
  > = ({ signal }) => getTransactionsExport(params, signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTransactionsExport>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTransactionsExportQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTransactionsExport>>
>;
export type GetTransactionsExportQueryError =
  | GetTransactionsExport400
  | GetTransactionsExport401;

export function useGetTransactionsExport<
  TData = Awaited<ReturnType<typeof getTransactionsExport>>,
  TError = GetTransactionsExport400 | GetTransactionsExport401,
>(
  params: undefined | GetTransactionsExportParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsExport>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransactionsExport>>,
          TError,
          Awaited<ReturnType<typeof getTransactionsExport>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTransactionsExport<
  TData = Awaited<ReturnType<typeof getTransactionsExport>>,
  TError = GetTransactionsExport400 | GetTransactionsExport401,
>(
  params?: GetTransactionsExportParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsExport>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransactionsExport>>,
          TError,
          Awaited<ReturnType<typeof getTransactionsExport>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTransactionsExport<
  TData = Awaited<ReturnType<typeof getTransactionsExport>>,
  TError = GetTransactionsExport400 | GetTransactionsExport401,
>(
  params?: GetTransactionsExportParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsExport>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Exportar transações em CSV
 */

export function useGetTransactionsExport<
  TData = Awaited<ReturnType<typeof getTransactionsExport>>,
  TError = GetTransactionsExport400 | GetTransactionsExport401,
>(
  params?: GetTransactionsExportParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsExport>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTransactionsExportQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Detectar assinaturas (heurística)
 */
export const getTransactionsSubscriptions = (signal?: AbortSignal) => {
  return customInstance<GetTransactionsSubscriptions200>({
    url: `/transactions/subscriptions`,
    method: "GET",
    signal,
  });
};

export const getGetTransactionsSubscriptionsQueryKey = () => {
  return [`/transactions/subscriptions`] as const;
};

export const getGetTransactionsSubscriptionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getTransactionsSubscriptions>>,
  TError = GetTransactionsSubscriptions400 | GetTransactionsSubscriptions401,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getTransactionsSubscriptions>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTransactionsSubscriptionsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTransactionsSubscriptions>>
  > = ({ signal }) => getTransactionsSubscriptions(signal);

  return {
    queryKey,
    queryFn,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTransactionsSubscriptions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTransactionsSubscriptionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTransactionsSubscriptions>>
>;
export type GetTransactionsSubscriptionsQueryError =
  | GetTransactionsSubscriptions400
  | GetTransactionsSubscriptions401;

export function useGetTransactionsSubscriptions<
  TData = Awaited<ReturnType<typeof getTransactionsSubscriptions>>,
  TError = GetTransactionsSubscriptions400 | GetTransactionsSubscriptions401,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsSubscriptions>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransactionsSubscriptions>>,
          TError,
          Awaited<ReturnType<typeof getTransactionsSubscriptions>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTransactionsSubscriptions<
  TData = Awaited<ReturnType<typeof getTransactionsSubscriptions>>,
  TError = GetTransactionsSubscriptions400 | GetTransactionsSubscriptions401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsSubscriptions>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransactionsSubscriptions>>,
          TError,
          Awaited<ReturnType<typeof getTransactionsSubscriptions>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTransactionsSubscriptions<
  TData = Awaited<ReturnType<typeof getTransactionsSubscriptions>>,
  TError = GetTransactionsSubscriptions400 | GetTransactionsSubscriptions401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsSubscriptions>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Detectar assinaturas (heurística)
 */

export function useGetTransactionsSubscriptions<
  TData = Awaited<ReturnType<typeof getTransactionsSubscriptions>>,
  TError = GetTransactionsSubscriptions400 | GetTransactionsSubscriptions401,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsSubscriptions>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTransactionsSubscriptionsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
